`al`: Implement `PlayerHolder` and some utility functions
MonsterDruide1/OdysseyDecomp pull request #10
Opened 2022-01-10 03:09 UTC by OatmealDome

Some notes:
* I tried implementing `al::getAlivePlayerNum()` with a for loop, but the ordering of two `MOV W##, WZR` instructions would never be right. If I did it with a do-while (which I did in this PR), the ordering matches.
* `al::getPlayerPos()` is odd. The game's function uses two `BL`s in a row, but no matter what I do, I always get `BL`, `LDP`, and then `B`. If I remove the return statement, the function would then contain the two `BL`s, but the epilogue would no longer be correct.

2022-01-22 16:32 UTC, MonsterDruide1 requested changes
No, apparently there is no `sead` structure used in this. It looks pretty similar to `sead::PtrArray`, but that has its data members in a different order... so we'll go with a manual implementation here.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-:-Mu1Ynue2I51vVgwtw3R:byrzgt4)* status: all files reviewed, 8 unresolved discussions (waiting on @OatmealDome)

___
*[lib/al/util/PlayerUtil.h, line 18 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu0TG9T9UBI45Aaiko1:-Mu0TG9U2NEj_JbFor9X:b2vhn) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/lib/al/util/PlayerUtil.h#L18)):*
> ```objc
> LiveActor* tryFindAlivePlayerActorFirst(const PlayerHolder* holder);
> LiveActor* findAlivePlayerActorFirst(const PlayerHolder* holder);
> };  // namespace al
> ```

No semicolon at the end of a namespace
___
*[src/al/player/PlayerHolder.cpp, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1aQ_a0QD9zr0CAoPw:-Mu1aQ_a0QD9zr0CAoPx:b-fd1z6c) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/player/PlayerHolder.cpp#L3)):*
> ```cpp
> #include "al/player/PlayerHolder.h"
> 
> #include <string.h>
> ```

This include is useless after the other things in this file are fixed.
___
*[src/al/player/PlayerHolder.cpp, line 12 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1aZkrEKo8s2Q3GPiy:-Mu1aZkrEKo8s2Q3GPiz:b-hucdyr) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/player/PlayerHolder.cpp#L12)):*
> ```cpp
>     mBufferSize = count;
> 
>     Player* players = new Player[count];
> ```

This whole section below can be replaced with the inlined function
```
mPlayers = new Player[count];
clear();
```
___
*[src/al/player/PlayerHolder.cpp, line 29 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1agBc9c7TKMpSj3q4:-Mu1agBdDL245Tk-Ltup:b-n04twd) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/player/PlayerHolder.cpp#L29)):*
> ```cpp
> 
> void PlayerHolder::clear() {
>     if (mBufferSize >= 1) {
> ```

This manual check is not necessary, it is only inserted by the compiler for optimization on the loop.
___
*[src/al/util/PlayerUtil.cpp, line 16 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1bPHu0BYgYrwcpA-_:-Mu1bPHu0BYgYrwcpA-a:b-v27f3) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/util/PlayerUtil.cpp#L16)):*
> ```cpp
>     int player_num = holder->getPlayerNum();
> 
>     if (player_num < 1) {
> ```

This is another indication for a `for`-loop below. Removing this and using a for-loop to iterate should match here.
___
*[src/al/util/PlayerUtil.cpp, line 40 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1bv99AATkIV_OolKT:-Mu1bv99AATkIV_OolKU:b-tsjszi) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/util/PlayerUtil.cpp#L40)):*
> ```cpp
> 
> #ifdef NON_MATCHING
> sead::Vector3f* getPlayerPos(const PlayerHolder* holder, int index) {
> ```

This can be fixed by making the return type `const sead::Vector3f&` instead. Yay, compiler weirdness!
___
*[src/al/util/PlayerUtil.cpp, line 67 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1cDty0_kFQLRarxTm:-Mu1cDty0_kFQLRarxTn:b8qg4s1) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/util/PlayerUtil.cpp#L67)):*
> ```cpp
>     u32 player_num = holder->getPlayerNum();
> 
>     if (player_num == 0) {
> ```

Useless check before a `for`-loop.
___
*[src/al/util/PlayerUtil.cpp, line 84 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1cApYBSA2tl_TLnac:-Mu1cApYBSA2tl_TLnad:b-7tks5u) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/util/PlayerUtil.cpp#L84)):*
> ```cpp
>     u32 player_num = holder->getPlayerNum();
> 
>     if (player_num == 0) {
> ```

Another useless check before a `for`-loop.


<!-- Sent from Reviewable.io -->

2022-01-22 16:36 UTC, MonsterDruide1 requested changes
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10)* status: all files reviewed, 9 unresolved discussions (waiting on @OatmealDome)

___
*[lib/al/player/PlayerHolder.h, line 23 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1dDXG36zmv9ZAnbee:-Mu1dDXH8cJwJwMUxLcc:bkq7yny) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/lib/al/player/PlayerHolder.h#L23)):*
> ```objc
> private:
>     struct Player {
>         LiveActor* mActor;
> ```

It might be required to initialize these two things to `= nullptr` in the header to make the suggestion below work.


<!-- Sent from Reviewable.io -->

2022-02-07 23:52 UTC, OatmealDome reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10)* status: 3 of 8 files reviewed, 9 unresolved discussions (waiting on @MonsterDruide1)

___
*[lib/al/player/PlayerHolder.h, line 23 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1dDXG36zmv9ZAnbee:-MvL_k5n9SlObQym7mDU:bh68xu9) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/lib/al/player/PlayerHolder.h#L23)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

It might be required to initialize these two things to `= nullptr` in the header to make the suggestion below work.
</blockquote></details>

Done. It was, in fact, required. (I initially missed this comment and was struggling to try and get the below to match...)
___
*[lib/al/util/PlayerUtil.h, line 18 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu0TG9T9UBI45Aaiko1:-MvL_aRZBa3xLCrnim2S:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/lib/al/util/PlayerUtil.h#L18)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No semicolon at the end of a namespace
</blockquote></details>

Done.
___
*[src/al/player/PlayerHolder.cpp, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1aQ_a0QD9zr0CAoPw:-MvLaFvp0-R9_XiKEDdu:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/player/PlayerHolder.cpp#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This include is useless after the other things in this file are fixed.
</blockquote></details>

Done.
___
*[src/al/player/PlayerHolder.cpp, line 12 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1aZkrEKo8s2Q3GPiy:-MvL_Dw7BQrsNdZlw2Sg:b19w7dl) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/player/PlayerHolder.cpp#L12)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This whole section below can be replaced with the inlined function
```
mPlayers = new Player[count];
clear();
```
</blockquote></details>

Done. Thank you, this looks a lot cleaner. Seems I'm still stuck on trying to translate things from the pseudocode too literally, if that makes any sense.
___
*[src/al/player/PlayerHolder.cpp, line 29 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1agBc9c7TKMpSj3q4:-MvL_ODF6iorjkfbMPq2:b-hz5xxi) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/player/PlayerHolder.cpp#L29)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This manual check is not necessary, it is only inserted by the compiler for optimization on the loop.
</blockquote></details>

Done. Thanks for the tip, will keep in mind for the future.
___
*[src/al/util/PlayerUtil.cpp, line 16 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1bPHu0BYgYrwcpA-_:-MvL_XbF13pRASgQRnf1:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/util/PlayerUtil.cpp#L16)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This is another indication for a `for`-loop below. Removing this and using a for-loop to iterate should match here.
</blockquote></details>

Done.
___
*[src/al/util/PlayerUtil.cpp, line 40 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1bv99AATkIV_OolKT:-MvL_Y7b07_I2nKjzVdb:b-5sao8o) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/util/PlayerUtil.cpp#L40)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This can be fixed by making the return type `const sead::Vector3f&` instead. Yay, compiler weirdness!
</blockquote></details>

Done. Thanks for looking into it!
___
*[src/al/util/PlayerUtil.cpp, line 67 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1cDty0_kFQLRarxTm:-MvL_ZhB3hTRFgZWhQBq:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/util/PlayerUtil.cpp#L67)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless check before a `for`-loop.
</blockquote></details>

Done.
___
*[src/al/util/PlayerUtil.cpp, line 84 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1cApYBSA2tl_TLnac:-MvL__6rEQWrpiKLj_4e:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/util/PlayerUtil.cpp#L84)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Another useless check before a `for`-loop.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-08 00:00 UTC, MonsterDruide1 requested changes
> Reviewed 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10)* status: all files reviewed, 2 unresolved discussions (waiting on @OatmealDome)

___
*[src/al/player/PlayerHolder.cpp, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1aQ_a0QD9zr0CAoPw:-MvLcKf_8lFQWMilYp8r:b8vbc4e) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/player/PlayerHolder.cpp#L3)):*
<details><summary><i>Previously, OatmealDome wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you missed this one.
___
*[src/al/player/PlayerHolder.cpp, line 12 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1aZkrEKo8s2Q3GPiy:-MvLaGyP3H7RKAygblkM:b48slfh) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/player/PlayerHolder.cpp#L12)):*
<details><summary><i>Previously, OatmealDome wrote…</i></summary><blockquote>

Done. Thank you, this looks a lot cleaner. Seems I'm still stuck on trying to translate things from the pseudocode too literally, if that makes any sense.
</blockquote></details>

I only got to that from a suggestion by the BotW-community, so don't worry about it. There are a few common things (like the check before a loop) that you'll pick up and memorize when dealing with more of those things, but some are a bit more complicated. Remember, we're essentially "reversing" the compilers optimizations, which took years to come up with.
___
*[src/al/util/PlayerUtil.cpp, line 33 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-MvLc0ETCn6Tg4FKfCrH:-MvLc0ETCn6Tg4FKfCrI:b-1ttcen) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/65550beb509152d67a9e7bace2500ff84d585115/src/al/util/PlayerUtil.cpp#L33)):*
> ```cpp
> const sead::Vector3f& getPlayerPos(const PlayerHolder* holder, int index) {
>     LiveActor* player = holder->tryGetPlayer(index);
>     return *getTrans(player);
> ```

Please rebase this branch to the latest master. This `*` will have to disappear then, as Fruityloops recently changed the return type of `getTrans` to a pointer (which makes sense here).


<!-- Sent from Reviewable.io -->

2022-02-08 00:43 UTC, OatmealDome reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[src/al/player/PlayerHolder.cpp, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-Mu1aQ_a0QD9zr0CAoPw:-MvLmDZwEofaamdfjRVd:b-39v3cp) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/aaef88144b2f2efc37d6d61de352dad33662e54b/src/al/player/PlayerHolder.cpp#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Looks like you missed this one.
</blockquote></details>

Whoops, fixed.
___
*[src/al/util/PlayerUtil.cpp, line 33 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-MvLc0ETCn6Tg4FKfCrH:-MvLlhvt5uo6zOf7M5e6:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/65550beb509152d67a9e7bace2500ff84d585115/src/al/util/PlayerUtil.cpp#L33)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Please rebase this branch to the latest master. This `*` will have to disappear then, as Fruityloops recently changed the return type of `getTrans` to a pointer (which makes sense here).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-08 08:59 UTC, MonsterDruide1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-:-MvNYnpKD0LUzSBEkiM1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OatmealDome)

___
*[src/al/util/PlayerUtil.cpp, line 33 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/10#-MvLc0ETCn6Tg4FKfCrH:-MvNYgsYDs05wOURNwSo:b2bphlq) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/65550beb509152d67a9e7bace2500ff84d585115/src/al/util/PlayerUtil.cpp#L33)):*
<details><summary><i>Previously, OatmealDome wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant a reference, but seems like you understood what I said :+1: 


<!-- Sent from Reviewable.io -->

2022-02-08 09:00 UTC, merged