Player: Implement PlayerJudgeWallCatch
MonsterDruide1/OdysseyDecomp pull request #103
Opened 2024-06-19 12:04 UTC by MonsterDruide1

The first Judge with a bit more logic to it! To grab onto a wall (start wall slide), the following criteria have to be true:
1. Do not carry anything
2. Not in 2D-section
3. Not forced to run (RocketFlower)
4. No external force applied to Mario (for example moving ground, but might be more?)
5. Currently colliding with a wall
6. Currently not colliding with the ground
7. The wall does not have any `NoWallGrab` code (`NoAction, NoWallGrab, ReflectStickNoWallGrab, OnlyWallHitDown, GrabCeil, Pole, Needle, DamageFire`)
8. If currently in `PlayerTrigger::Action_val30` (as far as I can tell enabled when doing a backflip and sideflip), have the stick pressed more than 41% (`length^2 > 0.64`)
9. Finally, succeed in finding a `WallCatchPos`

2024-06-19 15:02 UTC, GRAnimated requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/103)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerJudgeWallCatch.h` line 46 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/103#-O-l003J4P6-9ASIcVjj:-O-l003J4P6-9ASIcVjk:b6a2qcn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/123a8a801d6e3020045c8afbf6735519e80f3ad7/src/Player/PlayerJudgeWallCatch.h#L46)):*
> ```objc
>     const PlayerTrigger* mTrigger;
>     const PlayerCounterForceRun* mCounterForceRun;
>     bool mIsJudge = 0;
> ```

false instead of 0


<!-- Sent from Reviewable.io -->

2024-06-19 18:34 UTC, tetraxile reviewed
"external force" also includes the wind gusts in snow kingdom, as well as the ExtForceAreas that push mario down in the waterfalls in cascade and mushroom.

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/103#-:-O-llSQ9Eo_pIy61Ts7t:b-4rxthk)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)



<!-- Sent from Reviewable.io -->

2024-06-19 21:14 UTC, MonsterDruide1 reviewed
Ah, thanks for the additional info!

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/103#-:-O-mLC-707yikLQleHjX:bc9yldj)* status: all files reviewed, 1 unresolved discussion (waiting on @GRAnimated)

___
*[`src/Player/PlayerJudgeWallCatch.h` line 46 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/103#-O-l003J4P6-9ASIcVjj:-O-mLISM1R1bufvHojHt:b-39v3cp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/123a8a801d6e3020045c8afbf6735519e80f3ad7/src/Player/PlayerJudgeWallCatch.h#L46)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

false instead of 0
</blockquote></details>

Whoops, fixed.


<!-- Sent from Reviewable.io -->

2024-06-20 21:58 UTC, GRAnimated approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/103)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)



<!-- Sent from Reviewable.io -->

2024-06-22 21:23 UTC, merged