Library/Obj: Implement `EffectObj`, `EffectObjCameraEmit`, `EffectObjFollowCamera`, `EffectObjFollowCameraLimit`, `EffectObjFunction` and `EffectObjInterval`
MonsterDruide1/OdysseyDecomp pull request #128
Opened 2024-07-07 14:23 UTC by Fuzzy2319

This PR adds `EffectObj`, `EffectObjCameraEmit`, `EffectObjFollowCamera`, `EffectObjFollowCameraLimit`, `EffectObjFunction` and `EffectObjInterval` implementation. I also moved `MoveType` in it's own header.

2024-07-07 15:07 UTC, MonsterDruide1 requested changes
> Reviewed 20 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128)* status: 20 of 25 files reviewed, 19 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/Library/Effect/EffectKeeper.h` line 59 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1ChXeP9JZN5yaACs0H:-O1ChXeP9JZN5yaACs0I:b63wkd1) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Effect/EffectKeeper.h#L59)):*
> ```objc
> }  // namespace al
> 
> class alEffectFunction {
> ```

If it's not `friend` with anything (yet), it should be `namespace alEffectFunction` and non-static functions.
___
*[`lib/al/Library/LiveActor/ActorInitFunction.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Chiuz18URAXRMI5N6:-O1Chiuz18URAXRMI5N7:b-wq09st) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/LiveActor/ActorInitFunction.h#L3)):*
> ```objc
> #pragma once
> 
> #include <math/seadMatrix.h>
> ```

Useless include
___
*[`lib/al/Library/LiveActor/ActorInitFunction.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1ChgxC3FKdKmTHyK1F:-O1ChgxC3FKdKmTHyK1G:bhwj4wg) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/LiveActor/ActorInitFunction.h#L9)):*
> ```objc
> class LiveActor;
> class Resource;
> class HitSensor;
> ```

Useless forwards-declare
___
*[`lib/al/Library/Obj/EffectObj.cpp` line 39 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Ce9GD9Dv3ZyfE6YpO:-O1Ce9GD9Dv3ZyfE6YpP:b-ak073s) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObj.cpp#L39)):*
> ```cpp
> 
>     listenStageSwitchOnOff(this, "OnKillOffAppearSwitch", EffectObjFunctor(this, &EffectObj::kill),
>                            EffectObjFunctor(this, &EffectObj::appear));
> ```

Maybe you can call the constructor implicitly, then you don't need the `using` at the top: `listenStageSwitchOnOff(this, "...", {this, &EffectObj::kill}, {...});`



_Code quote:_
```cpp
    listenStageSwitchOnOff(this, "OnKillOffAppearSwitch", EffectObjFunctor(this, &EffectObj::kill),
                           EffectObjFunctor(this, &EffectObj::appear));
```
___
*[`lib/al/Library/Obj/EffectObj.cpp` line 63 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CeMJB9tVxqvtg5I40:-O1CeMJB9tVxqvtg5I41:botupnc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObj.cpp#L63)):*
> ```cpp
>         if (mMtxConnector != nullptr)
>             connectPoseQT(this, mMtxConnector);
>     } else {
> ```

Flip this logic a bit



_Suggestion:_
```cpp
    if (isExistRail(this)) {
        ...
    } else if (mMtxConnector != nullptr)
        connectPoseQT(this, mMtxConnector);
```
___
*[`lib/al/Library/Obj/EffectObj.cpp` line 67 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CdhkTBsAKFhdsYQzf:-O1CdhkTBsAKFhdsYQzg:b-5tfmk9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObj.cpp#L67)):*
> ```cpp
>         default:
>             moveSyncRail(this, mRailMoveSpeed);
>             break;
> ```

`default` should go last



_Code quote:_
```cpp
        default:
            moveSyncRail(this, mRailMoveSpeed);
            break;
```
___
*[`lib/al/Library/Obj/EffectObjCameraEmit.cpp` line 18 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Ceo3F3d9KXFiGKWy4:-O1Ceo3F3d9KXFiGKWy5:bm6g3r6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjCameraEmit.cpp#L18)):*
> ```cpp
> 
> void EffectObjCameraEmit::init(const ActorInitInfo& info) {
>     using EffectObjCameraEmitFunctor =
> ```

Same here, maybe not required?
___
*[`lib/al/Library/Obj/EffectObjFollowCamera.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Ci4Yd8dTw2YZf8c3D:-O1Ci4Yd8dTw2YZf8c3E:bkcbire) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCamera.h#L4)):*
> ```objc
> 
> #include "Library/LiveActor/LiveActor.h"
> #include "Library/Nerve/NerveSetupUtil.h"
> ```

Useless include then
___
*[`lib/al/Library/Obj/EffectObjFollowCamera.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CetuqBYtafXLhZewz:-O1CetuqBYtafXLhZex-:b-wik660) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCamera.h#L27)):*
> ```objc
> NERVE_IMPL(EffectObjFollowCamera, Wait)
> NERVE_IMPL(EffectObjFollowCamera, Disappear)
> }  // namespace
> ```

Should go at the top of `cpp`, not the header



_Code quote:_
```objc
namespace {
NERVE_IMPL(EffectObjFollowCamera, Wait)
NERVE_IMPL(EffectObjFollowCamera, Disappear)
}  // namespace
```
___
*[`lib/al/Library/Obj/EffectObjFollowCamera.cpp` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CfBpd8LTQxJ4tpRWS:-O1CfBpd8LTQxJ4tpRWT:b-qtvjtj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCamera.cpp#L25)):*
> ```cpp
> 
> void EffectObjFollowCamera::init(const ActorInitInfo& info) {
>     using EffectObjFollowCameraFunctor =
> ```

Maybe not required
___
*[`lib/al/Library/Obj/EffectObjFollowCameraLimit.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1ChwwK85cZxDpkD_CL:-O1ChwwK85cZxDpkD_CM:bkcbire) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCameraLimit.h#L4)):*
> ```objc
> 
> #include "Library/LiveActor/LiveActor.h"
> #include "Library/Nerve/NerveSetupUtil.h"
> ```

Useless include then
___
*[`lib/al/Library/Obj/EffectObjFollowCameraLimit.h` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CfbSD3J7KRmF0eMjK:-O1CfbSD3J7KRmF0eMjL:b-4mymfq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCameraLimit.h#L31)):*
> ```objc
> NERVE_IMPL(EffectObjFollowCameraLimit, Wait)
> NERVE_IMPL(EffectObjFollowCameraLimit, Disappear)
> }  // namespace
> ```

Top of cpp



_Code quote:_
```objc
namespace {
NERVE_IMPL(EffectObjFollowCameraLimit, Wait)
NERVE_IMPL(EffectObjFollowCameraLimit, Disappear)
}  // namespace
```
___
*[`lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CfeOJ97lFCwounG6L:-O1CfeOJ97lFCwounG6M:b-qtvjtj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp#L27)):*
> ```cpp
> 
> void EffectObjFollowCameraLimit::init(const ActorInitInfo& info) {
>     using EffectObjFollowCameraLimitFunctor =
> ```

Maybe not required
___
*[`lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp` line 73 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CfoTA4VAokYIHmxBv:-O1CfoTA4VAokYIHmxBw:b2md66x) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp#L73)):*
> ```cpp
> 
>     calcCameraFront(&front, this, 0);
>     pos.set(*getCameraPos(this, 0));
> ```

Change the return type of `getCameraPos` to `const sead::Vector3f&`, if that doesn't mess up anything else.
___
*[`lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp` line 90 at r1](https://reviewable.io/r [...]

2024-07-07 17:07 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128)* status: 20 of 25 files reviewed, 19 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Effect/EffectKeeper.h` line 59 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1ChXeP9JZN5yaACs0H:-O1CrPWEChd0HxSXUt33:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Effect/EffectKeeper.h#L59)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

If it's not `friend` with anything (yet), it should be `namespace alEffectFunction` and non-static functions.
</blockquote></details>

Done.
___
*[`lib/al/Library/LiveActor/ActorInitFunction.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Chiuz18URAXRMI5N6:-O1D60R82-qnN_lEnKNd:bxqu7hb) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/LiveActor/ActorInitFunction.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include
</blockquote></details>

It doesn't compile without.
![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/kpFv5ZItgpmHTdkkBHHkFV4n/image.png)
___
*[`lib/al/Library/LiveActor/ActorInitFunction.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1ChgxC3FKdKmTHyK1F:-O1D62PWEds-1OkLlbAR:b2nreh6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/LiveActor/ActorInitFunction.h#L9)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless forwards-declare
</blockquote></details>

Same as above.
___
*[`lib/al/Library/Obj/EffectObj.cpp` line 39 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Ce9GD9Dv3ZyfE6YpO:-O1CsvKTEp6TuE8crqmU:b8r283g) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObj.cpp#L39)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Maybe you can call the constructor implicitly, then you don't need the `using` at the top: `listenStageSwitchOnOff(this, "...", {this, &EffectObj::kill}, {...});`
</blockquote></details>

It doesn't compile.
![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/iQdvPBdGOCDrdydzsh3f-49u/image.png)
___
*[`lib/al/Library/Obj/EffectObj.cpp` line 63 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CeMJB9tVxqvtg5I40:-O1CtyGWCQL1SeEjVn0Z:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObj.cpp#L63)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Flip this logic a bit
</blockquote></details>

Done.
___
*[`lib/al/Library/Obj/EffectObj.cpp` line 67 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CdhkTBsAKFhdsYQzf:-O1Ctz-F-uZduPKRI-p0:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObj.cpp#L67)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`default` should go last
</blockquote></details>

Done.
___
*[`lib/al/Library/Obj/EffectObjCameraEmit.cpp` line 18 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Ceo3F3d9KXFiGKWy4:-O1D68EE3E5iYfBvYNMX:b-5oo5dr) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjCameraEmit.cpp#L18)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Same here, maybe not required?
</blockquote></details>

Same as `EffectObj`
___
*[`lib/al/Library/Obj/EffectObjFollowCamera.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Ci4Yd8dTw2YZf8c3D:-O1CucJ0EUnP0xHhuNtZ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCamera.h#L4)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include then
</blockquote></details>

Done.
___
*[`lib/al/Library/Obj/EffectObjFollowCamera.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CetuqBYtafXLhZewz:-O1CudJe9DsaTO_EbVV3:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCamera.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should go at the top of `cpp`, not the header
</blockquote></details>

Done.
___
*[`lib/al/Library/Obj/EffectObjFollowCamera.cpp` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CfBpd8LTQxJ4tpRWS:-O1D6Ga43jHaQPA8J7gm:b-5oo5dr) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCamera.cpp#L25)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Maybe not required
</blockquote></details>

Same as `EffectObj`
___
*[`lib/al/Library/Obj/EffectObjFollowCameraLimit.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1ChwwK85cZxDpkD_CL:-O1Cuy1b-2ChvPslyg90:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCameraLimit.h#L4)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include then
</blockquote></details>

Done.
___
*[`lib/al/Library/Obj/EffectObjFollowCameraLimit.h` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CfbSD3J7KRmF0eMjK:-O1Cuyhf7NDsVTWA-HB7:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCameraLimit.h#L31)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Top of cpp
</blockquote></details>

Done.
___
*[`lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CfeOJ97lFCwounG6L:-O1D6ICU9OB7F_G3lYhP:b-5oo5dr) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Maybe not required
</blockquote></details>

Same as `EffectObj`
___
*[`lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp` line 73 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CfoTA4VAokYIHmxBv:-O1CvZhx3Ez2Rf8yV4tf:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFollowCameraLimit.cpp#L73)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Change the return type of `getCameraPos` to `const sead::Vector3f&`, if that doesn't mess up anything else.
</blockquote></details>

Done.
___
*[`lib/al/Library/Obj/EffectObjFunction.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CiU8b85aQeb9D130o:-O1CxiPaE0_nQ77qE6Nw:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFunction.h#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No friend class => `namespace`
</blockquote></details>

Done.
___
*[`lib/al/Library/Obj/EffectObjFunction.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/Odysse [...]

2024-07-07 20:50 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 25 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128)* status: all files reviewed, 2 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/Library/LiveActor/ActorInitFunction.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Chiuz18URAXRMI5N6:-O1DvmYk7Jw_e80VIqZn:b-strk03) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/LiveActor/ActorInitFunction.h#L3)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

It doesn't compile without.
![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/kpFv5ZItgpmHTdkkBHHkFV4n/image.png)
</blockquote></details>

Okay, so it should've failed to compile before already, but we don't have enough checks.
___
*[`lib/al/Library/Obj/EffectObj.cpp` line 39 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Ce9GD9Dv3ZyfE6YpO:-O1DvtUdDFAo4FhGZo4E:b-529w6a) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObj.cpp#L39)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

It doesn't compile.
![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/iQdvPBdGOCDrdydzsh3f-49u/image.png)
</blockquote></details>

Alright, keep it like this then.
___
*[`lib/al/Library/Obj/EffectObjFunction.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CiKPHD69CIwO5BWfe:-O1DwbiJ7054sk3TgsMY:b-9xh4on) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFunction.h#L12)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

The function is listed in 3rd position in the binary but is used in the first function so it has to be defined in the header otherwise the compiler will throw an error.
</blockquote></details>

Hmm, interesting. I don't think we have tested around with unnamed functions too much, so ... let's just keep it like this for the moment then.
___
*[`lib/al/Library/Obj/EffectObjFunction.cpp` line 14 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Cibht1TRuEl4h4Oot:-O1DwuYeA7Bv06X8dKxF:b-hmx9g9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFunction.cpp#L14)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

It doesn't match without
![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/J-xHAQtupP9Sa2Q32pJuM2A7/image.png)
</blockquote></details>

Ah, now I get it: It's an inlined call to `initActorEffectObj(actor, info, model)`!
___
*[`lib/al/Library/Obj/EffectObjInterval.cpp` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CguYE1A0XkTVkzqHm:-O1DxV-E9iUkb7q5WH1p:bvwhh1q) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjInterval.cpp#L31)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

It doesn't match
![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/_5wCNBeQxdxpfSGNlQjjPDhk/image.png)
</blockquote></details>

decomp.me?


<!-- Sent from Reviewable.io -->

2024-07-08 07:24 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Obj/EffectObjFunction.cpp` line 14 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1Cibht1TRuEl4h4Oot:-O1GDDjf91ONY3mjZomv:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjFunction.cpp#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Ah, now I get it: It's an inlined call to `initActorEffectObj(actor, info, model)`!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-08 15:34 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Obj/EffectObjInterval.cpp` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CguYE1A0XkTVkzqHm:-O1Hyikd8Y168zGYIi6N:b-i04fj9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjInterval.cpp#L31)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

^ still open, in case you missed it
</blockquote></details>

https://decomp.me/scratch/UigwA


<!-- Sent from Reviewable.io -->

2024-07-08 15:40 UTC, MonsterDruide1 requested changes
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/Library/Obj/EffectObjInterval.cpp` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CguYE1A0XkTVkzqHm:-O1Hzoxx8-rCZwlEmAbC:b-ttxo4f) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjInterval.cpp#L31)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

https://decomp.me/scratch/UigwA
</blockquote></details>

Alright, can't get my good ideas to match either, so probably go with this:

if(tryGetArg(...))
  mTimer = mFirstEmitFrame;
else
  mTimer = 0;

That at least makes it explicitly two different assignments (mFirstEmitFrame and mTimer), instead of a ternary.


<!-- Sent from Reviewable.io -->

2024-07-08 15:53 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Obj/EffectObjInterval.cpp` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128#-O1CguYE1A0XkTVkzqHm:-O1I2GA79KOn2rVG5zqU:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/125c926343f217964869fd87363d3d7f7a42d0d3/lib/al/Library/Obj/EffectObjInterval.cpp#L31)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Alright, can't get my good ideas to match either, so probably go with this:

if(tryGetArg(...))
  mTimer = mFirstEmitFrame;
else
  mTimer = 0;

That at least makes it explicitly two different assignments (mFirstEmitFrame and mTimer), instead of a ternary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-08 15:55 UTC, MonsterDruide1 approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/128)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)



<!-- Sent from Reviewable.io -->

2024-07-09 19:26 UTC, merged