Compess
MonsterDruide1/OdysseyDecomp pull request #139
Opened 2024-07-30 14:41 UTC by Wexos

`Compass` layout class.

`Compass::appear` is unfinished, `Compass::updateLayout` is not implemented.

Constructor doesn't match due to different VTable. Originally it looks like:
```
al::LayoutActor::getNerveKeeper
Compass::appear
al::LayoutActor::kill
al::LayoutActor::movement
al::LayoutActor::calcAnim
al::LayoutActor::getName
al::LayoutActor::getEffectKeeper
al::LayoutActor::getAudioKeeper
al::LayoutActor::getLayoutActionKeeper
al::LayoutActor::getLayoutKeeper
al::LayoutActor::getCameraDirector
al::LayoutActor::getSceneObjHolder
al::LayoutActor::getMessageSystem
al::LayoutActor::control
```

Decompiled it looks like:
```
al::LayoutActor::getNerveKeeper
Compass::appear
al::LayoutActor::kill
al::LayoutActor::control
al::LayoutActor::calcAnim
al::LayoutActor::movement
al::LayoutActor::getName
al::LayoutActor::getEffectKeeper
al::LayoutActor::getAudioKeeper
al::LayoutActor::getLayoutActionKeeper
al::LayoutActor::getLayoutKeeper
al::LayoutActor::getCameraDirector
al::LayoutActor::getSceneObjHolder
al::LayoutActor::getMessageSystem
```

I don't think the overloads of `isInAreaObj` and `tryFindAreaObj` that I added are in the correct object file (I at least don't think it should be in the same object file as the existing overloads). However, I have no idea where they should be.

2024-07-30 16:00 UTC, GRAnimated requested changes
Please run `tools/check-format.py` and fix formatting errors.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-:-O33Lbf31vhOM4ppilfa:b-h8h9uf)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @Wexos)

___
*[`lib/al/Library/Area/AreaObjUtil.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33HVZdDVo619wcrPYP:-O33HVZdDVo619wcrPYQ:b-h81nrl) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/lib/al/Library/Area/AreaObjUtil.h#L9)):*
> ```objc
> class LiveActor;
> 
> bool isInAreaObj(const IUseAreaObj* area, const char* name, const sead::Vector3f& pos);
> ```

SMO Decomp Function Map: https://docs.google.com/spreadsheets/d/198vrkkDqktrRDLInSAkK2HsG5hy1Fl8cmCNRMND3nCY/edit?gid=4087080#gid=4087080
That spreadsheet should probably get linked in the repo somewhere, but refer to that for the future. The file location for those functions are good, but adjust the order to how it's linked based on the object
___
*[`src/Layout/Compass.h` line 26 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33FVHID9eYQPQv9vUz:-O33FVHID9eYQPQv9vV-:b-nq5kqv) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/src/Layout/Compass.h#L26)):*
> ```objc
> 
> private:
>     al::SceneCameraInfo* mSceneCamInfo;
> ```

Initialize these with the default values you create in the constructor.



_Code quote:_
```objc
    al::SceneCameraInfo* mSceneCamInfo;
    const al::PlayerHolder* mPlayerHolder;
    sead::Vector3f m140;
    f32 m14C;
```
___
*[`src/Layout/Compass.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33Luqt4T6aku9e7GP2:-O33Luqt4T6aku9e7GP3:b-swoulq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/src/Layout/Compass.h#L28)):*
> ```objc
>     al::SceneCameraInfo* mSceneCamInfo;
>     const al::PlayerHolder* mPlayerHolder;
>     sead::Vector3f m140;
> ```

Unknown variables shouldn't be prefixed with `m` as it causes a formatting error from the format script. `field_` is the preferred prefix for these.



_Code quote:_
```objc
    sead::Vector3f m140;
    f32 m14C;
```
___
*[`src/Layout/Compass.cpp` line 21 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33KeIaAI6iqGq_5eR_:-O33KeIaAI6iqGq_5eRa:by705mz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/src/Layout/Compass.cpp#L21)):*
> ```cpp
> }
> 
> Compass::Compass(const char* name, const al::LayoutInitInfo& info, const al::PlayerHolder* playerHolder) :
> ```

`tools/decompme` on this function and reply with the link, it provides a playground that we can test modifying the `LayoutActor.h` header to make the proper vtable to match this.
___
*[`src/Layout/Compass.cpp` line 34 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33GXBn0hBoa_btrzOW:-O33GXBn0hBoa_btrzOX:bs884fz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/src/Layout/Compass.cpp#L34)):*
> ```cpp
> }
> 
> /*void Compass::appear() {
> ```

Please run `tools/decompme` on this function and reply with the link here or in Discord, so this can hopefully be matched. Unfinished functions don't have to be commented out either, just add a comment above it like `NON_MATCHING: Unfinished`
___
*[`src/Layout/Compass.cpp` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33G-Qb5QdaoD7XnaBS:-O33G-Qb5QdaoD7XnaBT:b6tk233) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/src/Layout/Compass.cpp#L37)):*
> ```cpp
>     GameDataHolderAccessor accessor(this);
> 
>     if (GameDataFunction::isMainStage(accessor)) {
> ```

The compiler should let you pass `this` directly in instead of explicitly creating an accessor variable


<!-- Sent from Reviewable.io -->

2024-07-30 16:04 UTC, GRAnimated requested changes
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @Wexos)

___
*[`src/Layout/Compass.cpp` line 21 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33KeIaAI6iqGq_5eR_:-O33NajpBd4jidCYjOsa:bbdq8sv) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/src/Layout/Compass.cpp#L21)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

`tools/decompme` on this function and reply with the link, it provides a playground that we can test modifying the `LayoutActor.h` header to make the proper vtable to match this.
</blockquote></details>

Remove initializers for variables in favor of doing it in the header


<!-- Sent from Reviewable.io -->

2024-08-01 05:15 UTC, GRAnimated reviewed
> Reviewed 1 of 5 files at r1, 4 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @Wexos)



<!-- Sent from Reviewable.io -->

2024-08-02 09:31 UTC, Wexos reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @GRAnimated)

___
*[`lib/al/Library/Area/AreaObjUtil.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33HVZdDVo619wcrPYP:-O3HQ3Zq5gu4cYsJTEuf:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/lib/al/Library/Area/AreaObjUtil.h#L9)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

SMO Decomp Function Map: https://docs.google.com/spreadsheets/d/198vrkkDqktrRDLInSAkK2HsG5hy1Fl8cmCNRMND3nCY/edit?gid=4087080#gid=4087080
That spreadsheet should probably get linked in the repo somewhere, but refer to that for the future. The file location for those functions are good, but adjust the order to how it's linked based on the object
</blockquote></details>

Done.
___
*[`src/Layout/Compass.cpp` line 34 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33GXBn0hBoa_btrzOW:-O3HQDApAWjkJD1Y8hdE:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/src/Layout/Compass.cpp#L34)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

Please run `tools/decompme` on this function and reply with the link here or in Discord, so this can hopefully be matched. Unfinished functions don't have to be commented out either, just add a comment above it like `NON_MATCHING: Unfinished`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-02 13:29 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 5 files at r1, 3 of 7 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: all files reviewed, 10 unresolved discussions (waiting on @GRAnimated and @Wexos)

___
*[`lib/al/Library/Area/AreaObjUtil.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33HVZdDVo619wcrPYP:-O3I7jKv9NuTheBtgB2B:b-ve2b9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/lib/al/Library/Area/AreaObjUtil.h#L9)):*
<details><summary><i>Previously, Wexos wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should be flipped: `tryFindAreaObj` first, then `isInAreaObj`.
___
*[`lib/al/Library/LiveActor/ActorAreaFunction.h` line 11 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3I8f0o8U6Tzw4fopZ-:-O3I8f0o8U6Tzw4fopZ0:b-mopk9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/lib/al/Library/LiveActor/ActorAreaFunction.h#L11)):*
> ```objc
> bool isInDeathArea(const LiveActor*);
> 
> AreaObj* tryFindAreaObj(const LiveActor*, const char*);
> ```

I was just about to comment on please re-adding those here, great that you already took care of that! :+1:
___
*[`src/Layout/Compass.h` line 17 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3I9KmEAXJyRcdgnPAr:-O3I9KmF5groZGoeqolO:bak0qt5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/Compass.h#L17)):*
> ```objc
>     Compass(const char* name, const al::LayoutInitInfo& info, const al::PlayerHolder* playerHolder);
> 
>     virtual void appear() override;
> ```

Remove the `virtual` if `override` is already given
___
*[`src/Layout/Compass.cpp` line 61 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IAN8T7IH-aEqJFzyN:-O3IAN8T7IH-aEqJFzyO:bh6av1k) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/Compass.cpp#L61)):*
> ```cpp
>         sead::Vector3f camDir { 0.0f, 0.0f, 0.0f };
> 
>         if (al::tryCalcCameraLookDirH(&camDir, mSceneCamInfo, sead::Vector3f::ey, 0)) {
> ```

Flip this logic, using early `return` when hit instead
___
*[`src/Layout/Compass.cpp` line 64 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IASEp08VF45NVlo_4:-O3IASEp08VF45NVlo_5:b-3i51t7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/Compass.cpp#L64)):*
> ```cpp
>             sead::Vector3f northDir { 0.0f, 0.0f, 0.0f };
> 
>             if (rs::tryCalcMapNorthDir(&northDir, this)) {
> ```

Same here, early-return instead
___
*[`src/Layout/Compass.cpp` line 77 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IAUJg025Kdsjm6viL:-O3IAUJg025Kdsjm6viM:bjxs4v5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/Compass.cpp#L77)):*
> ```cpp
>         al::LiveActor* player = al::tryGetPlayerActor(mPlayerHolder, 0);
> 
>         if (player != nullptr && al::isInAreaObj(player, "CompassArea", al::getTrans(player))) {
> ```

Early-return instead
___
*[`src/Layout/MapLayout.h` line 14 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IGQdBCfF8vauNlDse:-O3IGQdBCfF8vauNlDsf:bew9dfz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/MapLayout.h#L14)):*
> ```objc
>                     const sead::Vector2f&, f32, f32);
> bool tryCalcMapNorthDir(sead::Vector3f*, const al::IUseSceneObjHolder*);
> void getMapViewProjMtx(const al::IUseSceneObjHolder*);
> ```

Type: `const sead::Matrix34f&
___
*[`src/Layout/MapLayout.h` line 15 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IGUkQEoVHSGFFQU91:-O3IGUkRDI_16WD2_JCE:b-cc6k7c) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/MapLayout.h#L15)):*
> ```objc
> bool tryCalcMapNorthDir(sead::Vector3f*, const al::IUseSceneObjHolder*);
> void getMapViewProjMtx(const al::IUseSceneObjHolder*);
> void getMapProjMtx(const al::IUseSceneObjHolder*);
> ```

Type: `const sead::Matrix34f&appearmap
___
*[`src/Layout/MapLayout.h` line 27 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IGyaf0lCsFJS-VbD4:-O3IGyag-O59uFGB7UX5:b-8qhcsq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/MapLayout.h#L27)):*
> ```objc
> namespace StageMapFunction {
> void getStageMapScaleMin();
> void getStageMapScaleMax();
> ```

Types: Both `f32`



_Code quote:_
```objc
void getStageMapScaleMin();

void getStageMapScaleMax();
```


<!-- Sent from Reviewable.io -->

2024-08-03 21:25 UTC, Wexos reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: 7 of 11 files reviewed, 10 unresolved discussions (waiting on @GRAnimated and @MonsterDruide1)

___
*[`lib/al/Library/Area/AreaObjUtil.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33HVZdDVo619wcrPYP:-O3P7HSj2suZCjpBGVfA:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/lib/al/Library/Area/AreaObjUtil.h#L9)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should be flipped: `tryFindAreaObj` first, then `isInAreaObj`.
</blockquote></details>

Done.
___
*[`src/Layout/Compass.h` line 17 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3I9KmEAXJyRcdgnPAr:-O3P6Sk--t9t-XVd8D5z:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/Compass.h#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Remove the `virtual` if `override` is already given
</blockquote></details>

Done.
___
*[`src/Layout/Compass.cpp` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O33G-Qb5QdaoD7XnaBS:-O3P6J3z-f8UJogYQcGM:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ca4bbedadde6082c96ca520b52d22a9edb7d05d2/src/Layout/Compass.cpp#L37)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

The compiler should let you pass `this` directly in instead of explicitly creating an accessor variable
</blockquote></details>

Done.
___
*[`src/Layout/Compass.cpp` line 61 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IAN8T7IH-aEqJFzyN:-O3P6Jx_7Mr15cHLD6qM:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/Compass.cpp#L61)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Flip this logic, using early `return` when hit instead
</blockquote></details>

Done.
___
*[`src/Layout/Compass.cpp` line 64 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IASEp08VF45NVlo_4:-O3P6KG97WD43dpUa7jK:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/Compass.cpp#L64)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Same here, early-return instead
</blockquote></details>

Done.
___
*[`src/Layout/Compass.cpp` line 77 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IAUJg025Kdsjm6viL:-O3P6KuG22NMnOpMDORr:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/Compass.cpp#L77)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Early-return instead
</blockquote></details>

Done.
___
*[`src/Layout/MapLayout.h` line 14 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IGQdBCfF8vauNlDse:-O3P6ZbU5UJpq46_fAnN:b-7m98ny) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/MapLayout.h#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Type: `const sead::Matrix34f&
</blockquote></details>

It's a projection matrix, so I would assume a 4x4 matrix. But I guess it's possible to have 3x4 matrix for orthogonal projection. Let me know if it should really be 3x4.
___
*[`src/Layout/MapLayout.h` line 15 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IGUkQEoVHSGFFQU91:-O3P6r8K2vSH1rBgrNu2:b2nreh6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/MapLayout.h#L15)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Type: `const sead::Matrix34f&appearmap
</blockquote></details>

Same as above.
___
*[`src/Layout/MapLayout.h` line 27 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IGyaf0lCsFJS-VbD4:-O3P6tCn6ahELUNMbDuy:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/MapLayout.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Types: Both `f32`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-03 21:36 UTC, GRAnimated reviewed
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: 10 of 11 files reviewed, 8 unresolved discussions (waiting on @MonsterDruide1)



<!-- Sent from Reviewable.io -->

2024-08-03 22:08 UTC, MonsterDruide1 requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: all files reviewed, 1 unresolved discussion (waiting on @Wexos)

___
*[`src/Layout/Compass.cpp` line 36 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3PH4GIDE6PY1JBKOYu:-O3PH4GIDE6PY1JBKOYv:b7hs6qm) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c889a053522d60479e79e16f8cc531402dac9def/src/Layout/Compass.cpp#L36)):*
> ```cpp
> }
> 
> // NON_MATCHING: https://decomp.me/scratch/pPVat
> ```

https://decomp.me/scratch/FqBF8
I'm not sure where this inlined function should be placed though - either extract the string constant to a parameter and move it to a utility header, or keep it in like this and local to the `cpp`.
___
*[`src/Layout/MapLayout.h` line 14 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IGQdBCfF8vauNlDse:-O3PDzW278TbWVLS6F4H:bgtwvt2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/MapLayout.h#L14)):*
<details><summary><i>Previously, Wexos wrote…</i></summary><blockquote>

It's a projection matrix, so I would assume a 4x4 matrix. But I guess it's possible to have 3x4 matrix for orthogonal projection. Let me know if it should really be 3x4.
</blockquote></details>

20 minutes of investigation and tracing return types later: You're right, this is actually a `Matrix44f`. Thanks for not trusting me blindly.
___
*[`src/Layout/MapLayout.h` line 15 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3IGUkQEoVHSGFFQU91:-O3PEV-o7kloTtoAKhnb:b6bpy94) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3341bd2d291dcf93f935142c54682f3a2236b1b7/src/Layout/MapLayout.h#L15)):*
<details><summary><i>Previously, Wexos wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Same, supposed to be a `Matrix44f`


<!-- Sent from Reviewable.io -->

2024-08-05 19:53 UTC, Wexos reviewed
Sorry that it's taking so long, I have some other stuff I need/want to work on.

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-:-O3Z5IZhCJh92bg6gSBd:bakcveo)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @GRAnimated and @MonsterDruide1)

___
*[`src/Layout/Compass.cpp` line 36 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3PH4GIDE6PY1JBKOYu:-O3Z57V0-7gACrC-s9qG:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c889a053522d60479e79e16f8cc531402dac9def/src/Layout/Compass.cpp#L36)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

https://decomp.me/scratch/FqBF8
I'm not sure where this inlined function should be placed though - either extract the string constant to a parameter and move it to a utility header, or keep it in like this and local to the `cpp`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-05 20:10 UTC, MonsterDruide1 requested changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: all files reviewed, 1 unresolved discussion (waiting on @Wexos)

___
*[`src/Layout/Compass.cpp` line 36 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3PH4GIDE6PY1JBKOYu:-O3Z9Rb-2rJXETL-YROp:b-gwjswt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c889a053522d60479e79e16f8cc531402dac9def/src/Layout/Compass.cpp#L36)):*
<details><summary><i>Previously, Wexos wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great! Remove this comment then.


<!-- Sent from Reviewable.io -->

2024-08-06 10:30 UTC, Wexos reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Layout/Compass.cpp` line 36 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139#-O3PH4GIDE6PY1JBKOYu:-O3bEO0V1eRjges_SRxF:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c889a053522d60479e79e16f8cc531402dac9def/src/Layout/Compass.cpp#L36)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Great! Remove this comment then.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-06 10:32 UTC, MonsterDruide1 approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Wexos)



<!-- Sent from Reviewable.io -->

2024-08-07 22:38 UTC, GRAnimated approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/139)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Wexos)



<!-- Sent from Reviewable.io -->

2024-08-07 22:45 UTC, merged