Player: Implement `PlayerJudgeLongFall`
MonsterDruide1/OdysseyDecomp pull request #168
Opened 2024-09-29 04:11 UTC by ShishuTheDragon

Judges whether Mario has fallen far enough that he will be staggered upon landing.

Note that this judge also checks that:
* Mario is not dead,
* Mario is not 2D,
* The “bind keeper” is not active, and
* Mario is not in a capture.

2024-09-29 04:28 UTC, ShishuTheDragon commented on src/Player/PlayerBindKeeper.h
> +class PlayerBindKeeper {
This is just a stub so that I can implement `PlayerJudgeLongFall`

2024-09-29 04:28 UTC, ShishuTheDragon commented on src/Player/PlayerBindKeeper.h
> +    al::HitSensor* mSecondHitSensor;
I’ve been investigating `PlayerBindKeeper` in a separate branch.

It has 2 hit sensors: the first belongs to the player and never changes; and the second changes during certain actions (examples: sitting on a bench, riding a jaxi).

Hence calling this field **_second_** hit sensor.

2024-09-29 09:13 UTC, MonsterDruide1 requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/168)* status: all files reviewed, 3 unresolved discussions (waiting on @ShishuTheDragon)

___
*[`src/Player/PlayerBindKeeper.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/168#-O7x2Krx04ySHkWDHUrh:-O7x2Krx04ySHkWDHUri:b-8afxf0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/140cf9b22224f7ad3663bf6e76b639bfd76f139f/src/Player/PlayerBindKeeper.h#L13)):*
> ```objc
> private:
>     char padding[8];
>     al::HitSensor* mSecondHitSensor;
> ```

Considering that this HitSensor is only `!= nullptr` when the player is "in a bind", maybe `mBindSensor` is more appropriate for a name?


<!-- Sent from Reviewable.io -->

2024-09-30 07:05 UTC, ShishuTheDragon reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/168)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerBindKeeper.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/168#-O7x2Krx04ySHkWDHUrh:-O80inhK4TxGEPcQ_ilF:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/140cf9b22224f7ad3663bf6e76b639bfd76f139f/src/Player/PlayerBindKeeper.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Considering that this HitSensor is only `!= nullptr` when the player is "in a bind", maybe `mBindSensor` is more appropriate for a name?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-30 23:54 UTC, MonsterDruide1 approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/168)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShishuTheDragon)



<!-- Sent from Reviewable.io -->

2024-09-30 23:55 UTC, merged