Addition of unfinished ``PlayerDamageKeeper``and new Macro for Nerve Functions
MonsterDruide1/OdysseyDecomp pull request #18
Opened 2024-01-22 21:03 UTC by Trippixyz

``PlayerDamageKeeper``:

- Adds 3 function declarations: ``activatePreventDamage``, ``dead`` and ``damage``.

``NerveSetupUtil``:

- New Macro to better define so called "Actions" (Nerve Functions) for both the definition and declaration.

2024-01-25 22:18 UTC, MonsterDruide1 requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/18)* status: all files reviewed, 1 unresolved discussion (waiting on @Trippixyz)

___
*[`lib/al/include/Library/Nerve/NerveSetupUtil.h` line 41 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/18#-Np1gbkl7xc2hvA1IbTx:-Np1gbkl7xc2hvA1IbTy:b-f9r8jl) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0f8645d794ad06f156beeaf67eda0540e4d6c1f1/lib/al/include/Library/Nerve/NerveSetupUtil.h#L41)):*
> ```objc
> #define NERVE_MAKE(Class, Action) Class##Nrv##Action Action;
> 
> #define NERVE_FUNC(Action) void exe##Action()
> ```

Sounds sensible to me that the devs had a macro like this, do you think we should put this as a discussion on the modding server again to see how others feel about moving the functions to a bunch of macros?


<!-- Sent from Reviewable.io -->

2024-01-27 11:13 UTC, Trippixyz reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/18)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Nerve/NerveSetupUtil.h` line 41 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/18#-Np1gbkl7xc2hvA1IbTx:-Np9ahByCl9bM6272Pj5:b-8nmjj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0f8645d794ad06f156beeaf67eda0540e4d6c1f1/lib/al/include/Library/Nerve/NerveSetupUtil.h#L41)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Sounds sensible to me that the devs had a macro like this, do you think we should put this as a discussion on the modding server again to see how others feel about moving the functions to a bunch of macros?
</blockquote></details>

Yes we should get some more opinion on this! I'll post this on the modding server.


<!-- Sent from Reviewable.io -->

2024-02-28 21:00 UTC, MonsterDruide1 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/18)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Trippixyz)

___
*[`.github/workflows/compile-check.yml` line 7 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/18#-NrlVzhEDzUVsulzAE4u:-NrlVzhEDzUVsulzAE4v:b-mpu8lt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/49602879835a3549012a0f33230a73ff38d2fbbb/.github/workflows/compile-check.yml#L7)):*
> ```YAML
>   compile_verify:
>     runs-on: ubuntu-latest
>     environment: PRs-allow-ExeFS
> ```

Please remove this again, should work with the normal workflows now - if you rebase your PR.
___
*[`lib/al/include/Library/Nerve/NerveSetupUtil.h` line 41 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/18#-Np1gbkl7xc2hvA1IbTx:-NrlW4kXCLXaDoZiZOxt:b-puo3f4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0f8645d794ad06f156beeaf67eda0540e4d6c1f1/lib/al/include/Library/Nerve/NerveSetupUtil.h#L41)):*
<details><summary><i>Previously, Trippixyz wrote…</i></summary><blockquote>

Yes we should get some more opinion on this! I'll post this on the modding server.
</blockquote></details>

I guess that's enough of a positive answer - no one seriously protested, so I see that as "accepted".


<!-- Sent from Reviewable.io -->

2024-05-25 09:56 UTC, MonsterDruide1 commented
Bumping this, you'd only need to remove the PR workflow stuff again and rebase to hopefully get everything sorted!

2025-02-09 12:50 UTC, MonsterDruide1 requested changes
> Reviewed 2 of 3 files at r1, 218 of 218 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/18)* status: all files reviewed, 1 unresolved discussion (waiting on @Trippixyz)

___
*[`src/Player/PlayerDamageKeeper.cpp` line 0 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/18#-OIekce2-gfFEUaDycgT:-OIekce3DpeGYpRH2p1Y:bobfjxt) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/3e7a25398e449ce39458b415e5dacb76e7ae0735/src/Player/PlayerDamageKeeper.cpp#L0)):*
Useless file - as there is no content, please remove it.


<!-- Sent from Reviewable.io -->

2025-02-09 13:23 UTC, Trippixyz reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/18)* status: 9 of 220 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerDamageKeeper.cpp` line  at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/18#-OIekce2-gfFEUaDycgT:-OIesM-a59SwiBrgn5m6:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/3e7a25398e449ce39458b415e5dacb76e7ae0735/src/Player/PlayerDamageKeeper.cpp#L)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless file - as there is no content, please remove it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-09 16:03 UTC, MonsterDruide1 approved these changes
> Reviewed 211 of 211 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/18)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Trippixyz)



<!-- Sent from Reviewable.io -->

2025-02-10 21:14 UTC, merged