[Draft] Player: Implement PlayerBindableSensorList
MonsterDruide1/OdysseyDecomp pull request #181
Opened 2024-10-20 09:14 UTC by ShishuTheDragon

Matching implementation of PlayerBindableSensorList.

It’s a **_draft_** PR because this implementation requires a few workarounds for bugs & non-matches in `sead`. I’d like to see if I can get these fixes merged into `sead` itself.

2025-06-28 09:31 UTC, LynxDev2 reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181)* status: all files reviewed, 2 unresolved discussions (waiting on @ShishuTheDragon)

___
*[`src/Player/PlayerBindableSensorList.cpp` line 7 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OTprxOG15wZmRzgdm4z:-OTprxOG15wZmRzgdm5-:b-o5lucx) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/12460f824d85d1baea0c49b8af8f8a35bef08579/src/Player/PlayerBindableSensorList.cpp#L7)):*
> ```cpp
> const s32 PoolSize = 24;
> 
> // Workaround until https://github.com/open-ead/sead/pull/207 is merged.
> ```

This `sead` PR has now been merged. Please rebase and remove this workaround
___
*[`src/Player/PlayerBindableSensorList.h` line 22 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OTppnor3-Ss5BwaYBuQ:-OTppnos8leEjFSR-6cO:b-vnx6a6) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/12460f824d85d1baea0c49b8af8f8a35bef08579/src/Player/PlayerBindableSensorList.h#L22)):*
> ```objc
>     u32 getType(u32 index) const;
> 
>     struct SensorInfo;
> ```

What's the reason you forward declare this here and have the `struct` body later instead of having the `struct` body inside the parent `class`? I would prefer it to be inside the class instead and that would also match what's done here: https://github.com/MonsterDruide1/OdysseyDecomp/blob/master/lib/al/Project/Bgm/BgmInfo.h#L38 (this should also probably be made `private` like that one since the struct is only used internally)


<!-- Sent from Reviewable.io -->

2025-07-03 08:15 UTC, ShishuTheDragon reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @LynxDev2)

___
*[`src/Player/PlayerBindableSensorList.h` line 22 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OTppnor3-Ss5BwaYBuQ:-OUEJ--d6jAQqJMsAHTB:bf60q8p) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/12460f824d85d1baea0c49b8af8f8a35bef08579/src/Player/PlayerBindableSensorList.h#L22)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

What's the reason you forward declare this here and have the `struct` body later instead of having the `struct` body inside the parent `class`? I would prefer it to be inside the class instead and that would also match what's done here: https://github.com/MonsterDruide1/OdysseyDecomp/blob/master/lib/al/Project/Bgm/BgmInfo.h#L38 (this should also probably be made `private` like that one since the struct is only used internally)
</blockquote></details>

I found that forward declaring made it tidier. I’ve pushed a change which shows it nested instead. It’s okay but it means that the `PlayerBindableSensorList` member variables are much further down.

See what you think
___
*[`src/Player/PlayerBindableSensorList.cpp` line 7 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OTprxOG15wZmRzgdm4z:-OUEHTmV9G8iVMXi2Bat:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/12460f824d85d1baea0c49b8af8f8a35bef08579/src/Player/PlayerBindableSensorList.cpp#L7)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

This `sead` PR has now been merged. Please rebase and remove this workaround
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-07-03 10:44 UTC, LynxDev2 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @ShishuTheDragon)

___
*[`src/Player/PlayerBindableSensorList.h` line 22 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OTppnor3-Ss5BwaYBuQ:-OUEsK0IB-rwTzygYRf5:b7w61fc) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/12460f824d85d1baea0c49b8af8f8a35bef08579/src/Player/PlayerBindableSensorList.h#L22)):*
<details><summary><i>Previously, ShishuTheDragon (Shishu the Dragon) wrote…</i></summary><blockquote>

I found that forward declaring made it tidier. I’ve pushed a change which shows it nested instead. It’s okay but it means that the `PlayerBindableSensorList` member variables are much further down.

See what you think
</blockquote></details>

I think this is a bit better, but with this new layout, the `static_assert` for the size of the `struct` should either be removed or moved down to right before the `class` ends for it to look nicer


<!-- Sent from Reviewable.io -->

2025-07-03 23:17 UTC, ShishuTheDragon reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @LynxDev2)

___
*[`src/Player/PlayerBindableSensorList.h` line 22 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OTppnor3-Ss5BwaYBuQ:-OUH_FzU-BdlWwxhvf66:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/12460f824d85d1baea0c49b8af8f8a35bef08579/src/Player/PlayerBindableSensorList.h#L22)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

I think this is a bit better, but with this new layout, the `static_assert` for the size of the `struct` should either be removed or moved down to right before the `class` ends for it to look nicer
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-07-03 23:23 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 4 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181)* status: all files reviewed, 7 unresolved discussions (waiting on @LynxDev2)

___
*[`src/Player/PlayerBindableSensorList.h` line 14 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUHaEaBACDqiEzQ0yyp:-OUHaEaBACDqiEzQ0yyq:bi47l48) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.h#L14)):*
> ```objc
> 
>     void clear();
>     void append(al::HitSensor* bindSensor, u32 type, f32 distance, s32 priority);
> ```

Where did you get these names from?
Distance is semi-understandable, but I think the formula in `collectBindableSensor` is the other way around:
`(sensorRadiusA + sensorRadiusB) - distanceBetweenSensors`



_Code quote:_
```objc
f32 distance, s32 priority
```
___
*[`src/Player/PlayerBindableSensorList.h` line 32 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUHYzBi6yuyuAlrWXBB:-OUHYzBi6yuyuAlrWXBC:undefined) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.h#L32)):*
> ```objc
> 
>     sead::PtrArray<struct SensorInfo> mActiveSensors;
>     sead::PtrArray<struct SensorInfo> mPool;
> ```





_Suggestion:_
```objc
    sead::PtrArray<SensorInfo> mActiveSensors;
    sead::PtrArray<SensorInfo> mPool;
```
___
*[`src/Player/PlayerBindableSensorList.cpp` line 5 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUHZqs7Ejm7KovH23Do:-OUHZqs7Ejm7KovH23Dp:undefined) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.cpp#L5)):*
> ```cpp
> #include <container/seadPtrArray.h>
> 
> const s32 PoolSize = 24;
> ```





_Suggestion:_
```cpp
constexpr s32 PoolSize = 24;
```
___
*[`src/Player/PlayerBindableSensorList.cpp` line 51 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUH_ude2m_68hHO4piD:-OUH_ude2m_68hHO4piE:undefined) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.cpp#L51)):*
> ```cpp
>     SensorInfo* item = mActiveSensors.at(found);
>     mPool.pushBack(item);
>     mActiveSensors.erase(found);
> ```





_Suggestion:_
```cpp
    s32 size = mActiveSensors.size();
    for (s32 i = 0; i < size; i++) {
        const SensorInfo* item = mActiveSensors[i];
        if (item->bindSensor == toRemove) {
            SensorInfo* item = mActiveSensors[i];
            mPool.pushBack(item);
            mActiveSensors.erase(i);
            return;
        }
    }
```
___
*[`src/Player/PlayerBindableSensorList.cpp` line 63 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUH_wTN4enXaV2ossVQ:-OUH_wTN4enXaV2ossVR:undefined) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.cpp#L63)):*
> ```cpp
> 
> al::HitSensor* PlayerBindableSensorList::get(u32 index) const {
>     return mActiveSensors.at(index)->bindSensor;
> ```





_Suggestion:_
```cpp
return mActiveSensors[index]->bindSensor;
```
___
*[`src/Player/PlayerBindableSensorList.cpp` line 67 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUH_yh70dWqTJpFaP4v:-OUH_yh70dWqTJpFaP4w:undefined) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.cpp#L67)):*
> ```cpp
> 
> u32 PlayerBindableSensorList::getType(u32 index) const {
>     return mActiveSensors.at(index)->type;
> ```





_Suggestion:_
```cpp
return mActiveSensors[index]->type;
```


<!-- Sent from Reviewable.io -->

2025-07-04 03:27 UTC, ShishuTheDragon reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @LynxDev2 and @MonsterDruide1)

___
*[`src/Player/PlayerBindableSensorList.h` line 14 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUHaEaBACDqiEzQ0yyp:-OUHcEl80EkPdENTuLvJ:b-dhzs49) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.h#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Where did you get these names from?
Distance is semi-understandable, but I think the formula in `collectBindableSensor` is the other way around:
`(sensorRadiusA + sensorRadiusB) - distanceBetweenSensors`
</blockquote></details>

Oh yes, `distance` actually measures closeness or amount of overlap. I think I remember getting confused because of `operator<`. I have renamed it to `overlap`, let me know if there are better suggestions.

As for `priority`: it’s always set to **4** and is not really used, except as the first comparison done in `operator<`. So “priority” is just my best guess.
___
*[`src/Player/PlayerBindableSensorList.h` line 32 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUHYzBi6yuyuAlrWXBB:-OUHp0dzDZp6qCTWA7Pr:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.h#L32)):*
> ```objc
> 
>     sead::PtrArray<struct SensorInfo> mActiveSensors;
>     sead::PtrArray<struct SensorInfo> mPool;
> ```

Done.
___
*[`src/Player/PlayerBindableSensorList.cpp` line 5 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUHZqs7Ejm7KovH23Do:-OUHolG49vXj6nnUY_ha:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.cpp#L5)):*
> ```cpp
> #include <container/seadPtrArray.h>
> 
> const s32 PoolSize = 24;
> ```

Done.
___
*[`src/Player/PlayerBindableSensorList.cpp` line 51 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUH_ude2m_68hHO4piD:-OUHprGW1xhgrsZLfbu9:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.cpp#L51)):*
> ```cpp
>     SensorInfo* item = mActiveSensors.at(found);
>     mPool.pushBack(item);
>     mActiveSensors.erase(found);
> ```

Done.
___
*[`src/Player/PlayerBindableSensorList.cpp` line 63 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUH_wTN4enXaV2ossVQ:-OUHoxQIC_RadCiQN7zB:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.cpp#L63)):*
> ```cpp
> 
> al::HitSensor* PlayerBindableSensorList::get(u32 index) const {
>     return mActiveSensors.at(index)->bindSensor;
> ```

Done.
___
*[`src/Player/PlayerBindableSensorList.cpp` line 67 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUH_yh70dWqTJpFaP4v:-OUHox6WBB4Lp3vCOaOy:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.cpp#L67)):*
> ```cpp
> 
> u32 PlayerBindableSensorList::getType(u32 index) const {
>     return mActiveSensors.at(index)->type;
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-07-04 10:28 UTC, MonsterDruide1 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ShishuTheDragon)

___
*[`src/Player/PlayerBindableSensorList.h` line 14 at r4](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/181#-OUHaEaBACDqiEzQ0yyp:-OUJyctM2VrIymfHQHni:b-37wna6) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/43f228711c19098f033954a486b8b4bd8e6aba9e/src/Player/PlayerBindableSensorList.h#L14)):*
<details><summary><i>Previously, ShishuTheDragon (Shishu the Dragon) wrote…</i></summary><blockquote>

Oh yes, `distance` actually measures closeness or amount of overlap. I think I remember getting confused because of `operator<`. I have renamed it to `overlap`, let me know if there are better suggestions.

As for `priority`: it’s always set to **4** and is not really used, except as the first comparison done in `operator<`. So “priority” is just my best guess.
</blockquote></details>

Alright, sounds good - `overlap` also makes more sense now.


<!-- Sent from Reviewable.io -->

2025-07-06 10:06 UTC, merged