Util: add several `rs` util headers
MonsterDruide1/OdysseyDecomp pull request #197
Opened 2024-11-20 10:07 UTC by tetraxile

2024-11-21 20:36 UTC, MonsterDruide1 requested changes
> Reviewed 23 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: 23 of 33 files reviewed, 7 unresolved discussions (waiting on @tetraxile)

___
*[`src/Layout/ShopLayoutInfo.h` line 0 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCEsjxb-QAiF8uXVXoN:-OCEsjxb-QAiF8uXVXoO:b-muoxx8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Layout/ShopLayoutInfo.h#L0)):*
Why is this file added? It does not add any value/information, and it's not actually needed to be included anywhere (types should be forward-declared).
___
*[`src/Util/BreakJudgeUtil.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFQy23EnoN3HMGcRCn:-OCFQy23EnoN3HMGcRCo:b-l9z44z) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/BreakJudgeUtil.h#L13)):*
> ```objc
> bool isMsgBreakByNormalAttack(const al::SensorMsg* sensorMsg);
> bool isMsgBreakCage(const al::SensorMsg* sensorMsg);
> bool isMsgBreakByExplosion(const al::SensorMsg* sensorMsg);
> ```

Where did you get those names from? They're unnamed (`sub_`) for me.



_Code quote:_
```objc
bool isMsgBreakByNormalAttack(const al::SensorMsg* sensorMsg);
bool isMsgBreakCage(const al::SensorMsg* sensorMsg);
bool isMsgBreakByExplosion(const al::SensorMsg* sensorMsg);
```
___
*[`src/Util/AmiiboUtil.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFM5N60brPSDLwUst0:-OCFM5N60brPSDLwUst1:b-wq09st) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/AmiiboUtil.h#L7)):*
> ```objc
> #include "Library/Base/StringUtil.h"
> 
> #include "Layout/ShopLayoutInfo.h"
> ```

Useless include
___
*[`src/Util/AreaUtil.h` line 22 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFPhE--9aFakOdF7-Q:-OCFPhE--9aFakOdF7-R:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/AreaUtil.h#L22)):*
> ```objc
> bool isInLowGravityArea(const al::LiveActor* actor);
> bool isInItemVanishArea(const al::LiveActor* actor);
> al::AreaObj* tryFindStageMapAreaAndGetPlayerPoint(sead::Vector3f* playerPoint,
> ```





_Suggestion:_
```objc
bool tryFindStageMapAreaAndGetPlayerPoint(sead::Vector3f* playerPoint,
```
___
*[`src/Util/AreaUtil.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFQOY14Rjn7pv6GFgh:-OCFQOY277b7xPcv0GeC:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/AreaUtil.h#L36)):*
> ```objc
> void calc2DAreaSnapPower(sead::Vector3f*, f32* snapPower, const al::AreaObj* area,
>                          const sead::Vector3f& trans);
> bool calc2DAreaDistanceGravity(sead::Vector3f*, const al::AreaObj* area,
> ```





_Suggestion:_
```objc
void calc2DAreaDistanceGravity(sead::Vector3f*, const al::AreaObj* area,
```
___
*[`src/System/GameDataUtil.h` line 163 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFJqVYCVfdT82QhGic:-OCFJqVYCVfdT82QhGid:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/System/GameDataUtil.h#L163)):*
> ```objc
> bool isStartKoopaCapture(const al::LiveActor* actor);
> void isAlreadyTalkPrevWorldInWorldWarp(const al::LiveActor* actor, s32);
> void isAlreadyTalkNextWorldInWorldWarp(const al::LiveActor* actor, s32);
> ```





_Suggestion:_
```objc
bool isAlreadyTalkPrevWorldInWorldWarp(const al::LiveActor* actor, s32);
bool isAlreadyTalkNextWorldInWorldWarp(const al::LiveActor* actor, s32);
```
___
*[`src/Util/ClothUtil.h` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFM8ar8QxN67KTtYPe:-OCFM8ar8QxN67KTtYPf:b-wq09st) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/ClothUtil.h#L6)):*
> ```objc
> #include <container/seadPtrArray.h>
> 
> #include "Layout/ShopLayoutInfo.h"
> ```

Useless include


<!-- Sent from Reviewable.io -->

2024-11-22 09:11 UTC, tetraxile reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: 19 of 33 files reviewed, 7 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Util/AmiiboUtil.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFM5N60brPSDLwUst0:-OCI5mGz0sE1C6cxjBW5:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/AmiiboUtil.h#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include
</blockquote></details>

done
___
*[`src/Util/BreakJudgeUtil.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFQy23EnoN3HMGcRCn:-OCI4z-w0P1aGgCZcYr_:b-7vxtx2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/BreakJudgeUtil.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Where did you get those names from? They're unnamed (`sub_`) for me.
</blockquote></details>

i made them up based on the other "break judge" function names as well as the particular `SensorMsg`s that these functions use. perhaps they should only go in the source file though? as they are indeed unnamed for me too
___
*[`src/Util/ClothUtil.h` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFM8ar8QxN67KTtYPe:-OCI6j1M0c2zsc3epXDh:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/ClothUtil.h#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include
</blockquote></details>

done
___
*[`src/Layout/ShopLayoutInfo.h` line  at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCEsjxb-QAiF8uXVXoN:-OCI5JfV4wltaYPgntn4:bapfww3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Layout/ShopLayoutInfo.h#L)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Why is this file added? It does not add any value/information, and it's not actually needed to be included anywhere (types should be forward-declared).
</blockquote></details>

right, i guess i had it as a `class ShopItem` with inner classes in which case it wouldn't just be a forward declaration if i were to do that at every instance at which it's needed. done
___
*[`src/Util/AreaUtil.h` line 22 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFPhE--9aFakOdF7-Q:-OCI5x3n67CevVVrqtYf:br97b4i) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/AreaUtil.h#L22)):*
> ```objc
> bool isInLowGravityArea(const al::LiveActor* actor);
> bool isInItemVanishArea(const al::LiveActor* actor);
> al::AreaObj* tryFindStageMapAreaAndGetPlayerPoint(sead::Vector3f* playerPoint,
> ```

done -- was confused by `al::tryFindAreaObj` returning `al::AreaObj*`.
___
*[`src/Util/AreaUtil.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFQOY14Rjn7pv6GFgh:-OCI4TzI8DeTa7_jYHx3:b-otbl3r) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/AreaUtil.h#L36)):*
> ```objc
> void calc2DAreaSnapPower(sead::Vector3f*, f32* snapPower, const al::AreaObj* area,
>                          const sead::Vector3f& trans);
> bool calc2DAreaDistanceGravity(sead::Vector3f*, const al::AreaObj* area,
> ```

i don't think so; when this is used in `In2DAreaMoveControl::calcGravityDir` it expects a `bool` to be returned, and you can see where the function is setting this return value at addresses `0x545364` and `0x545398`.
___
*[`src/System/GameDataUtil.h` line 163 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFJqVYCVfdT82QhGic:-OCI77yL3xtX5tbmkZWT:b-bsl8ac) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/System/GameDataUtil.h#L163)):*
> ```objc
> bool isStartKoopaCapture(const al::LiveActor* actor);
> void isAlreadyTalkPrevWorldInWorldWarp(const al::LiveActor* actor, s32);
> void isAlreadyTalkNextWorldInWorldWarp(const al::LiveActor* actor, s32);
> ```

done -- must've confused this with the corresponding setters or something.


<!-- Sent from Reviewable.io -->

2024-11-23 14:35 UTC, MonsterDruide1 requested changes
> Reviewed 9 of 33 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: all files reviewed, 9 unresolved discussions (waiting on @tetraxile)

___
*[`src/Util/AreaUtil.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFQOY14Rjn7pv6GFgh:-OCOQe3L6XNeBVRb52Dy:bvfuc2i) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/AreaUtil.h#L36)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

i don't think so; when this is used in `In2DAreaMoveControl::calcGravityDir` it expects a `bool` to be returned, and you can see where the function is setting this return value at addresses `0x545364` and `0x545398`.
</blockquote></details>

Oh true, IDA messed up for me and wanted it to return a `float`, which is obviously wrong, so the code handling a standard register return didn't even show up.
___
*[`src/Util/BreakJudgeUtil.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFQy23EnoN3HMGcRCn:-OCORKkTEsCuQma8xeAE:b60x0iz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/BreakJudgeUtil.h#L13)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

i made them up based on the other "break judge" function names as well as the particular `SensorMsg`s that these functions use. perhaps they should only go in the source file though? as they are indeed unnamed for me too
</blockquote></details>

Actually, thinking about it again, I don't think any of these functions really exist in a header. The bottom two are only "named" because they're thunks to other functions, because they only contain one function call, so maybe the name is actually propagated by IDA, and not really in the executable? The first three are not thunks/named because those contain a combination of multiple `isMsg` calls, so no name can be auto-generated there.
___
*[`src/Util/CameraUtil.h` line 26 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOG8Xj46g-EhIQkAI8:-OCOG8Xj46g-EhIQkAI9:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/CameraUtil.h#L26)):*
> ```objc
>                                            f32 distance, f32 angleY, f32 angleH);
> bool isPreCameraFollowOrParallel(const al::CameraStartInfo& cameraStartInfo);
> void initGetMoonCamera(const al::IUseCamera* user, const al::LiveActor* moon,
> ```





_Suggestion:_
```objc
al::CameraTicket* initGetMoonCamera(const al::IUseCamera* user, const al::LiveActor* moon,
```
___
*[`src/Util/CameraUtil.h` line 29 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOGBVC-VfOLEvMb8KI:-OCOGBVC-VfOLEvMb8KJ:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/CameraUtil.h#L29)):*
> ```objc
>                        const al::ActorInitInfo& actorInitInfo, const char* name, sead::Vector3f*,
>                        sead::Vector3f*, sead::Vector3f*, sead::LookAtCamera* lookAtCamera);
> void initWarpCheckpointCamera(const al::IUseCamera* user, const al::LiveActor* checkpoint,
> ```





_Suggestion:_
```objc
al::CameraTicket* initWarpCheckpointCamera(const al::IUseCamera* user, const al::LiveActor* checkpoint,
```
___
*[`src/Npc/AchievementHolder.cpp` line 79 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOPwbe599qAlVNXZlF:-OCOPwbf5tgSGboBA5V-:b-tp08ye) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Npc/AchievementHolder.cpp#L79)):*
> ```cpp
>         return 1;
>     if (al::isEqualString(*name, "Scenario_WorldAll"))
>         return rs::calcClearWorldNum(accessor.mData);
> ```

Weird, that's the "wrong function" being called so far. I don't really like adding `.mData` everywhere, seems useless, but ... no idea how it should be done otherwise.
___
*[`src/Util/AreaUtil.h` line 34 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOQw0-BFSwJZ4tEhW4:-OCOQw0-BFSwJZ4tEhW5:bce7qjn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/AreaUtil.h#L34)):*
> ```objc
>                        const sead::Vector3f& trans);
> void calc2DAreaSnapPower(sead::Vector3f*, f32* snapPower, const al::AreaObj* area,
>                          const sead::Vector3f& trans);
> ```

Unused return value, but following the pattern of `calc2DArea*` functions



_Suggestion:_
```objc
bool calc2DAreaSnapPower(sead::Vector3f*, f32* snapPower, const al::AreaObj* area,
                         const sead::Vector3f& trans);
```
___
*[`src/Util/AreaUtil.h` line 39 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOR16dDsi_pXxPRF3N:-OCOR16dDsi_pXxPRF3O:bce7qjn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/AreaUtil.h#L39)):*
> ```objc
> f32 get2DAreaSurfaceDistance(const al::AreaObj* area);
> void calc2DAreaSnapPowerSurfaceDistance(sead::Vector3f*, f32* snapPower, const al::AreaObj* area,
>                                         const sead::Vector3f& trans, f32 surfaceDistance);
> ```

Unused return value, but following the pattern of `calc2DArea*` functions



_Suggestion:_
```objc
bool calc2DAreaSnapPowerSurfaceDistance(sead::Vector3f*, f32* snapPower, const al::AreaObj* area,
                                        const sead::Vector3f& trans, f32 surfaceDistance);
```
___
*[`src/Util/ClothUtil.h` line 29 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOI8df0hzRkymPg-vO:-OCOI8df0hzRkymPg-vP:b-3ui9b0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/ClothUtil.h#L29)):*
> ```objc
> bool isHaveSticker(GameDataHolderAccessor accessor, const char* name);
> bool isHaveGift(GameDataHolderAccessor accessor, const char* name);
> sead::PtrArrayImpl* getClothList(GameDataHolderAccessor accessor);
> ```

... and put a comment next to its declaration saying that this is not the right type and should be adjusted if necessary.



_Suggestion:_
```objc
const sead::PtrArray<UnknownItemInfo>& getClothList(GameDataHolderAccessor accessor);
```
___
*[`src/Util/ClothUtil.h` line 35 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOMhnr261pqomVbPeT:-OCOMhnr261pqomVbPeU:bhdezg8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/ClothUtil.h#L35)):*
> ```objc
> s32 calcHaveClothNum(GameDataHolderAccessor accessor);
> void buyCloth(const al::IUseSceneObjHolder* user, const char* clothName);
> sead::PtrArrayImpl* getCapList(GameDataHolderAccessor accessor);
> ```

(same type)



_Suggestion:_
```objc
const sead::PtrArray<UnknownItemInfo>&  getCapList(GameDataHolderAccessor accessor);
```
___
*[`src/Util/ClothUtil.h` line 46 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOMkHP1Rm3VzsYYT1L:-OCOMkHP1Rm3VzsYYT1M:bhdezg8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/ClothUtil.h#L46)):*
> ```objc
> s32 calcHaveCapNum(GameDataHolderAccessor accessor);
> void buyCap(const al::IUseSceneObjHolder* user, const char* capName);
> sead::PtrArrayImpl* getGiftList(GameDataHolderAccessor accessor);
> ```

(same type)



_Suggestion:_
```objc
const sead::PtrArray<UnknownItemInfo>&  getGiftList(GameDataHolderAccessor accessor);
```
___
*[`src/Util/ClothUtil.h` line 51 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOMm_j2ZkZhrRZ_cqy:-OCOMm_j2ZkZhrRZ_cqz:bhdezg8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/ [...]

2024-11-24 01:30 UTC, tetraxile reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: 29 of 33 files reviewed, 9 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Util/AreaUtil.h` line 34 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOQw0-BFSwJZ4tEhW4:-OCQiV0vDGW81KEwa6PJ:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/AreaUtil.h#L34)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unused return value, but following the pattern of `calc2DArea*` functions
</blockquote></details>

done
___
*[`src/Util/AreaUtil.h` line 39 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOR16dDsi_pXxPRF3N:-OCQiV_v0iURYTvpfWk_:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/AreaUtil.h#L39)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unused return value, but following the pattern of `calc2DArea*` functions
</blockquote></details>

done
___
*[`src/Util/BreakJudgeUtil.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCFQy23EnoN3HMGcRCn:-OCQiYC972PuM5SvfiHD:b-q05o8b) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/fad1b2a4f9cef24e5649b278a40dc29a3d4cbf1a/src/Util/BreakJudgeUtil.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Actually, thinking about it again, I don't think any of these functions really exist in a header. The bottom two are only "named" because they're thunks to other functions, because they only contain one function call, so maybe the name is actually propagated by IDA, and not really in the executable? The first three are not thunks/named because those contain a combination of multiple `isMsg` calls, so no name can be auto-generated there.
</blockquote></details>

right, i'll just remove these then.
___
*[`src/Util/ClothUtil.h` line 29 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOI8df0hzRkymPg-vO:-OCQl0bpAg8riQOVek5I:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/ClothUtil.h#L29)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

... and put a comment next to its declaration saying that this is not the right type and should be adjusted if necessary.
</blockquote></details>

done
___
*[`src/Util/ClothUtil.h` line 35 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOMhnr261pqomVbPeT:-OCQl1dx9Sk3B40wUF0Q:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/ClothUtil.h#L35)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

(same type)
</blockquote></details>

done
___
*[`src/Util/ClothUtil.h` line 46 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOMkHP1Rm3VzsYYT1L:-OCQl2Gw3Mzi-idiZHVJ:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/ClothUtil.h#L46)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

(same type)
</blockquote></details>

done
___
*[`src/Util/ClothUtil.h` line 51 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOMm_j2ZkZhrRZ_cqy:-OCQl2of3KJEQ4EEsIW5:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/ClothUtil.h#L51)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

(same type)
</blockquote></details>

done
___
*[`src/Util/CameraUtil.h` line 26 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOG8Xj46g-EhIQkAI8:-OCQjKyCCOZsnE7mNEhp:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/CameraUtil.h#L26)):*
> ```objc
>                                            f32 distance, f32 angleY, f32 angleH);
> bool isPreCameraFollowOrParallel(const al::CameraStartInfo& cameraStartInfo);
> void initGetMoonCamera(const al::IUseCamera* user, const al::LiveActor* moon,
> ```

done
___
*[`src/Util/CameraUtil.h` line 29 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCOGBVC-VfOLEvMb8KI:-OCQjLgn4hNP0OddSx9c:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4785c804bb9ba89fdcf16b23d1ab0ea5d4131646/src/Util/CameraUtil.h#L29)):*
> ```objc
>                        const al::ActorInitInfo& actorInitInfo, const char* name, sead::Vector3f*,
>                        sead::Vector3f*, sead::Vector3f*, sead::LookAtCamera* lookAtCamera);
> void initWarpCheckpointCamera(const al::IUseCamera* user, const al::LiveActor* checkpoint,
> ```

done


<!-- Sent from Reviewable.io -->

2024-11-24 09:09 UTC, MonsterDruide1 requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: all files reviewed, 1 unresolved discussion (waiting on @tetraxile)

___
*[`src/Util/ClothUtil.h` line 24 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCSQbKgAWRxiN4nxkSR:-OCSQbKgAWRxiN4nxkSS:b-zc7wjm) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a1f99cea72315b8d9c790013b9254e06142e4df1/src/Util/ClothUtil.h#L24)):*
> ```objc
> };
> 
> struct ItemListInfo {
> ```

Are these names known/right, or just guessed?



_Code quote:_
```objc
struct ItemAmiiboInfo {
    s32 mCharacterId;
    s32 mNumberingId;
};

struct ItemListInfo {
```


<!-- Sent from Reviewable.io -->

2024-11-24 12:49 UTC, tetraxile reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Util/ClothUtil.h` line 24 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCSQbKgAWRxiN4nxkSR:-OCTCwI4EmY699HqEYsF:b9wjabt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a1f99cea72315b8d9c790013b9254e06142e4df1/src/Util/ClothUtil.h#L24)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Are these names known/right, or just guessed?
</blockquote></details>

i got it from `0x52ec50`, which is where those four PtrArrays are initialized. they come from `SystemData/ItemList.szs`


<!-- Sent from Reviewable.io -->

2024-11-24 21:01 UTC, MonsterDruide1 requested changes
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: all files reviewed, 1 unresolved discussion (waiting on @tetraxile)

___
*[`src/Util/ClothUtil.h` line 24 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCSQbKgAWRxiN4nxkSR:-OCUyUSs9EMoKXBr4W3c:b-fnujok) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a1f99cea72315b8d9c790013b9254e06142e4df1/src/Util/ClothUtil.h#L24)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

i got it from `0x52ec50`, which is where those four PtrArrays are initialized. they come from `SystemData/ItemList.szs`
</blockquote></details>

True, the structures look correct like this, but are we sure that these are their names in the executable? Or is it just guessed based on the names of yaml dicts/files?


<!-- Sent from Reviewable.io -->

2024-11-24 21:04 UTC, tetraxile reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Util/ClothUtil.h` line 24 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCSQbKgAWRxiN4nxkSR:-OCUz9qQ5YBxyE7cqzyT:blfjmnn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a1f99cea72315b8d9c790013b9254e06142e4df1/src/Util/ClothUtil.h#L24)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

True, the structures look correct like this, but are we sure that these are their names in the executable? Or is it just guessed based on the names of yaml dicts/files?
</blockquote></details>

you mean the names `ItemListInfo` and `ItemAmiiboInfo`? i did just make those up based on context yeah. but you were suggesting `UnknownItemInfo` so i thought this would be better


<!-- Sent from Reviewable.io -->

2024-11-24 22:17 UTC, tetraxile reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: 32 of 35 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Util/ClothUtil.h` line 24 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCSQbKgAWRxiN4nxkSR:-OCVCPYT4QzkIzNNqJFF:bmpjych) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a1f99cea72315b8d9c790013b9254e06142e4df1/src/Util/ClothUtil.h#L24)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

(see discussion in Discord, please move this somewhere:tm: more appropriate and implement the respective functions to cause compiler errors when one of the occurances is renamed)
</blockquote></details>

alright i've moved it to `GameDataHolder.h`. unsure if those getters (`GameDataHolder::getCapList` etc) are the best way of doing that but the only alternatives i see are making `GameDataHolder`'s members public, or making it a friend class within `rs`. but it is only four members so far so i think for this PR it's fine to just leave it like that until we figure out later whether there are enough external private member accesses to warrant an alternative solution


<!-- Sent from Reviewable.io -->

2024-11-24 22:59 UTC, MonsterDruide1 requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: all files reviewed, 1 unresolved discussion (waiting on @tetraxile)

___
*[`src/Util/ClothUtil.h` line 24 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCSQbKgAWRxiN4nxkSR:-OCVOIXU-Jq4hO9PKULm:b-mx5vkr) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a1f99cea72315b8d9c790013b9254e06142e4df1/src/Util/ClothUtil.h#L24)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

alright i've moved it to `GameDataHolder.h`. unsure if those getters (`GameDataHolder::getCapList` etc) are the best way of doing that but the only alternatives i see are making `GameDataHolder`'s members public, or making it a friend class within `rs`. but it is only four members so far so i think for this PR it's fine to just leave it like that until we figure out later whether there are enough external private member accesses to warrant an alternative solution
</blockquote></details>

Yes, header-defined getter sounds good! Only make sure that it's `const` :sweat_smile: 
___
*[`src/System/GameDataHolder.h` line 112 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCVOB1L5l4wjRCaaazD:-OCVOB1L5l4wjRCaaazE:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ad386aceb4b9bf5e6c6944af47e4b59176d3af12/src/System/GameDataHolder.h#L112)):*
> ```objc
>     const sead::PtrArray<ItemListInfo>& getGiftList() { return mItemGift; }
> 
>     const sead::PtrArray<ItemListInfo>& getStickerList() { return mItemSticker; }
> ```





_Suggestion:_
```objc
    const sead::PtrArray<ItemListInfo>& getClothList() const { return mItemCloth; }

    const sead::PtrArray<ItemListInfo>& getCapList() const { return mItemCap; }

    const sead::PtrArray<ItemListInfo>& getGiftList() const { return mItemGift; }

    const sead::PtrArray<ItemListInfo>& getStickerList() const { return mItemSticker; }
```


<!-- Sent from Reviewable.io -->

2024-11-24 23:04 UTC, tetraxile reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Util/ClothUtil.h` line 24 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCSQbKgAWRxiN4nxkSR:-OCVPbAi4X_drd2q5DQ_:bosmlf1) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a1f99cea72315b8d9c790013b9254e06142e4df1/src/Util/ClothUtil.h#L24)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Yes, header-defined getter sounds good! Only make sure that it's `const` :sweat_smile:
</blockquote></details>

right, done
___
*[`src/System/GameDataHolder.h` line 112 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197#-OCVOB1L5l4wjRCaaazD:-OCVPdjYDpDPqI1nfYbz:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ad386aceb4b9bf5e6c6944af47e4b59176d3af12/src/System/GameDataHolder.h#L112)):*
> ```objc
>     const sead::PtrArray<ItemListInfo>& getGiftList() { return mItemGift; }
> 
>     const sead::PtrArray<ItemListInfo>& getStickerList() { return mItemSticker; }
> ```

done


<!-- Sent from Reviewable.io -->

2024-11-24 23:06 UTC, MonsterDruide1 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/197)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tetraxile)



<!-- Sent from Reviewable.io -->

2024-11-25 11:00 UTC, merged