lots of AreaObj.* functions
MonsterDruide1/OdysseyDecomp pull request #23
Opened 2024-03-08 04:28 UTC by whaleymar

pasted PR comment from the other repo:

This covers
- Reversed `AreaObjDirector`'s methods and fixed some errors in its header
- `AreaObjFactory` header + reversed both methods
- Headers for `AreaObjMtxConnecter` and `AreaObjMtxConnecterHolder`
- 2 inlined functions in `Factory` to get AreaObj + AreaObjDirector stuff matching
- Headers for area objects used in the factory (includes `TrafficArea`, `CameraStartParam`, `SeBarrierArea`, `SePlayArea`, `ViewCtrlArea`, `BirdGatheringSpotArea`, `ExtForceArea`, `ForceRecoveryKidsArea`, `MoveArea2D`, `NpcForceMaterialCodeArea`, `RouteGuideArea`, and `StainArea`)
- `ProjectAreaFactory` header and a non-matching constructor

Things to sanity check:
- `AreaObjDirector::getAreaObjGroup` did not match when using the inlined `_getAreaObjGroup`. Instead, it only matches when I paste the exact same code into the public method. Inlining the binary search was necessary for several functions to match, but having 2 identical functions feels wrong.
- I don't know if I defined `BirdGatheringSpotArea::AreaClippingInfo` in the right spot

2024-03-08 04:35 UTC, whaleymar commented
I'll deal with the linting stuff later I'm going to bed

2024-03-08 13:57 UTC, MonsterDruide1 commented
Alright, I'll review when the linter is (mostly) fixed.

2024-03-08 22:53 UTC, MonsterDruide1 requested changes
> Reviewed 2 of 29 files at r1, 26 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23)* status: 28 of 29 files reviewed, 26 unresolved discussions (waiting on @whaleymar)

___
*[`lib/al/include/Library/Area/AreaInitInfo.h` line 6 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsUWj2g5iiV7pF1ZJL7:-NsUWj2g5iiV7pF1ZJL8:bjs8pto) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaInitInfo.h#L6)):*
> ```objc
> 
> namespace al {
> class PlacementInfo;
> ```

It has to be included either way (to be able to inherit from it), so this is useless.
___
*[`lib/al/include/Library/Area/AreaInitInfo.h` line 12 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsUWZeeDXNpNFEg4bQl:-NsUWZeeDXNpNFEg4bQm:b-suihvq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaInitInfo.h#L12)):*
> ```objc
> class AreaInitInfo : public PlacementInfo {
> public:
>     AreaInitInfo(){};
> ```

Defining it in the header means that the function is not generated in the binary. As this constructor does exist in the game, this seems wrong.
___
*[`lib/al/include/Library/Area/AreaObj.h` line 25 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsUXD2887fpK1LsxKt_:-NsUXD2887fpK1LsxKta:b-ea2xth) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaObj.h#L25)):*
> ```objc
>     virtual void init(const AreaInitInfo& initInfo);
>     virtual bool isInVolume(const sead::Vector3f& position) const;
>     virtual bool isInVolumeOffset(const sead::Vector3f&, f32 offset) const;
> ```

Naming this as `position` for consistency across the functions?



_Code quote:_
```objc
const sead::Vector3f&
```
___
*[`lib/al/include/Library/Area/AreaObjDirector.h` line 37 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsUXfU_8PqfAsCyInHL:-NsUXfU_8PqfAsCyInHM:b-qobtg1) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaObjDirector.h#L37)):*
> ```objc
>     u32 mAreaGroupCount = 0;
> 
>     AreaObjGroup* _getAreaObjGroup(const char* name) const {
> ```

I don't think this belongs in the header, but I'll do some experiments later.
___
*[`lib/al/include/Library/Area/AreaObjMtxConnecter.h` line 41 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsV6WXY7R3-lz5j5mZL:-NsV6WXY7R3-lz5j5mZM:bzc56up) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaObjMtxConnecter.h#L41)):*
> ```objc
> 
> private:
>     MtxConnector** mMtxConnectors;
> ```

Isn't this a `al::AreaObjMtxConnecter**`?
___
*[`lib/al/include/Library/Area/TrafficArea.h` line 17 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsV7SBSAlh8IJ1c_Vyk:-NsV7SBSAlh8IJ1c_Vyl:boahd6u) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/TrafficArea.h#L17)):*
> ```objc
>     bool mNpcFull = false;
>     bool mNpcUnavailable = false;
>     char mUnkChar = '\0';
> ```

Considering the above is `mNpcUnavailable`, this should probably be `bool mCarUnavailable`.
___
*[`lib/al/include/Library/Factory/Factory.h` line 35 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVA-QZDL0WwtL3_4Ee:-NsVA-QZDL0WwtL3_4Ef:b7rg9fv) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Factory/Factory.h#L35)):*
> ```objc
>     s32 getNumFactoryEntries() const { return mNumFactoryEntries; }
> 
>     s32 getEntryIndex(const char* entryName, T* creationPtr) const {
> ```

If that still matches, I would prefer to swap the two parameters to have `T*, const char*`. Other functions in this game have it that way around (`out, in1, in2, ...`).
___
*[`lib/al/include/Library/Play/Area/ViewCtrlArea.h` line 4 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsV98dSETHxuOMPn5mf:-NsV98dSETHxuOMPn5mg:b-hdxxi9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Play/Area/ViewCtrlArea.h#L4)):*
> ```objc
> 
> #include "Library/Area/AreaObj.h"
> #include "Library/Placement/PlacementId.h"
> ```

Do not include, but just declare as `class PlacementId;`
___
*[`lib/al/src/Library/Area/AreaObj.cpp` line 44 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVAUpMCL17bVVm6cJ3:-NsVAUpMCL17bVVm6cJ4:bzcv47x) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObj.cpp#L44)):*
> ```cpp
> 
>     mAreaShape->setBaseMtxPtr(&mMatrixTR);
>     sead::Vector3f scale({1.0, 1.0, 1.0});
> ```

`sead::Vector3f scale = {1.0, 1.0, 1.0};` for consistency with `= nullptr` from above
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 19 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVBLRbD7DlIuQgBRKu:-NsVBLRbD7DlIuQgBRKv:b154foi) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L19)):*
> ```cpp
>     mMtxConnecterHolder = new AreaObjMtxConnecterHolder(0x100);
>     s32 nFactoryEntries = mFactory->getNumFactoryEntries();
>     s32 areaGroupsSize = nFactoryEntries;
> ```

Is this double-copying required?
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 79 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVBwg36kj_DWmiRo_5:-NsVBwg36kj_DWmiRo_6:b-c54fjf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L79)):*
> ```cpp
> void AreaObjDirector::createAreaObjGroupBuffer() {
>     for (s32 i = 0; i < mFactory->getAreaGroupCount(); i++) {
>         AreaGroupInfo* addBuffer = mFactory->getAreaGroupInfo() + i;
> ```

Ugly pointer arithmetic.
Suggestion: `AreaGroupInfo& addBuffer = mFactory->getAreaGroupInfo()[i];`, if that matches.
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 108 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVCtxB3yqwyEED9A9s:-NsVCtxB3yqwyEED9A9t:ba08xai) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L108)):*
> ```cpp
> 
> void AreaObjDirector::placementAreaObj(const AreaInitInfo& initInfo) {
>     PlacementInfo pInfo(initInfo);
> ```

Should not be required, I think - just using `initInfo` everywhere should be fine, as it is the superclass
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 127 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVD7U67CpxvYhNo-KB:-NsVD7U67CpxvYhNo-KC:b-jeianp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L127)):*
> ```cpp
>         areaObj->init(initInfo2);
> 
>         AreaObjGroup* areaGroup = _getAreaObjGroup(pInfoName);
> ```

Maybe calling `getAreaObjGroup` instead, removing the need for `_getAreaObjGroup` in the first place?
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 135 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVDGeo88EgIQCBeaIT:-NsVDGepEIvDPPBxdLjB:byjlfh8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L135)):*
> ```cpp
> 
> AreaObjGroup* AreaObjDirector::getAreaObjGroup(const char* name) const {
>     // return _getAreaObjGroup(name); // doesn't match
> ```

( [...]

2024-03-09 03:33 UTC, whaleymar commented
*[`lib/al/src/Library/Area/AreaObjGroup.cpp` line 40 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVE64Q83Kl2SOBq8CW:-NsWG40225_-xKiPRyLr:b-yx2dbn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjGroup.cpp#L40)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Uhh, are you sure about this?
</blockquote></details>

we've been over this one before https://github.com/odyssey-modding/odyssey/pull/19#discussion_r1310355086 


<!-- Sent from Reviewable.io -->

2024-03-09 04:24 UTC, whaleymar reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23)* status: 28 of 29 files reviewed, 26 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Area/AreaInitInfo.h` line 6 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsUWj2g5iiV7pF1ZJL7:-NsWH5mXCC0_ilcShk1t:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaInitInfo.h#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

It has to be included either way (to be able to inherit from it), so this is useless.
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Area/AreaInitInfo.h` line 12 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsUWZeeDXNpNFEg4bQl:-NsWHUZn4KbMVaG1yVK6:byb1s8k) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaInitInfo.h#L12)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Defining it in the header means that the function is not generated in the binary. As this constructor does exist in the game, this seems wrong.
</blockquote></details>

idk what I was on
___
*[`lib/al/include/Library/Area/AreaObj.h` line 25 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsUXD2887fpK1LsxKt_:-NsWHfH07JR4Sw6Nn1V_:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaObj.h#L25)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Naming this as `position` for consistency across the functions?
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Area/AreaObjDirector.h` line 37 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsUXfU_8PqfAsCyInHL:-NsWOSXSDMtbF4ubejYX:b-20x040) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaObjDirector.h#L37)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I don't think this belongs in the header, but I'll do some experiments later.
</blockquote></details>

is gone
___
*[`lib/al/include/Library/Area/AreaObjMtxConnecter.h` line 41 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsV6WXY7R3-lz5j5mZL:-NsWJtPlBmmyE8OOoBsV:b2nih0v) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/AreaObjMtxConnecter.h#L41)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Isn't this a `al::AreaObjMtxConnecter**`?
</blockquote></details>

yup
___
*[`lib/al/include/Library/Area/TrafficArea.h` line 17 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsV7SBSAlh8IJ1c_Vyk:-NsWK2z4-IamcZzA1kTi:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Area/TrafficArea.h#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Considering the above is `mNpcUnavailable`, this should probably be `bool mCarUnavailable`.
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Factory/Factory.h` line 35 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVA-QZDL0WwtL3_4Ee:-NsWKxHV3bVbMX9ffGjd:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Factory/Factory.h#L35)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

If that still matches, I would prefer to swap the two parameters to have `T*, const char*`. Other functions in this game have it that way around (`out, in1, in2, ...`).
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Play/Area/ViewCtrlArea.h` line 4 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsV98dSETHxuOMPn5mf:-NsWL7GA-jaIxEuYb7g3:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/include/Library/Play/Area/ViewCtrlArea.h#L4)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Do not include, but just declare as `class PlacementId;`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Area/AreaObj.cpp` line 44 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVAUpMCL17bVVm6cJ3:-NsWLJe85wtsGEhCKSjn:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObj.cpp#L44)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`sead::Vector3f scale = {1.0, 1.0, 1.0};` for consistency with `= nullptr` from above
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 19 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVBLRbD7DlIuQgBRKu:-NsWMFe-ERveYWW3Dv_m:b-eylnis) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L19)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Is this double-copying required?
</blockquote></details>

nope idk why I did that
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 79 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVBwg36kj_DWmiRo_5:-NsWMmIvB8tF_Hemvk95:b-7h4u3n) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L79)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Ugly pointer arithmetic.
Suggestion: `AreaGroupInfo& addBuffer = mFactory->getAreaGroupInfo()[i];`, if that matches.
</blockquote></details>

works
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 108 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVCtxB3yqwyEED9A9s:-NsWNHMt7xNHm9Cibg23:bnm7gaq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L108)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should not be required, I think - just using `initInfo` everywhere should be fine, as it is the superclass
</blockquote></details>

doesn't match
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 127 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVD7U67CpxvYhNo-KB:-NsWNLrw79yYzHRlVur1:b8qrxkz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L127)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Maybe calling `getAreaObjGroup` instead, removing the need for `_getAreaObjGroup` in the first place?
</blockquote></details>

that worked i feel so dumb
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 135 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVDGeo88EgIQCBeaIT:-NsWOXqG7N8duaNN7_va:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L135)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

(see above)
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 152 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVDISJ-pNk4HqIcGxR:-NsWOYxT6jLs0zELcFvC:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e453 [...]

2024-03-12 11:27 UTC, MonsterDruide1 reviewed
> Reviewed 13 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23)* status: 26 of 29 files reviewed, 4 unresolved discussions

___
*[`lib/al/src/Library/Area/AreaObjGroup.cpp` line 10 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVDpdS-pVw1awbWNkh:-NsmPBdt1_swATQZh5J9:b-h9e77r) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjGroup.cpp#L10)):*
<details><summary><i>Previously, whaleymar (whaley) wrote…</i></summary><blockquote>

required.
</blockquote></details>

Alright, then just leave it like that.
___
*[`src/AreaObj/ExtForceArea.h` line 11 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVEXHNAmhzBkXlSk8P:-NsmPJL_6F9PNH7MRcud:bi60gbz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/src/AreaObj/ExtForceArea.h#L11)):*
<details><summary><i>Previously, whaleymar (whaley) wrote…</i></summary><blockquote>

const + references for vectors 2, 3, and 4
</blockquote></details>

Alright, I just noticed that pass-by-value seems wrong, without checking further. Thanks for confirming.


<!-- Sent from Reviewable.io -->

2024-03-12 16:44 UTC, MonsterDruide1 requested changes
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23)* status: 26 of 29 files reviewed, 3 unresolved discussions (waiting on @whaleymar)

___
*[`lib/al/src/Library/Area/AreaObjDirector.cpp` line 108 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVCtxB3yqwyEED9A9s:-NsnSnHw5HRoyhW1K3mH:b-desfee) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjDirector.cpp#L108)):*
<details><summary><i>Previously, whaleymar (whaley) wrote…</i></summary><blockquote>

doesn't match
</blockquote></details>

Hmm, weird, but I can't get a better match either.
___
*[`lib/al/src/Library/Area/AreaObjFactory.cpp` line 19 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVDYvv0l-rSmWty6Vd:-NsnTJEj0Sy4zk-wh_-J:b3sgc10) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjFactory.cpp#L19)):*
<details><summary><i>Previously, whaleymar (whaley) wrote…</i></summary><blockquote>

not very close to matching
</blockquote></details>

Missed the reference to `offset`, which should've been changed to `i`:
```cpp
s32 AreaObjFactory::tryFindAddBufferSize(const char* bufferName) const {
    if (mAreaGroupInfo == nullptr || mNumBuffers < 1)
        return 0;

    for (s32 i=0; i<mNumBuffers; i++) {
        if (isEqualString(bufferName, mAreaGroupInfo[i].name))
            return mAreaGroupInfo[i].size;
    }
    return 0;
}
```
This matches for me.
___
*[`lib/al/src/Library/Area/AreaObjGroup.cpp` line 40 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVE64Q83Kl2SOBq8CW:-NsnTTWX3ahw1_v37Wtw:bhqloi2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjGroup.cpp#L40)):*
<details><summary><i>Previously, whaleymar (whaley) wrote…</i></summary><blockquote>

we've been over this one before https://github.com/odyssey-modding/odyssey/pull/19#discussion_r1310355086
</blockquote></details>

I mean... is there something wrong about my logic here, or does increasing the `mCapacity` here mean that more objects can be added in `registerAreaObj` than actually allowed, so the game can write out-of-bounds?

If my line of thought is correct, we might want to keep track of stuff like that as a starting point for research, in case anyone might want to look into trying to find some ROP/ACE entry points - or just a collection to point out what N does wrong sometimes in general.
___
*[`src/Scene/ProjectAreaFactory.cpp` line 169 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/23#-NsVGHmx-W48-Wuvfyam:-NsnY-kbDQuHuvd7HXsj:blujpqf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/src/Scene/ProjectAreaFactory.cpp#L169)):*
<details><summary><i>Previously, whaleymar (whaley) wrote…</i></summary><blockquote>

is genning an empty function, not entirely sure why. Decompme is timing out I'll try again later
</blockquote></details>

Change the `CSV` to contain `C1` instead of `C2`, that will give you the function. It doesn't match and I'm not able to get a proper match though, but please do make that change and mark it as one of the mismatching states for a better tracking.


<!-- Sent from Reviewable.io -->

2025-03-31 18:13 UTC, whaleymar commented
*[`src/Scene/ProjectAreaFactory.cpp` line 169 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/23#-NsVGHmx-W48-Wuvfyam:-OMhP4KTD5I6f2fuptU-:bj0qcs0) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/src/Scene/ProjectAreaFactory.cpp#L169)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Change the `CSV` to contain `C1` instead of `C2`, that will give you the function. It doesn't match and I'm not able to get a proper match though, but please do make that change and mark it as one of the mismatching states for a better tracking.
</blockquote></details>

https://decomp.me/scratch/harn1


<!-- Sent from Reviewable.io -->

2025-03-31 18:15 UTC, whaleymar commented
*[`lib/al/src/Library/Area/AreaObjGroup.cpp` line 40 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/23#-NsVE64Q83Kl2SOBq8CW:-OMhPP3k5bV3-8gUvHLN:byw63jc) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjGroup.cpp#L40)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I mean... is there something wrong about my logic here, or does increasing the `mCapacity` here mean that more objects can be added in `registerAreaObj` than actually allowed, so the game can write out-of-bounds?

If my line of thought is correct, we might want to keep track of stuff like that as a starting point for research, in case anyone might want to look into trying to find some ROP/ACE entry points - or just a collection to point out what N does wrong sometimes in general.
</blockquote></details>

Your logic makes sense. I agree it's probably a mistake. I'll add a comment in the function body to point it out ig.


<!-- Sent from Reviewable.io -->

2025-03-31 18:43 UTC, whaleymar reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/23)* status: 24 of 29 files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/src/Library/Area/AreaObjFactory.cpp` line 19 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/23#-NsVDYvv0l-rSmWty6Vd:-OMhPKvX2YcDGbEAElsl:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/ba2d24f99acffe163b590ba2e45326def3d772da/lib/al/src/Library/Area/AreaObjFactory.cpp#L19)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Missed the reference to `offset`, which should've been changed to `i`:
```cpp
s32 AreaObjFactory::tryFindAddBufferSize(const char* bufferName) const {
    if (mAreaGroupInfo == nullptr || mNumBuffers < 1)
        return 0;

    for (s32 i=0; i<mNumBuffers; i++) {
        if (isEqualString(bufferName, mAreaGroupInfo[i].name))
            return mAreaGroupInfo[i].size;
    }
    return 0;
}
```
This matches for me.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-03-31 20:06 UTC, MonsterDruide1 commented
Please rebase this PR - it is heavily outdated by like half of the project's total commits, and conflicts on *7 files*. Sorry, that'll probably be quite painful...

2025-04-01 18:23 UTC, german77 commented
https://github.com/german77/OdysseyDecomp/tree/areaobj rebased to latest master to save you some pain

2025-04-04 23:02 UTC, closed without merging

2025-04-06 08:49 UTC, MonsterDruide1 commented
Supersed by #515