First PQ, worked on some Model, BGM and Actor stuff.
MonsterDruide1/OdysseyDecomp pull request #24
Opened 2024-03-19 20:01 UTC by vakhdmyt06

yes

2024-03-20 21:20 UTC, MonsterDruide1 requested changes
> Reviewed 2 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 2 of 17 files reviewed, 27 unresolved discussions (waiting on @vakhdmyt06)

___
*[`lib/al/include/Library/Action/ActorActionKeeper.h` line 29 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtScLgUEt65P5WMERZo:-NtScLgUEt65P5WMERZp:bmxm97c) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Action/ActorActionKeeper.h#L29)):*
> ```objc
>     void updatePrev();
> 
>     static ActorActionKeeper* tryCreate(LiveActor*, ActorResource const*, char const*, char const*);
> ```

Put this one at the top, above the constructor, with an empty line in-between. This is to make sure that people looking at the class see the "extra"-constructor-like function before everything else, in case for example a mod would want to make use of it.
___
*[`lib/al/include/Library/Action/ActorActionKeeper.h` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSconC2LMTSp1GYn9G:-NtSconC2LMTSp1GYn9H:b8ik0zx) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Action/ActorActionKeeper.h#L31)):*
> ```objc
>     static ActorActionKeeper* tryCreate(LiveActor*, ActorResource const*, char const*, char const*);
> 
>     LiveActor* mParentActor;
> ```

`private:` before this
___
*[`lib/al/include/Library/Action/ActorActionKeeper.h` line 33 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSdxUPBuxvK8x3qO3i:-NtSdxUPBuxvK8x3qO3j:brt6max) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Action/ActorActionKeeper.h#L33)):*
> ```objc
>     LiveActor* mParentActor;
>     const char* mActorName;
>     s8 mByteUnkn = 0;
> ```

`bool isActionRunning;`
___
*[`lib/al/include/Library/Action/ActorActionKeeper.h` line 44 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSe4aa2AG0TCjD0QqQ:-NtSe4aa2AG0TCjD0QqR:b-uktesy) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Action/ActorActionKeeper.h#L44)):*
> ```objc
> };
> 
> static_assert(sizeof(ActorActionKeeper) == 0x58, "");
> ```

Remove the empty message (`""`), just failing compilation without description is fine
___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSeDnO9U_sXRScZcJI:-NtSeDnO9U_sXRScZcJJ:b-w0w9t2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L11)):*
> ```objc
> class AudioSystemInfo {
> public:
>     AudioSystemInfo() = default;
> ```

Should not be `= default;` in the header, otherwise it will not generate a function
___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSeHtXCDA_ZFMDSbk3:-NtSeHtXCDA_ZFMDSbk4:b-6lhd2q) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L13)):*
> ```objc
>     AudioSystemInfo() = default;
> 
>     void* mVoid;
> ```

`private:`
___
*[`lib/al/include/Library/Bgm/BgmKeeper.h` line 14 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSegPFDD7tDJRxLI-i:-NtSegPFDD7tDJRxLI-j:b-uktrbp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Bgm/BgmKeeper.h#L14)):*
> ```objc
>     BgmKeeper(const AudioSystemInfo*, BgmDirector*, const char*);
> 
>     static BgmKeeper* create(const AudioSystemInfo*, BgmDirector*, const char*);
> ```

Move to the top
___
*[`lib/al/include/Library/Bgm/BgmKeeper.h` line 15 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSfbEC5WhaXcn9UUbU:-NtSfbEC5WhaXcn9UUbV:bvt1dtg) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Bgm/BgmKeeper.h#L15)):*
> ```objc
> 
>     static BgmKeeper* create(const AudioSystemInfo*, BgmDirector*, const char*);
>     sead::SafeString* getUserName() const;
> ```

I'm pretty sure that this should be `const char*`, as the first member of `BgmUserInfo` is set to the return value of `al::createStringIfInStack` (`7100A4812C`)
___
*[`lib/al/include/Library/Bgm/BgmLineFunction.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSfqIA1kuJji0RMXXf:-NtSfqIA1kuJji0RMXXg:b-uktrbp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Bgm/BgmLineFunction.h#L9)):*
> ```objc
> public:
>     BgmDataBase(const Resource*, const Resource*);
>     static BgmDataBase* create(const char*, const char*);
> ```

Move to the top
___
*[`lib/al/include/Library/LiveActor/LiveActor.h` line 130 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSfvgD8SVP7SEyk18z:-NtSfvgD8SVP7SEyk19-:btq9wzp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/LiveActor/LiveActor.h#L130)):*
> ```objc
>     void setName(const char* newName) { mActorName = newName; }
> 
>     const char* mActorName;
> ```

No, please don't - if you need write access, see the `setName` function above, and if you need read access, create a getter function in the header. The member variables itself should always remain private though.
___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 17 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSg99sB7HcVfaqtI-F:-NtSg99sB7HcVfaqtI-G:b-6lhd2q) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Model/ModelCtrl.h#L17)):*
> ```objc
>     void hide();
> 
>     sead::Matrix34f* mMatrix;
> ```

`private:`
___
*[`lib/al/include/Library/Resource/Resource.h` line 94 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSgEkKEP7TZqS0OS9U:-NtSgEkKEP7TZqS0OS9V:bof5qj8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Resource/Resource.h#L94)):*
> ```objc
>     InitResourceDataAction* mActionResData;
> 
> private:
> ```

No, please don't
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 10 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSgWdQ6jFyeueCY2sK:-NtSgWdQ6jFyeueCY2sL:bh2mnl8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Project/Action/ActionAnimCtrl.h#L10)):*
> ```objc
> 
> struct ActionAnimCtrlInfo {
>     ActionAnimCtrlInfo(int sklAnimSize);  // int = mSklAnimSize
> ```

Comment seems useless?
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSh0kdEkDCR8SqQx8U:-NtSh0kdEkDCR8SqQx8V:bz2cbr5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Project/Action/ActionAnimCtrl.h#L40)):*
> ```objc
> struct ActionAnimDataInfo {
>     sead::SafeString* mAnimName = nullptr;
>     float mFloat = -1.0;
> ```

If you are unsure what these are used for, please name them in a way that this is obvious. `_34` (for offset `0x34`) is the most common format for things like this in the repo at the moment.
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 45 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSgvI2CdV25hYqxgig:-NtSgvI2CdV25hYqxgih:b-7m69qo) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f6 [...]

2024-03-21 00:36 UTC, vakhdmyt06 commented
Done, i hope that's ok.

2024-03-25 18:47 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 2 of 23 files reviewed, 27 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Action/ActorActionKeeper.h` line 29 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtScLgUEt65P5WMERZo:-Ntfg7oh1sjv4p9N9NJF:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Action/ActorActionKeeper.h#L29)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Put this one at the top, above the constructor, with an empty line in-between. This is to make sure that people looking at the class see the "extra"-constructor-like function before everything else, in case for example a mod would want to make use of it.
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Action/ActorActionKeeper.h` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSconC2LMTSp1GYn9G:-Ntfg9kkDVTJ3p-fWAZb:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Action/ActorActionKeeper.h#L31)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`private:` before this
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Action/ActorActionKeeper.h` line 33 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSdxUPBuxvK8x3qO3i:-NtfgBN50lVzlTsW7ZPa:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Action/ActorActionKeeper.h#L33)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`bool isActionRunning;`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Action/ActorActionKeeper.h` line 44 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSe4aa2AG0TCjD0QqQ:-NtfgDg03zjX9DEV5DGz:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Action/ActorActionKeeper.h#L44)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Remove the empty message (`""`), just failing compilation without description is fine
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSeDnO9U_sXRScZcJI:-NtfgLje9735uxAAHbAX:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L11)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should not be `= default;` in the header, otherwise it will not generate a function
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSeHtXCDA_ZFMDSbk3:-NtfgOoj9FD3XbG0ZuHL:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`private:`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Bgm/BgmKeeper.h` line 14 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSegPFDD7tDJRxLI-i:-NtfgpMYBQzKVgGIxH3A:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Bgm/BgmKeeper.h#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Move to the top
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Bgm/BgmKeeper.h` line 15 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSfbEC5WhaXcn9UUbU:-NtflzQK7xMd8LLejQsx:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Bgm/BgmKeeper.h#L15)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I'm pretty sure that this should be `const char*`, as the first member of `BgmUserInfo` is set to the return value of `al::createStringIfInStack` (`7100A4812C`)
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Bgm/BgmLineFunction.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSfqIA1kuJji0RMXXf:-Ntfh5H05CRD4g7gFspg:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Bgm/BgmLineFunction.h#L9)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Move to the top
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 17 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSg99sB7HcVfaqtI-F:-Ntfh7_f2EKDNjY1g7Wj:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Model/ModelCtrl.h#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`private:`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Resource/Resource.h` line 94 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSgEkKEP7TZqS0OS9U:-NtfhG7fDFrGcDQjmN9m:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Resource/Resource.h#L94)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No, please don't
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 10 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSgWdQ6jFyeueCY2sK:-NtfhHliEO8KKkKdNL4J:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Project/Action/ActionAnimCtrl.h#L10)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Comment seems useless?
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSh0kdEkDCR8SqQx8U:-NtfhKNKEVZvn0NzNOmy:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Project/Action/ActionAnimCtrl.h#L40)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

If you are unsure what these are used for, please name them in a way that this is obvious. `_34` (for offset `0x34`) is the most common format for things like this in the repo at the moment.
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 45 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSgvI2CdV25hYqxgig:-NtfhQ3244BlV_xvd6h5:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Project/Action/ActionAnimCtrl.h#L45)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Missing `public:`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 47 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSgtgW9rx_HnFLjA5z:-NtfhRhC-pOCueaHKQj8:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Project/Action/ActionAnimCtrl.h#L47)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Move to the top
</blockquote></details>

Done.
___
*[`lib/al/in [...]

2024-03-25 21:59 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 17 files at r1, 8 of 16 files at r2, 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 12 of 23 files reviewed, 10 unresolved discussions (waiting on @vakhdmyt06)

___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 17 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZJXw8qDBBeZ9L0IK:-NtrZJXw8qDBBeZ9L0IL:b-b4gmnk) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L17)):*
> ```objc
> 
> private:
>     void* mVoid;
> ```

Can we figure out anything more about this type? `void*` is definitely wrong.
___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 19 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZqij9QAviOrSTON-:-NtrZqij9QAviOrSTON0:b-tj5r95) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L19)):*
> ```objc
>     void* mVoid;
>     AudioEffectDataBase* mAudioEffectDataBase;
>     AudioSoundArchiveInfo** mAudioSoundArchiveInfo;
> ```

Double-pointer here? Can you tell where you got all this type info from?
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 6 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-Ntr_I6f3fzvBCN0upt7:-Ntr_I6f3fzvBCN0upt8:bz7hmgd) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L6)):*
> ```objc
> class LiveActor;
> 
> static void startSklAnim(LiveActor*, const char*);
> ```

`static` is useless here, same for all functions below
___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 17 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSg99sB7HcVfaqtI-F:-Ntr_S3p6n_7rYnT2wkC:b-wrfr47) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Library/Model/ModelCtrl.h#L17)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not quite, but removing them is fine as well :sweat_smile: 
___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 3 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-Ntr_bF385tcxnm2s2YZ:-Ntr_bF385tcxnm2s2Y_:b-wq09st) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Model/ModelCtrl.h#L3)):*
> ```objc
> #pragma once
> 
> #include <math/seadMatrix.h>
> ```

Useless include
___
*[`lib/al/include/Library/Nerve/NerveExecutor.h` line 5 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-Ntr_hzFAXLfHc_gblR_:-Ntr_hzFAXLfHc_gblRa:b-wq09st) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Nerve/NerveExecutor.h#L5)):*
> ```objc
> #include <basis/seadTypes.h>
> 
> #include "Library/Action/ActorActionKeeper.h"
> ```

Useless include
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSh0kdEkDCR8SqQx8U:-Ntra1ky37GxiDLHgk1E:b5z9077) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Project/Action/ActionAnimCtrl.h#L40)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You removed the others? Not too great here, as a partial `struct` might mean that somebody tries to use it in this incomplete form. Please add at least some placeholders that will pad it to the right size.
___
*[`lib/al/include/Project/Action/ActionEffectCtrl.h` line 28 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtraZUx45fJ_GKbJZJA:-NtraZUy8WyHFNEBn9Ti:b-i3venf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Project/Action/ActionEffectCtrl.h#L28)):*
> ```objc
>     ActionEffectCtrlInfo mEffectStack;
> };
> }  // namespace al
> ```

Missing newline
___
*[`lib/al/include/Project/Action/ActionFlagCtrl.h` line 30 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-Ntraf5o2w3ld9rY4Omz:-Ntraf5o2w3ld9rY4On-:b-y6fsv0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Project/Action/ActionFlagCtrl.h#L30)):*
> ```objc
>     bool isFlagValidOn(int, bool);
>     bool isFlagValidOff(int, bool);
>     char* findFlagInfo(const char*);
> ```

`const char*`
___
*[`lib/al/include/Project/Action/ActionFunction.h` line 5 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtraiW-7lBNkQUH6cEO:-NtraiW-7lBNkQUH6cEP:bjdld49) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Project/Action/ActionFunction.h#L5)):*
> ```objc
> #include <prim/seadSafeString.h>
> 
> #include "Project/Action/ActionAnimCtrl.h"
> ```

Replace include with declaration
___
*[`lib/al/src/Project/Bgm/BgmInfo.cpp` line 5 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSj1pRA8d4gGyMxqp8:-NtrbsgU8W8I0RPuEj8X:ba8kaju) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/src/Project/Bgm/BgmInfo.cpp#L5)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

MathCalcCommon still useless?


<!-- Sent from Reviewable.io -->

2024-03-26 10:49 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 12 of 23 files reviewed, 10 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 17 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZJXw8qDBBeZ9L0IK:-NtuM5dI6wflhZM_To9d:b-rmp1i7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Can we figure out anything more about this type? `void*` is definitely wrong.
</blockquote></details>

i tried my best, but i cant find it being mentioned anywhere.
___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 19 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZqij9QAviOrSTON-:-NtuMG5H3O0yrvEorGLn:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L19)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Double-pointer here? Can you tell where you got all this type info from?
</blockquote></details>

Done.
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 6 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-Ntr_I6f3fzvBCN0upt7:-NtuMHyw4jrEDUccyfNV:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`static` is useless here, same for all functions below
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 3 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-Ntr_bF385tcxnm2s2YZ:-NtuMIRd4joiBCmYj5nU:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Model/ModelCtrl.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Nerve/NerveExecutor.h` line 5 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-Ntr_hzFAXLfHc_gblR_:-NtuMK7u-8RESF3PvrJP:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Nerve/NerveExecutor.h#L5)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-26 10:53 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 10 files at r3, 4 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 16 of 23 files reviewed, 4 unresolved discussions (waiting on @vakhdmyt06)

___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 19 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZqij9QAviOrSTON-:-NtuNoTz0Pmc_ykhE2Pb:b-kcvij7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L19)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean, I'm not sure about it, just looks wrong. Where did you get this info, maybe I can try verifying these?


<!-- Sent from Reviewable.io -->

2024-03-26 10:54 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 16 of 23 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Project/Action/ActionEffectCtrl.h` line 28 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtraZUx45fJ_GKbJZJA:-NtuNF2S2j8jAHHMapiW:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Project/Action/ActionEffectCtrl.h#L28)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Missing newline
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionFlagCtrl.h` line 30 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-Ntraf5o2w3ld9rY4Omz:-NtuNFekEveeOg6IQWNF:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Project/Action/ActionFlagCtrl.h#L30)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`const char*`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionFunction.h` line 5 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtraiW-7lBNkQUH6cEO:-NtuNGaXEtNddfo7-EDW:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Project/Action/ActionFunction.h#L5)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Replace include with declaration
</blockquote></details>

Done.
___
*[`lib/al/src/Project/Bgm/BgmInfo.cpp` line 5 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSj1pRA8d4gGyMxqp8:-NtuOF2tDkSpyYZhrSjS:bv6ry5x) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/src/Project/Bgm/BgmInfo.cpp#L5)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

MathCalcCommon still useless?
</blockquote></details>

I will include <math.h> instead then. i am using expf2(), after all


<!-- Sent from Reviewable.io -->

2024-03-26 10:55 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 16 of 23 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 19 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZqij9QAviOrSTON-:-NtuOd1i9R-DJq0GAF_c:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L19)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I mean, I'm not sure about it, just looks wrong. Where did you get this info, maybe I can try verifying these?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-26 10:56 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 16 of 23 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 19 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZqij9QAviOrSTON-:-NtuOg-z3XfV4QCvSa-8:b-a7w404) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L19)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i mean, it should be one star


<!-- Sent from Reviewable.io -->

2024-03-26 10:57 UTC, MonsterDruide1 requested changes
> Reviewed 3 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 19 of 23 files reviewed, 4 unresolved discussions (waiting on @vakhdmyt06)

___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 19 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZqij9QAviOrSTON-:-NtuP1Ut9IsrsQFXz7Dz:bdskoif) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L19)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

i mean, it should be one star
</blockquote></details>

Okay, but I still want to look at the others, maybe I can figure out the first member, it would help if you gave me some "starting offset" of where I can look into.


<!-- Sent from Reviewable.io -->

2024-03-26 12:07 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 17 of 23 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 19 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZqij9QAviOrSTON-:-NtudsxeB8R6dsyU0dOp:b-qds7v7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L19)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Okay, but I still want to look at the others, maybe I can figure out the first member, it would help if you gave me some "starting offset" of where I can look into.
</blockquote></details>

It is nulled in AudioSystemInfo constructor, but i coulldnt find more references than that.
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtSh0kdEkDCR8SqQx8U:-Ntue3eN-0xZZvTrKBhb:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/aa4f631852e2b555253047adab4e04402e042fb0/lib/al/include/Project/Action/ActionAnimCtrl.h#L40)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

You removed the others? Not too great here, as a partial `struct` might mean that somebody tries to use it in this incomplete form. Please add at least some placeholders that will pad it to the right size.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-26 12:09 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 17 of 23 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 19 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZqij9QAviOrSTON-:-NtueV9Y4EHXkmF-6HSw:b-mtiadu) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L19)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

It is nulled in AudioSystemInfo constructor, but i coulldnt find more references than that.
</blockquote></details>

nvm...


<!-- Sent from Reviewable.io -->

2024-03-26 12:32 UTC, MonsterDruide1 reviewed
> Reviewed 1 of 8 files at r4, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: 22 of 23 files reviewed, all discussions resolved

___
*[`lib/al/include/Library/Audio/System/AudioSystemInfo.h` line 19 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-NtrZqij9QAviOrSTON-:-NtujZH53YvVXs_PCtA5:b-48r9ji) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b99a47a906b1d550da2d94654cf632f419ee91b0/lib/al/include/Library/Audio/System/AudioSystemInfo.h#L19)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

nvm...
</blockquote></details>

Okay, I'll just trust you on these types, I can't do too much research to verify them at the moment.


<!-- Sent from Reviewable.io -->

2024-03-26 12:33 UTC, MonsterDruide1 approved these changes
> Reviewed 1 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @vakhdmyt06)



<!-- Sent from Reviewable.io -->

2024-03-26 12:34 UTC, MonsterDruide1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
Can you squash the commits into a single one? That's the last step before merging!

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-:-NtukCjSB1Ewz8DwKhkR:bu4h4x7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @vakhdmyt06)



<!-- Sent from Reviewable.io -->

2024-03-26 14:36 UTC, vakhdmyt06 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24#-:-NtvBGoa5C-wTgU1lr3f:bnfp4nl)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @MonsterDruide1)



<!-- Sent from Reviewable.io -->

2024-03-26 16:49 UTC, vakhdmyt06 reviewed
done

2024-03-26 16:50 UTC, vakhdmyt06 reviewed
> Reviewed 3 of 17 files at r1, 6 of 16 files at r2, 2 of 10 files at r3, 7 of 8 files at r4, 4 of 4 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @vakhdmyt06)



<!-- Sent from Reviewable.io -->

2024-03-26 16:54 UTC, MonsterDruide1 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/24)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @vakhdmyt06)



<!-- Sent from Reviewable.io -->

2024-03-26 16:54 UTC, merged