Progress on ActorActionkeeper, AnimPlayer* and ActorAnimFunction
MonsterDruide1/OdysseyDecomp pull request #25
Opened 2024-04-03 21:52 UTC by vakhdmyt06

just what it says. my second ever pr

2024-04-04 22:40 UTC, tetraxile reviewed
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: all files reviewed, 23 unresolved discussions (waiting on @vakhdmyt06)

___
*[`lib/al/include/Library/Bgm/BgmFunction.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf4taG0jFsakmwlFVA:-Nuf4taG0jFsakmwlFVB:b-ry4obv) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Bgm/BgmFunction.h#L9)):*
> ```objc
> }  // namespace al
> 
> struct alBgmFunction {
> ```

this shouldn't be in the `al` namespace. there could be other ones somewhere considering that you didn't create this one
___
*[`lib/al/include/Library/Execute/ExecuteTableHolderUpdate.h` line 49 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf5-C69k2RHJXChI9l:-Nuf5-C69k2RHJXChI9m:b-2whqku) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Execute/ExecuteTableHolderUpdate.h#L49)):*
> ```objc
> };
> 
> struct alActorSystemFunction {
> ```

same as `alBgmFunction`
___
*[`lib/al/include/Library/Execute/ExecuteTableHolderUpdate.h` line 50 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf4Pxr4frM8Se3fm8w:-Nuf4Pxr4frM8Se3fm8x:bleendz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Execute/ExecuteTableHolderUpdate.h#L50)):*
> ```objc
> 
> struct alActorSystemFunction {
>     static void addToExecutorMovemenet(LiveActor*);
> ```

`Movemenet` -> `Movement`
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 49 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf5sJX-ldYa2BuXuPZ:-Nuf5sJX-ldYa2BuXuP_:b-tpq505) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L49)):*
> ```objc
> 
> void setAllAnimFrame(LiveActor*, f32);
> void seetAllAnimFrameRate(LiveActor* f32);
> ```

`seet` -> `set`
___
*[`lib/al/include/Library/Model/ModelKeeper.h` line 32 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NufG30Z-M8cTrSB7dK6:-NufG30Z-M8cTrSB7dK7:b7ngvu5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Model/ModelKeeper.h#L32)):*
> ```objc
> 
> private:
>     const char* mName;                 // 8
> ```

remove these offset comments
___
*[`lib/al/include/Library/Resource/Resource.h` line 87 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf6nGC3ebS4WEhRVcK:-Nuf6nGC3ebS4WEhRVcL:bydjzhq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Resource/Resource.h#L87)):*
> ```objc
>     void initResourceData(char const*, bool);
> 
>     bool getHasAnimData() const { return mHasAnimData; }
> ```

perhaps nitpicky but because this is a bool i would call the function just `hasAnimData`. others might disagree though
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 23 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf7EPA4HW_-Z29xMuy:-Nuf7EPA4HW_-Z29xMuz:b-1biai3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Se/Info/SeAudioInfo.h#L23)):*
> ```objc
> 
>     const char* mName;
>     bool isPartsUser = false;
> ```

`isPartsUser` -> `mIsPartsUser`
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 24 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf8nuPDnOsdkwL1cow:-Nuf8nuPDnOsdkwL1cox:b-vf5vdn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Se/Info/SeAudioInfo.h#L24)):*
> ```objc
>     const char* mName;
>     bool isPartsUser = false;
>     sead::PtrArrayImpl* mPartsUserNameList;  // PtrArray<T> missing type
> ```

appears to be `PtrArray<char*>` based on `SeUserInfo::createInfo`
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf7B2z41RM4c10zAHo:-Nuf7B2z41RM4c10zAHp:b-o3q6r0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Se/Info/SeAudioInfo.h#L25)):*
> ```objc
>     bool isPartsUser = false;
>     sead::PtrArrayImpl* mPartsUserNameList;  // PtrArray<T> missing type
>     AudioInfoListWithParts* mErmitterInfoList;
> ```

`Ermitter` -> `Emitter`
___
*[`lib/al/include/Project/Action/ActionAnimCtrl.h` line 46 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf9CVbCMqGjeDaCic8:-Nuf9CVbCMqGjeDaCic9:b-8gwnaf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionAnimCtrl.h#L46)):*
> ```objc
>     LiveActor* mParentActor;
>     const char* mPlayingAnimName = nullptr;
>     s32 mInfoSize = 0;
> ```

minor but i would prefer `mInfoCount` because it's not the size of the `Info`, but rather the number of them
___
*[`lib/al/include/Project/Action/ActionEffectCtrl.h` line 26 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf9WJP1omvlvnV2rCv:-Nuf9WJP1omvlvnV2rCw:b-xr8axo) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionEffectCtrl.h#L26)):*
> ```objc
> private:
>     EffectKeeper* mEffectKeeper = nullptr;
>     s32 mInfoSize = 0;
> ```

same as above, `mInfoCount`
___
*[`lib/al/include/Project/Action/ActionFlagCtrl.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf9ufIEDVHBRrd2-Lu:-Nuf9ufIEDVHBRrd2-Lv:b-sobnd7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionFlagCtrl.h#L37)):*
> ```objc
>     LiveActor* mParentActor;
>     const char* mName = nullptr;
>     HitSensorKeeper* mHitSensor = nullptr;
> ```

maybe change name to `mHitSensorKeeper` because it isn't just a HitSensor
___
*[`lib/al/include/Project/Action/ActionFlagCtrl.h` line 38 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf9pG3-5NHLrgZfixH:-Nuf9pG3-5NHLrgZfixI:b-xr8axo) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionFlagCtrl.h#L38)):*
> ```objc
>     const char* mName = nullptr;
>     HitSensorKeeper* mHitSensor = nullptr;
>     s32 mInfoSize = 0;
> ```

same as above, `mInfoCount`
___
*[`lib/al/include/Project/Action/ActionScreenEffectCtrl.h` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NufABgyEX_MWg2OGK2u:-NufABgyEX_MWg2OGK2v:b-xr8axo) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionScreenEffectCtrl.h#L25)):*
> ```objc
>     LiveActor* mParentActor;
>     const char* mLastEffectName = nullptr;
>     s32 mInfoSize = 0;
> ```

same as above, `mInfoCount`
___
*[`lib/al/include/Project/Action/ActionSeCtrl.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NufALEP0cCKT80yfdb3:-NufALEP0cCKT80yfdb4:bl37bqr) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionSeCtrl.h#L12)):*
> ```objc
>     static ActionSeCtrl* tryCreate(AudioKeeper*);
> 
>     ActionSeCtrl(SeKeeper*, SeUserInfo*);
> ```

`SeUserInfo*` -> `const SeUserInfo*`
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 17 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NufDDnNDUdVzbMl6UFv:-NufDDnO8vDeADNoVJZq:b-2uj [...]

2024-04-05 04:42 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 25 of 32 files reviewed, 22 unresolved discussions (waiting on @tetraxile)

___
*[`lib/al/include/Library/Bgm/BgmFunction.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf4taG0jFsakmwlFVA:-NugSC3u7FBOCPtphjz6:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Bgm/BgmFunction.h#L9)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

this shouldn't be in the `al` namespace. there could be other ones somewhere considering that you didn't create this one
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Execute/ExecuteTableHolderUpdate.h` line 49 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf5-C69k2RHJXChI9l:-NugSAYi6diOVW_VI7mv:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Execute/ExecuteTableHolderUpdate.h#L49)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

same as `alBgmFunction`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Execute/ExecuteTableHolderUpdate.h` line 50 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf4Pxr4frM8Se3fm8w:-NugSBAzEmi2xaL_en_9:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Execute/ExecuteTableHolderUpdate.h#L50)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`Movemenet` -> `Movement`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 49 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf5sJX-ldYa2BuXuPZ:-NugS9Id1HpoBZlzQyHl:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L49)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`seet` -> `set`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Model/ModelKeeper.h` line 32 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NufG30Z-M8cTrSB7dK6:-NugSG0c-rVCUan8C8H6:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Model/ModelKeeper.h#L32)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

remove these offset comments
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Resource/Resource.h` line 87 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf6nGC3ebS4WEhRVcK:-NugSYCa7PlVWAwCsCfD:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Resource/Resource.h#L87)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

perhaps nitpicky but because this is a bool i would call the function just `hasAnimData`. others might disagree though
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 23 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf7EPA4HW_-Z29xMuy:-NugSZ8_CKxrpbF9zm1G:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Se/Info/SeAudioInfo.h#L23)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`isPartsUser` -> `mIsPartsUser`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 24 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf8nuPDnOsdkwL1cow:-NugSkQ5-ju42WOSpfMo:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Se/Info/SeAudioInfo.h#L24)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

appears to be `PtrArray<char*>` based on `SeUserInfo::createInfo`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf7B2z41RM4c10zAHo:-NugSksDD0S5bJ5CEBN_:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Se/Info/SeAudioInfo.h#L25)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`Ermitter` -> `Emitter`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionEffectCtrl.h` line 26 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf9WJP1omvlvnV2rCv:-NugSyLtAPXyT--3JS6l:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionEffectCtrl.h#L26)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

same as above, `mInfoCount`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionFlagCtrl.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf9ufIEDVHBRrd2-Lu:-NugT6Et5zQD0ibh9lQY:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionFlagCtrl.h#L37)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

maybe change name to `mHitSensorKeeper` because it isn't just a HitSensor
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionFlagCtrl.h` line 38 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf9pG3-5NHLrgZfixH:-NugT72t5mGTCAVI7p_h:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionFlagCtrl.h#L38)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

same as above, `mInfoCount`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionScreenEffectCtrl.h` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NufABgyEX_MWg2OGK2u:-NugTBNv5lNvJLtASSWg:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionScreenEffectCtrl.h#L25)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

same as above, `mInfoCount`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionSeCtrl.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NufALEP0cCKT80yfdb3:-NugTGFOBRn9k6SI1zF4:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Project/Action/ActionSeCtrl.h#L12)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`SeUserInfo*` -> `const SeUserInfo*`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 17 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NufDDnNDUdVzbMl6UFv:-NugTqtY2g_WloKlsD0F:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L17)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

would be nice if this was changed from `string` to `animName`, for many of the functions in this file. `string` isn't very descriptive
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 20 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NufCDs04j6vRYUkkC6V:-NugUpfk6avHKlMQcWSs:b-896fix) ([raw file](https://github.c [...]

2024-04-05 20:22 UTC, tetraxile reviewed
> Reviewed 4 of 7 files at r2, 7 of 11 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: all files reviewed, 4 unresolved discussions (waiting on @vakhdmyt06)

___
*[`lib/al/include/Library/Resource/Resource.h` line 87 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf6nGC3ebS4WEhRVcK:-Nujt7Om6SWxu7Bj_VyQ:bfn8qmw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Resource/Resource.h#L87)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

are you sure?
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 11 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NujrpCD51Ja0wgJ31cx:-NujrpCD51Ja0wgJ31cy:b-o21oub) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d7b917f5bdb44cf18c736971a56d54bb7ce344ad/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L11)):*
> ```cpp
> 
> namespace al {
> void startAction(LiveActor* actor, const char* string) {
> ```

`string` -> `name` like you did in `ActorActionKeeper::startAction`
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 22 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NujrzPT9oBjy-XBVNUy:-NujrzPT9oBjy-XBVNUz:b4vlv1a) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d7b917f5bdb44cf18c736971a56d54bb7ce344ad/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L22)):*
> ```cpp
>     }
> }
> bool tryStartAction(LiveActor* actor, const char* string) {
> ```

change `string` name as above
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 93 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuju4Km9yOBS0qhjYRE:-Nuju4Km9yOBS0qhjYRF:b-fd18xg) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d7b917f5bdb44cf18c736971a56d54bb7ce344ad/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L93)):*
> ```cpp
> }
> void setSklAnimFrameRate(LiveActor* actor, f32 frame, s32 index) {
>     getSkl(actor)->setSklAnimFrameRate(index, frame);
> ```

this should be `frameRate`, not `frame`


<!-- Sent from Reviewable.io -->

2024-04-06 18:16 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 23 of 39 files reviewed, 4 unresolved discussions (waiting on @tetraxile)

___
*[`lib/al/include/Library/Resource/Resource.h` line 87 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf6nGC3ebS4WEhRVcK:-NunGtRu50ixFeoN_Ed7:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Resource/Resource.h#L87)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

are you sure?
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 11 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NujrpCD51Ja0wgJ31cx:-NunLA8V3keWCkb9nOVM:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d7b917f5bdb44cf18c736971a56d54bb7ce344ad/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L11)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`string` -> `name` like you did in `ActorActionKeeper::startAction`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 22 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NujrzPT9oBjy-XBVNUy:-NunKvwa6Vh7J8fdLLc5:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d7b917f5bdb44cf18c736971a56d54bb7ce344ad/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L22)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

change `string` name as above
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 93 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuju4Km9yOBS0qhjYRE:-NunLyFV9N__eymoMLjd:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d7b917f5bdb44cf18c736971a56d54bb7ce344ad/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L93)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

this should be `frameRate`, not `frame`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-06 21:49 UTC, tetraxile reviewed
> Reviewed 5 of 15 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: all files reviewed, 18 unresolved discussions (waiting on @vakhdmyt06)

___
*[`lib/al/include/Library/Anim/AnimPlayerSkl.h` line 7 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupDdjX0hS8tpoTheP7:-NupDdjX0hS8tpoTheP8:b-1ut373) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/Anim/AnimPlayerSkl.h#L7)):*
> ```objc
> #include "Project/Anim/AnimPlayerBase.h"
> 
> namespace nn {
> ```

you can change this to `namespace nn::g3d` rather than having two nested namespaces
___
*[`lib/al/include/Library/Anim/SklAnimRetargettingInfo.h` line 5 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupENGo1gdmw3whKyTm:-NupENGpCjQ7AiwxKmUZ:b-b5o9e3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/Anim/SklAnimRetargettingInfo.h#L5)):*
> ```objc
> #include <math/seadVector.h>
> 
> namespace nn {
> ```

same as above, `namespace nn::g3d`
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 5 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupNWZ_6GS12iEuX9sm:-NupNWZ_6GS12iEuX9sn:bajwpyn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L5)):*
> ```objc
> #include <basis/seadTypes.h>
> #include <math/seadMatrix.h>
> #include <math/seadVectorFwd.h>
> ```

this should be `seadVector.h`, not `seadVectorFwd.h`
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 315 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupGZDG4wx6wykvIDJs:-NupGZDG4wx6wykvIDJt:bbkw6y6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L315)):*
> ```objc
> 
> namespace alAnimFunction {
> bool isAllAnimEnd(const al::LiveActor*, int);
> ```

`int` -> `s32` for these 4 functions
___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 23 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupK-0I30uYakYaC6a2:-NupK-0I30uYakYaC6a3:buayaaw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/Model/ModelCtrl.h#L23)):*
> ```objc
> private:
>     nn::g3d::ModelObj* mModelObj;
>     int _8;
> ```

`int` -> `s32` for this and mBlockBufferSize
___
*[`lib/al/include/Library/Model/ModelKeeper.h` line 24 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupK34uDS25wkolMMnF:-NupK34uDS25wkolMMnG:b-zehn59) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/Model/ModelKeeper.h#L24)):*
> ```objc
>     void calc(const sead::Matrix34f&, const sead::Vector3f&);
>     void initResource();
>     void createMatAnimForProgram(int);
> ```

`int` -> `s32`
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 3 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupHPOoAnL1eTZFAmBW:-NupHPOoAnL1eTZFAmBX:b7ggai3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Project/Anim/AnimInfo.h#L3)):*
> ```objc
> #pragma once
> 
> namespace nn {
> ```

`namespace nn::g3d`, as above
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 13 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupK5_b7m1LnoJAKOa2:-NupK5_cA_zJwFvmguHa:bcp36fq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Project/Anim/AnimInfo.h#L13)):*
> ```objc
>     void* _0;
>     const nn::g3d::ResMaterialAnim* mResMaterialAnim;
>     int mFrameMax;
> ```

`int` -> `s32` for this and `AnimInfoTable::mInfoCount`
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 20 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupLVDE-bicKyCzlnTZ:-NupLVDE-bicKyCzlnT_:b-c40cwn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Project/Anim/AnimInfo.h#L20)):*
> ```objc
>     int mInfoCount;
>     AnimResInfo* mResInfoStack;
>     bool mIsBool;
> ```

is this meant to be `mIsLoop` like the bool in AnimResInfo above? if not, assuming you didn't mean to call it mIsBool, rename it to `unk` or `_10`. if it's correct though then ignore me (just reply so i know to resolve this comment)
___
*[`lib/al/include/Project/Anim/AnimPlayerVisual.h` line 17 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKBRCD25e7dPdqZMe:-NupKBRCD25e7dPdqZMf:b-pokpop) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Project/Anim/AnimPlayerVisual.h#L17)):*
> ```objc
> 
> private:
>     int mMatType;
> ```

`int` -> `s32` for this and both `tryCreate` functions in this file
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 93 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuju4Km9yOBS0qhjYRE:-NupMJyj3lrAIIXM2mva:b-4l7t0s) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d7b917f5bdb44cf18c736971a56d54bb7ce344ad/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L93)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you changed the wrong one, the argument in `setSklAnimFrame` should be `frame` like it was, but *this* one in `setSklAnimFrameRate` should be `frameRate`.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 104 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKINC5CvHxavItMzy:-NupKIND06Cu3ka8ukDJ:b-zehn59) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L104)):*
> ```cpp
>     return getSkl(actor)->getSklAnimBlendNum();
> }
> f32 getSklAnimBlendWeight(const LiveActor* actor, int index) {
> ```

`int` -> `s32`
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 361 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKPn93OWVGXyw94HB:-NupKPn93OWVGXyw94HC:buxjs8d) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L361)):*
> ```cpp
> }
> void setMclAnimFrameAndStopEnd(LiveActor* actor) {
>     float frameMax = getMcl(actor)->getAnimFrameMax();
> ```

`float` -> `f32`
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 441 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKRxB2O0VeqNqb_1e:-NupKRxB2O0VeqNqb_1f:buxjs8d) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L441)):*
> ```cpp
> }
> void setMtsAnimFrameAndStopEnd(LiveActor* actor) {
>     float frameMax = getMts(actor)->getAnimFrameMax();
> ```

`float` -> `f32`
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 534 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKTn4CpRqCgKKJZi_:-NupKTn4CpRqCgKKJZia:buxjs8d) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L534)):*
> ```cpp
> }
> void setMatAnimFrameAndStopEnd(LiveActor* actor) {
>     float frameMax = getMat(actor)->getAnimFrameMax();
> ```

`float` -> `f32`
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 612 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKW4DDIaK5i6in7fk:-NupKW4DDIaK5i6in7fl:buxjs8d) ([ [...]

2024-04-07 08:11 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: all files reviewed, 18 unresolved discussions (waiting on @tetraxile)

___
*[`lib/al/include/Library/Anim/AnimPlayerSkl.h` line 7 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupDdjX0hS8tpoTheP7:-NurZIKSBrUB2vKHA_Zq:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/Anim/AnimPlayerSkl.h#L7)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

you can change this to `namespace nn::g3d` rather than having two nested namespaces
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Anim/SklAnimRetargettingInfo.h` line 5 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupENGo1gdmw3whKyTm:-NurZKPD2jMSHLfUJ3ji:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/Anim/SklAnimRetargettingInfo.h#L5)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

same as above, `namespace nn::g3d`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 5 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupNWZ_6GS12iEuX9sm:-NurZcUAEujLceaJ32kM:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L5)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

this should be `seadVector.h`, not `seadVectorFwd.h`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 315 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupGZDG4wx6wykvIDJs:-NurZcHHCF3lTfNF-9dx:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L315)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`int` -> `s32` for these 4 functions
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 23 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupK-0I30uYakYaC6a2:-Nurb6MsBL8UNaBzso7m:bmz7dtm) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/Model/ModelCtrl.h#L23)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`int` -> `s32` for this and mBlockBufferSize
</blockquote></details>

mBlockBufferSize? isnt it below?
___
*[`lib/al/include/Library/Model/ModelKeeper.h` line 24 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupK34uDS25wkolMMnF:-Nur_2DeCZTLsPG8Lc_V:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/Model/ModelKeeper.h#L24)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`int` -> `s32`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 3 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupHPOoAnL1eTZFAmBW:-Nur_3Ca7RgON3M7LF2j:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Project/Anim/AnimInfo.h#L3)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`namespace nn::g3d`, as above
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 13 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupK5_b7m1LnoJAKOa2:-NurbFMS5wN9yr7KgHU3:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Project/Anim/AnimInfo.h#L13)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`int` -> `s32` for this and `AnimInfoTable::mInfoCount`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 20 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupLVDE-bicKyCzlnTZ:-Nur_Y8OEg4dDHfOaOGg:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Project/Anim/AnimInfo.h#L20)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

is this meant to be `mIsLoop` like the bool in AnimResInfo above? if not, assuming you didn't mean to call it mIsBool, rename it to `unk` or `_10`. if it's correct though then ignore me (just reply so i know to resolve this comment)
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Anim/AnimPlayerVisual.h` line 17 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKBRCD25e7dPdqZMe:-Nura7m1Dw-LJ5TSbem-:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Project/Anim/AnimPlayerVisual.h#L17)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`int` -> `s32` for this and both `tryCreate` functions in this file
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 93 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuju4Km9yOBS0qhjYRE:-NuraNLpAu9-6zbFPAvx:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d7b917f5bdb44cf18c736971a56d54bb7ce344ad/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L93)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

you changed the wrong one, the argument in `setSklAnimFrame` should be `frame` like it was, but *this* one in `setSklAnimFrameRate` should be `frameRate`.
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 104 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKINC5CvHxavItMzy:-Nura_f_CeGgSBdej85V:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L104)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`int` -> `s32`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 361 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKPn93OWVGXyw94HB:-Nurb-JeC-Z5XTBTyoZV:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L361)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`float` -> `f32`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 441 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKRxB2O0VeqNqb_1e:-Nurb03oD0S-k5Fbqkse:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L441)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`float` -> `f32`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 534 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupKTn4CpRqCgKKJZi_:-Nurb0Xv2LSmAB_WZe8G:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L534)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`float` -> `f32`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 612 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25# [...]

2024-04-07 08:12 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: all files reviewed, 18 unresolved discussions (waiting on @tetraxile)

___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 23 at r6](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NupK-0I30uYakYaC6a2:-NurbK-168HtNkldIAdV:b26p33i) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/08d980c1d87f20da80be74a12e40d53341f1ff33/lib/al/include/Library/Model/ModelCtrl.h#L23)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

mBlockBufferSize? isnt it below?
</blockquote></details>

oh ahem yeah done.


<!-- Sent from Reviewable.io -->

2024-04-07 21:00 UTC, MonsterDruide1 requested changes
> Reviewed 4 of 30 files at r1, 2 of 7 files at r2, 3 of 11 files at r3, 2 of 5 files at r4, 1 of 15 files at r5, 2 of 11 files at r6, 2 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 33 of 39 files reviewed, 38 unresolved discussions (waiting on @tetraxile and @vakhdmyt06)

___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 3 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuDfFD8LAnp_C_y6GR:-NuuDfFD8LAnp_C_y6GS:b-1pvg3k) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L3)):*
> ```objc
> #pragma once
> 
> #include <basis/seadTypes.h>
> ```

useless include, as other `sead` stuff is already included
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 18 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuEPfG4oM80_GFbuXV:-NuuEPfG4oM80_GFbuXW:bweo4cd) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L18)):*
> ```objc
> struct SklAnimRetargettingInfo;
> 
> // Inlined
> ```

I haven't seen `inline` functions anywhere so far, so I'm inclined to think that this is wrong. Maybe those are some other function within the same file? Or ... actually written completely for every usage?
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 101 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHOnG93kCNwLLbv49:-NuuHOnH59kxT1XiV3bU:b3hhnrc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L101)):*
> ```objc
> bool isSklAnimPlaying(const LiveActor*, s32);
> 
> // Mtp
> ```

Styling: Empty line before and after this comment to ensure consistency across the file
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 129 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHTlTEvpTS2VH46dL:-NuuHTlTEvpTS2VH46dM:bmrkhjx) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L129)):*
> ```objc
> bool isMtpAnimPlaying(const LiveActor*);
> 
> // Mcl
> ```

Empty line below
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 158 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHV_gEVnXWjPhufgN:-NuuHV_gEVnXWjPhufgO:bmrkhjx) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L158)):*
> ```objc
> bool isMclAnimPlaying(const LiveActor*);
> 
> // Mts
> ```

Empty line below
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 319 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHiqk06OtBjsZPYTz:-NuuHiqk06OtBjsZPYU-:b-geuwih) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L319)):*
> ```objc
> f32 getAllAnimFrameMax(const al::LiveActor*, s32);
> f32 getAllAnimFrameRate(const al::LiveActor*, s32);
> }  // namespace alAnimFunction
> ```

Can you declare the three remaining functions for this namespace as well?
___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 3 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuI7HY4It6Ro2YeeCD:-NuuI7HY4It6Ro2YeeCE:bsi8rdp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/Model/ModelCtrl.h#L3)):*
> ```objc
> #pragma once
> 
> #include <nn/g3d/ModelObj.h>
> ```

Forward-declare
___
*[`lib/al/include/Library/Resource/Resource.h` line 10 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuImDeCPgbmTj82yd0:-NuuImDeCPgbmTj82yd1:b-fysq9a) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/Resource/Resource.h#L10)):*
> ```objc
> 
> namespace al {
> struct InitResourceDataAction;
> ```

`class`, same for `InitResourceDataAnim` below
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 24 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf8nuPDnOsdkwL1cow:-NuuJaUz6vSpk5PbiIyM:baa4plc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Se/Info/SeAudioInfo.h#L24)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd think it should be `const char*` instead? @tetraxile 
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 3 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuJCaE5kgmZU2efPHS:-NuuJCaF94Z-t-o09lOW:b-g8eq2l) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/Se/Info/SeAudioInfo.h#L3)):*
> ```objc
> #pragma once
> 
> #include <basis/seadTypes.h>
> ```

useless include
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 7 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuJHJUBQbn6wjjNfKi:-NuuJHJUBQbn6wjjNfKj:b-q19qv7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/Se/Info/SeAudioInfo.h#L7)):*
> ```objc
> #include <prim/seadSafeString.h>
> 
> #include "Library/Yaml/ByamlIter.h"
> ```

forward-declare
___
*[`lib/al/include/Project/Action/ActionBgmCtrl.h` line 18 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuJqtY2Acf7Q-3R9pd:-NuuJqtY2Acf7Q-3R9pe:b7gy6x0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Action/ActionBgmCtrl.h#L18)):*
> ```objc
>     void update(float, float, float, bool);
> 
>     virtual AudioKeeper* getAudioKeeper() const override;
> ```

`virtual` should be removed, as `override` is already specified
___
*[`lib/al/include/Project/Action/ActionPadAndCameraCtrl.h` line 6 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuKBi7-sb3XwCZ2Q3G:-NuuKBi7-sb3XwCZ2Q3H:b-q19qv7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Action/ActionPadAndCameraCtrl.h#L6)):*
> ```objc
> 
> #include "Library/LiveActor/LiveActor.h"
> #include "Library/Resource/Resource.h"
> ```

forward-declare



_Code quote:_
```objc
#include "Library/LiveActor/LiveActor.h"
#include "Library/Resource/Resource.h"
```
___
*[`lib/al/include/Project/Action/ActionSeCtrl.h` line 6 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuKO5m9M0IuCbF8THR:-NuuKO5m9M0IuCbF8THS:b1vcgr4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Action/ActionSeCtrl.h#L6)):*
> ```objc
> class AudioKeeper;
> class SeKeeper;
> class SeUserInfo;
> ```

`struct`
___
*[`lib/al/include/Project/Action/InitResourceDataAction.h` line 7 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuKT4h36lROkA0-SpX:-NuuKT4h36lROkA0-SpY:b-h0cvg4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Action/InitResourceDataAction.h#L7)):*
> ```objc
> namespace al {
> struct InitResourceDataActionAnim;
> struct InitResourceDataAnim;
> ```

`class`es for both of them



_Code quote:_
```objc
struct InitResourceDataActionAnim;
struct InitResourceDataAnim;
```
___
*[`lib/al/include/Project/Action/InitResourceDataActionAnim.h` line 6 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuKipu3_ZFAe2zTA4G:-NuuKipu3_ZFAe2zTA4 [...]

2024-04-08 12:03 UTC, tetraxile reviewed
> Reviewed 6 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: all files reviewed, 20 unresolved discussions (waiting on @vakhdmyt06)

___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 24 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf8nuPDnOsdkwL1cow:-NuxTWho9D3QtL_5eA5N:b-cvysnj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Se/Info/SeAudioInfo.h#L24)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I'd think it should be `const char*` instead? @tetraxile
</blockquote></details>

right, my bad -- was looking at it in ghidra and forgot that ghidra doesn't support `const`!


<!-- Sent from Reviewable.io -->

2024-04-08 15:31 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: all files reviewed, 20 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 3 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuDfFD8LAnp_C_y6GR:-Nuy9Hi75YImXadvqqya:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

useless include, as other `sead` stuff is already included
</blockquote></details>

Done.
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 18 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuEPfG4oM80_GFbuXV:-Nuy3pNH7FuaFo8g2dP4:b-suyvpv) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L18)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I haven't seen `inline` functions anywhere so far, so I'm inclined to think that this is wrong. Maybe those are some other function within the same file? Or ... actually written completely for every usage?
</blockquote></details>

well, i wrote it cause of laziness, didnt want to write actor->getModelKeeper()getSklAnim every time
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 101 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHOnG93kCNwLLbv49:-Nuy9Y4o3tgBPaDeQ3m5:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L101)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Styling: Empty line before and after this comment to ensure consistency across the file
</blockquote></details>

Done.
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 129 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHTlTEvpTS2VH46dL:-Nuy9_u28XwLd5WUKPsv:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L129)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Empty line below
</blockquote></details>

Done.
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 158 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHV_gEVnXWjPhufgN:-Nuy9_Il-Xm2MqrWKYoW:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L158)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Empty line below
</blockquote></details>

Done.
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 319 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHiqk06OtBjsZPYTz:-NuyK2cnBIpxUD8J9zV9:bx6h3zp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L319)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Can you declare the three remaining functions for this namespace as well?
</blockquote></details>

it was two, and somewhy they are in another file/another position than these. not sure if they were defined seperately in another file... i mean, this file is full of frame and name functions, so these alAnimFunctions are positioned here.......... no idea
didnt add them tho
___
*[`lib/al/include/Library/Model/ModelCtrl.h` line 3 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuI7HY4It6Ro2YeeCD:-Nuy9oNxBBUZGd3JV0lH:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/Model/ModelCtrl.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Forward-declare
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Resource/Resource.h` line 10 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuImDeCPgbmTj82yd0:-Nuy9xjSETPTps1plVHp:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/Resource/Resource.h#L10)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`class`, same for `InitResourceDataAnim` below
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 3 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuJCaE5kgmZU2efPHS:-NuyA4xH4_rBCSAYwN-k:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/Se/Info/SeAudioInfo.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

useless include
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 7 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuJHJUBQbn6wjjNfKi:-NuyA5dUAfHaZD-YYuTF:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/Se/Info/SeAudioInfo.h#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

forward-declare
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionBgmCtrl.h` line 18 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuJqtY2Acf7Q-3R9pd:-NuyBbx47QJIcDXJoDi-:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Action/ActionBgmCtrl.h#L18)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`virtual` should be removed, as `override` is already specified
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionPadAndCameraCtrl.h` line 6 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuKBi7-sb3XwCZ2Q3G:-NuyBt6hDBxWnITp43E8:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Action/ActionPadAndCameraCtrl.h#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

forward-declare
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/ActionSeCtrl.h` line 6 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuKO5m9M0IuCbF8THR:-NuyGg69EL1-goJ0KQfv:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Action/ActionSeCtrl.h#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`struct`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/InitResourceDataAction.h` line 7 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuKT4h36lROkA0-SpX:-NuyC22zEQW6PBTRCQdB:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Action/InitResourceDataAction.h#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`class`es for both of them
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/InitResourceDataActionAnim.h` line 6 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuKipu3_ZFAe2zTA4G:-NuyC8ZG7tf5aN3QOhLy:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/A [...]

2024-04-08 22:42 UTC, MonsterDruide1 requested changes
> Reviewed 4 of 30 files at r1, 1 of 11 files at r3, 10 of 20 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 31 of 41 files reviewed, 8 unresolved discussions (waiting on @tetraxile and @vakhdmyt06)

___
*[`.github/workflows/copy-headers.yml` line 55 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuzoce12JyNNNF2kDYv:-Nuzoce12JyNNNF2kDYw:b-od6oja) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/.github/workflows/copy-headers.yml#L55)):*
> ```YAML
>           echo "AUTHOR_NAME=$COMMIT_AUTHOR_NAME" >> "$GITHUB_ENV"
>           echo "AUTHOR_MAIL=$COMMIT_AUTHOR_MAIL" >> "$GITHUB_ENV"
>           echo "MESSAGE=$COMMIT_MESSAGE" >> "$GITHUB_ENV"
> ```

Please do not change this back, I guess this just happened due to a faulty rebase.
___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 18 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuEPfG4oM80_GFbuXV:-NuzrusJ2VcwlAXHhyI5:b-blnr5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L18)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

well, i wrote it cause of laziness, didnt want to write actor->getModelKeeper()getSklAnim every time
</blockquote></details>

Okay, looking at the `cpp`, there's quite a number of those... I guess it's fine then.
___
*[`lib/al/include/Library/Se/Info/SeAudioInfo.h` line 24 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuf8nuPDnOsdkwL1cow:-NuzpMFS5WlmJttBt6MC:b-ijuwdu) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/abb6a7474d13b30af3bd137e25b307e25aadd562/lib/al/include/Library/Se/Info/SeAudioInfo.h#L24)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

right, my bad -- was looking at it in ghidra and forgot that ghidra doesn't support `const`!
</blockquote></details>

@vakhdmyt06 No, it should've been `PtrArray<const char*>`. I was just too lazy to write the full type.
___
*[`lib/al/include/Project/Action/InitResourceDataActionAnim.h` line 12 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuzqArY81kHiTWYfbrd:-NuzqArY81kHiTWYfbre:b8xk3ub) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/include/Project/Action/InitResourceDataActionAnim.h#L12)):*
> ```objc
> class InitResourceDataActionAnim {
> public:
>     static InitResourceDataActionAnim* tryCreate(Resource*, InitResourceDataAnim const*,
> ```

`const TYPE*`, same below
___
*[`lib/al/include/Project/Action/InitResourceDataActionAnim.h` line 16 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuzqF9pB9EzwHpIYxeN:-NuzqF9pB9EzwHpIYxeO:b-wlkpx0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/include/Project/Action/InitResourceDataActionAnim.h#L16)):*
> ```objc
> 
>     InitResourceDataActionAnim(Resource*, InitResourceDataAnim const*, char const* resourceYml);
>     void sortCtrlInfo(void);
> ```

Do not specify `(void)` as parameter
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 18 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuzqKLXDxi-K4VqZbQw:-NuzqKLXDxi-K4VqZbQx:b-libcs6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/include/Project/Anim/AnimInfo.h#L18)):*
> ```objc
> 
> class AnimInfoTable {
>     u32 mInfoCount;
> ```

`public:`
___
*[`lib/al/include/Project/Anim/AnimPlayerBase.h` line 13 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuLIuADZhjnZROwTZd:-NuzqTMY8zvWe5v6VrbA:bvo47m5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Anim/AnimPlayerBase.h#L13)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done. even though i had to change \_ZN2al14AnimPlayerBaseC1Ev to \_ZN2al14AnimPlayerBaseC2Ev so that it matches again... i cant find calcNeedUpdateAnimNext in AnimPlayerBase......
</blockquote></details>

You added it twice, once with a typo. Also, you can't find it in the base class, as it is a pure virtual function (`= 0`), it is only known to exist due to the `__cxa_pure_virtual` entry in the `vtable`.
___
*[`lib/al/include/Project/Anim/AnimPlayerSimple.h` line 12 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuLdof1Gr2UZQsTjwD:-NuzqpYL8LhXZPEwNce2:bjgt0h2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Anim/AnimPlayerSimple.h#L12)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

are you sure? i found no such functions for animplayersimple... added virtual void init and setAnimToModel though

done
</blockquote></details>

Yes, see above (pure virtual vtable entries)
___
*[`lib/al/include/Project/Anim/AnimPlayerSimple.h` line 12 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuLWF7B851hiC-mzHx:-Nuzqydu6Y20doQd73Ua:b-2pf6vo) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Anim/AnimPlayerSimple.h#L12)):*
<details><summary><i>Previously, vakhdmyt06 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You shouldn't delete it, only mark it as `override`.


<!-- Sent from Reviewable.io -->

2024-04-09 10:52 UTC, vakhdmyt06 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 31 of 41 files reviewed, 8 unresolved discussions (waiting on @MonsterDruide1 and @tetraxile)

___
*[`.github/workflows/copy-headers.yml` line 55 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuzoce12JyNNNF2kDYv:-Nv1LrbQ7GY-1yc3LNaT:bqueiks) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/.github/workflows/copy-headers.yml#L55)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Please do not change this back, I guess this just happened due to a faulty rebase.
</blockquote></details>

uh what
___
*[`lib/al/include/Project/Action/InitResourceDataActionAnim.h` line 12 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuzqArY81kHiTWYfbrd:-Nv1NLtdEYnR15W_S1vr:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/include/Project/Action/InitResourceDataActionAnim.h#L12)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`const TYPE*`, same below
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/InitResourceDataActionAnim.h` line 16 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuzqF9pB9EzwHpIYxeN:-Nv1NMKV8G9K43W5N-ci:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/include/Project/Action/InitResourceDataActionAnim.h#L16)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Do not specify `(void)` as parameter
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 18 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuzqKLXDxi-K4VqZbQw:-Nv1SsnP8EQ5bFJgO7Sz:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/include/Project/Anim/AnimInfo.h#L18)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`public:`
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Anim/AnimPlayerBase.h` line 13 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuLIuADZhjnZROwTZd:-Nv1NnbQ3dHE1Ve78voT:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Anim/AnimPlayerBase.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

You added it twice, once with a typo. Also, you can't find it in the base class, as it is a pure virtual function (`= 0`), it is only known to exist due to the `__cxa_pure_virtual` entry in the `vtable`.
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Anim/AnimPlayerSimple.h` line 12 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuLWF7B851hiC-mzHx:-Nv1U9ax-pETLORvKSsc:b-tcsq85) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Anim/AnimPlayerSimple.h#L12)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

You shouldn't delete it, only mark it as `override`.
</blockquote></details>

Done.
i kinda forgot what it was though........


<!-- Sent from Reviewable.io -->

2024-04-10 16:04 UTC, MonsterDruide1 requested changes
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 31 of 41 files reviewed, 27 unresolved discussions (waiting on @Moddimation and @tetraxile)

___
*[`lib/al/src/Library/Action/ActorActionKeeper.cpp` line 26 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7YbSc573cIMBiLAIF:-Nv7YbSdDkxQ-W26-SO2:b4hekuy) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/Action/ActorActionKeeper.cpp#L26)):*
> ```cpp
>                                      ActionPadAndCameraCtrl* padAndCamCtrl,
>                                      ActionScreenEffectCtrl* screenEffectCtrl)
> ```

Why add an empty line here? Seems like this would be more confusing.
___
*[`lib/al/src/Library/Action/ActorActionKeeper.cpp` line 63 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7YqTr5F2WcKmynmgb:-Nv7YqTr5F2WcKmynmgc:b-4jh7ap) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/Action/ActorActionKeeper.cpp#L63)):*
> ```cpp
>                                       newScreenEffectCtrl);
>     }
>     return newMe;
> ```

```cpp
if(newAnimCtrl || newFlagCtrl || ...) {
  return new ActorActionKeeper(...);
} else {
  return nullptr;
}
```



_Code quote:_
```cpp
    ActorActionKeeper* newMe = nullptr;

    if (newAnimCtrl || newFlagCtrl || newEffectCtrl || newSeCtrl || newBgmCtrl ||
        newPadAndCameraCtrl || newScreenEffectCtrl) {
        newMe = new ActorActionKeeper(actor, name, newAnimCtrl, newNerveCtrl, newFlagCtrl,
                                      newEffectCtrl, newSeCtrl, newBgmCtrl, newPadAndCameraCtrl,
                                      newScreenEffectCtrl);
    }
    return newMe;
```
___
*[`lib/al/src/Library/Action/ActorActionKeeper.cpp` line 77 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7ZH_Z40Czkxdj3s0h:-Nv7ZB0F1nGA1rRrEskF:bkavqzc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/Action/ActorActionKeeper.cpp#L77)):*
> ```cpp
>     if (mAnimCtrl)
>         return mAnimCtrl->start(name);
>     return false;
> ```

```cpp
return mAnimCtrl && mAnimCtrl->start(name);
```



_Code quote:_
```cpp
    if (mAnimCtrl)
        return mAnimCtrl->start(name);
    return false;
```
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 21 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7_VNV6DZdzigdLaYx:-Nv7_VNV6DZdzigdLaYy:bfziyr1) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L21)):*
> ```cpp
> }
> bool tryStartAction(LiveActor* actor, const char* actionName) {
>     ActorActionKeeper* actionKeeper = actor->getActorActionKeeper();
> ```

Try to remove this variable entirely, and always access `actor->getActorActionKeeper()` - this might eliminate some of the re-fetching while still matching
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 25 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7i4Ml2vJftVfpocCK:-Nv7i4Ml2vJftVfpocCL:b-av196i) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L25)):*
> ```cpp
>         return false;
> 
>     getSkl(actor)->startSklAnim(nullptr, animName, nullptr, nullptr, nullptr, nullptr, nullptr);
> ```

`startSklAnim(actor, animName)`
similar for most such calls below
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 161 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7iSY-0P1vJ2jx-Ju5:-Nv7iSY-0P1vJ2jx-Ju6:b-qpm802) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L161)):*
> ```cpp
>     if (isSync) {
>         f32 frameMax0 = sklAnim->getSklAnimFrameMax(0);
>         for (s32 i = 1; i < sklAnim->getSklAnimBlendNum(); ++i) {
> ```

`i++` is what the most part of the repo uses. same below
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 167 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7iKMk4RVFQHujI1S5:-Nv7iKMk4RVFQHujI1S6:be9x4fo) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L167)):*
> ```cpp
>             }
>         }
>     } else
> ```

Should also have `{}`, otherwise this looks weird - multiline blocks should always have `{}`.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 168 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7idJI7orkBfp28E8I:-Nv7idJI7orkBfp28E8J:b-eakndt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L168)):*
> ```cpp
>         }
>     } else
>         for (s32 j = 1; j < sklAnim->getSklAnimBlendNum(); ++j) {
> ```

Use `i` and `i++` here. Same below (in other functions)
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 197 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7isoW-MRf75jCgyT1:-Nv7isoW-MRf75jCgyT2:b-nz5zaa) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L197)):*
> ```cpp
> void startMtpAnimAndSetFrameAndStop(LiveActor* actor, const char* animName, f32 frame) {
>     getMtp(actor)->startAnim(animName);
>     updateModelDraw(actor);
> ```

`startMtpAnim(actor, animName);`



_Code quote:_
```cpp
    getMtp(actor)->startAnim(animName);
    updateModelDraw(actor);
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 199 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7ixfuCcGbm-3Ul-p_:-Nv7ixfuCcGbm-3Ul-pa:b-6m05ok) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L199)):*
> ```cpp
>     updateModelDraw(actor);
>     getMtp(actor)->setAnimFrame(frame);
>     updateModelDraw(actor);
> ```

`setMtpAnimFrame(actor, frame);`



_Code quote:_
```cpp
    getMtp(actor)->setAnimFrame(frame);
    updateModelDraw(actor);
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 200 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7jKF30bieHSlxBrO_:-Nv7jKF30bieHSlxBrOa:bw41sa4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L200)):*
> ```cpp
>     getMtp(actor)->setAnimFrame(frame);
>     updateModelDraw(actor);
>     getMtp(actor)->setAnimFrameRate(0.0);
> ```

`setMtpAnimFrameRate(0.0f);`
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 208 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7jWEM7GXVf1kuUKMq:-Nv7jWEM7GXVf1kuUKMr:b-b8byuh) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L208)):*
> ```cpp
> bool tryStartMtpAnimIfExist(LiveActor* actor, const char* animName) {
>     if (getMtp(actor)) {
>         if (getMtp(actor)->isAnimExist(animName)) {
> ```

Flip logic, early `return false;`



_Code quote:_
```cpp
    if (getMtp(actor)) {
        if (getMtp(actor)->isAnimExist(animName)) {
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 210 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7jR__9y96dcRIAIKY:-Nv7jR__9y96dcRIAIKZ:b-nz5zaa) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/L [...]

2024-04-10 16:11 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 20 files at r8, 1 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 33 of 41 files reviewed, 23 unresolved discussions (waiting on @Moddimation and @tetraxile)

___
*[`lib/al/include/Library/LiveActor/ActorInitResourceData.h` line 11 at r9](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7lgoS4X1FLTcypcT6:-Nv7lgoS4X1FLTcypcT7:b-1ip3pg) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4d87306f77ab0811d6aca33b6af607be897d2246/lib/al/include/Library/LiveActor/ActorInitResourceData.h#L11)):*
> ```objc
> class ActorInitResourceData {
> public:
>     ActorInitResourceData(Resource* res) : mResource(res) {
> ```

Shouldn't be defined in the header, as it will not generate the code as function, but will be inlined everywhere instead.
___
*[`lib/al/include/Project/Action/InitResourceDataActionAnim.h` line 13 at r9](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7ksCGDRH-yEoRudgD:-Nv7ksCGDRH-yEoRudgE:b4r4zb5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4d87306f77ab0811d6aca33b6af607be897d2246/lib/al/include/Project/Action/InitResourceDataActionAnim.h#L13)):*
> ```objc
> public:
>     static InitResourceDataActionAnim* tryCreate(Resource*, const InitResourceDataAnim*,
>                                                  char const*);
> ```

Missed one `const char*` here
___
*[`lib/al/include/Project/Anim/AnimPlayerSimple.h` line 12 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuLWF7B851hiC-mzHx:-Nv7lLob9WtGUhn46HPG:bqhg6rt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Project/Anim/AnimPlayerSimple.h#L12)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
i kinda forgot what it was though........
</blockquote></details>

You got all of them now, I think.


<!-- Sent from Reviewable.io -->

2024-04-10 21:02 UTC, Moddimation reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 27 of 45 files reviewed, 23 unresolved discussions (waiting on @MonsterDruide1 and @tetraxile)

___
*[`.github/workflows/copy-headers.yml` line 55 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nuzoce12JyNNNF2kDYv:-Nv7n4gx2X_E4NAJWT_O:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/.github/workflows/copy-headers.yml#L55)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

You introduced a change here, probably because I recently committed this (left side) on `master`, so I guess you accidentally changed this back - somehow.

https://github.com/MonsterDruide1/OdysseyDecomp/commit/dd328ecc684c27e1edca3c9962fae350a46ce541
</blockquote></details>

Done.
___
*[`lib/al/include/Library/LiveActor/ActorInitResourceData.h` line 11 at r9](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7lgoS4X1FLTcypcT6:-Nv7narm2pncXQarALa-:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4d87306f77ab0811d6aca33b6af607be897d2246/lib/al/include/Library/LiveActor/ActorInitResourceData.h#L11)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Shouldn't be defined in the header, as it will not generate the code as function, but will be inlined everywhere instead.
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Action/InitResourceDataActionAnim.h` line 13 at r9](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7ksCGDRH-yEoRudgD:-Nv7oBey5RjIZtBTXHD3:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4d87306f77ab0811d6aca33b6af607be897d2246/lib/al/include/Project/Action/InitResourceDataActionAnim.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Missed one `const char*` here
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Action/ActorActionKeeper.cpp` line 26 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7YbSc573cIMBiLAIF:-Nv7pi4eEwJBYlRo4ezS:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/Action/ActorActionKeeper.cpp#L26)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Why add an empty line here? Seems like this would be more confusing.
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Action/ActorActionKeeper.cpp` line 63 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7YqTr5F2WcKmynmgb:-Nv7q19-68xRqirjiBSr:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/Action/ActorActionKeeper.cpp#L63)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

```cpp
if(newAnimCtrl || newFlagCtrl || ...) {
  return new ActorActionKeeper(...);
} else {
  return nullptr;
}
```
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Action/ActorActionKeeper.cpp` line 77 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7ZH_Z40Czkxdj3s0h:-Nv7qxAg9ZSC0_DKfnbU:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/Action/ActorActionKeeper.cpp#L77)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

```cpp
return mAnimCtrl && mAnimCtrl->start(name);
```
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 21 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7_VNV6DZdzigdLaYx:-Nv7rqBA9F7RLkp6UAhx:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L21)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Try to remove this variable entirely, and always access `actor->getActorActionKeeper()` - this might eliminate some of the re-fetching while still matching
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 25 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7i4Ml2vJftVfpocCK:-Nv7skX80_LsQfErulKR:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L25)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`startSklAnim(actor, animName)`
similar for most such calls below
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 161 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7iSY-0P1vJ2jx-Ju5:-Nv7sy8V1f7UTkmMlJwk:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L161)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`i++` is what the most part of the repo uses. same below
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 167 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7iKMk4RVFQHujI1S5:-Nv7t4dvC0c8n3OEP0x_:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L167)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should also have `{}`, otherwise this looks weird - multiline blocks should always have `{}`.
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 168 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7idJI7orkBfp28E8I:-Nv7t8GW7_x3ZdL6POln:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L168)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Use `i` and `i++` here. Same below (in other functions)
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 197 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7isoW-MRf75jCgyT1:-Nv7tPje5u4goY4zyvgS:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L197)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`startMtpAnim(actor, animName);`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 199 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7ixfuCcGbm-3Ul-p_:-Nv7tYgeEC1rNnQqDT8z:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L199)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`setMtpAnimFrame(actor, frame);`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 200 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7jKF30bieHSlxBrO_:-Nv7v-IhDuufqN7Dsi0c:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L200)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`setMtpAnimFrameRate(0.0f);`
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 208 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDe [...]

2024-04-10 23:49 UTC, MonsterDruide1 requested changes
> Reviewed 4 of 14 files at r10.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 31 of 45 files reviewed, 21 unresolved discussions (waiting on @Moddimation and @tetraxile)

___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 19 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9OsDX0ks7rxM2K40s:-Nv9OsDX0ks7rxM2K40t:bijtgj4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L19)):*
> ```cpp
> }
> bool tryStartAction(LiveActor* actor, const char* actionName) {
>     if ((!actor->getActorActionKeeper() || !actor->getActorActionKeeper()->getAnimCtrl() ||
> ```

Double parentheses
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 27 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9OuDf8y9XpUng6Toh:-Nv9OuDf8y9XpUng6Toi:bijtgj4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L27)):*
> ```cpp
>         bool visStarted = tryStartVisAnimIfExistForAction(actor, actionName);
> 
>         if ((!sklStarted && !mtpStarted && !mclStarted && !mtsStarted && !visStarted)) {
> ```

Double parentheses
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 35 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9P8BR5GvZXRPASG16:-Nv9P8BR5GvZXRPASG17:b-t269fc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L35)):*
> ```cpp
>     }
>     actor->getActorActionKeeper()->startAction(actionName);
>     return true;
> ```

```cpp
    }
    if (actor->getActorActionKeeper()) {
        actor->getActorActionKeeper()->startAction(actionName);
    }
    return true;
```



_Code quote:_
```cpp
        if (!actor->getActorActionKeeper()) {
            return true;
        }
    }
    actor->getActorActionKeeper()->startAction(actionName);
    return true;
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 278 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7k0tA5Djzw-0R5-CL:-Nv9M3LgDYl9TQ_5QaSe:b-lg10c1) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L278)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, not quite
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 14 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9Jx7I42L3PRj1p7Pk:-Nv9Jx7I42L3PRj1p7Pl:b1xx6ib) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L14)):*
> ```cpp
> namespace al {
> void startSklAnim(LiveActor* actor, const char* animName) {
>     getSkl(actor)->startSklAnim(nullptr, animName, nullptr, nullptr, nullptr, nullptr, nullptr);
> ```

startSklAnimBlendInterpole(nullptr, animName, nullptr, ...);
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 17 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9K2T52hWMxGIpIcfA:-Nv9K2T52hWMxGIpIcfB:brtlvdk) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L17)):*
> ```cpp
> }
> void startSklAnimInterpole(LiveActor* actor, const char* animName0, const char* animName1) {
>     getSkl(actor)->startSklAnim(animName1, animName0, nullptr, nullptr, nullptr, nullptr, nullptr);
> ```

startSklAnimBlendInterpole(...)
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 23 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9K9GBC161QpsaMQZ_:-Nv9K9GBC161QpsaMQZa:b-2hy538) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L23)):*
> ```cpp
>         return false;
>     if (!getSkl(actor)->isSklAnimExist(animName))
>         return false;
> ```

if(!isSklAnimExist(actor, animName)) return false;



_Code quote:_
```cpp
    if (!getSkl(actor))
        return false;
    if (!getSkl(actor)->isSklAnimExist(animName))
        return false;
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 29 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KIGZ4gl7WwDSsszq:-Nv9KIGZ4gl7WwDSsszr:bgqp39g) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L29)):*
> ```cpp
> }
> bool isSklAnimExist(const LiveActor* actor, const char* animName) {
>     if (!getSkl(actor))
> ```

if(!isSklAnimExist(actor))
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 38 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KOR54Y_30IlJwNkk:-Nv9KOR54Y_30IlJwNkl:bh74tny) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L38)):*
> ```cpp
> 
>     if (playingName && isEqualString(animName, playingName))
>         return false;
> ```

if(isSklAnimPlaying(actor, animName, 0)) return false;



_Code quote:_
```cpp
    const char* playingName = getSkl(actor)->getPlayingSklAnimName(0);

    if (playingName && isEqualString(animName, playingName))
        return false;
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 43 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KeVa0dkCDWmEuWnY:-Nv9KeVa0dkCDWmEuWnZ:bbp90o3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L43)):*
> ```cpp
> }
> bool isSklAnimPlaying(const LiveActor* actor, const char* animName, s32 index) {
>     const char* playingName = getSkl(actor)->getPlayingSklAnimName(index);
> ```

const char* playingName = getPlayingSklAnimName(actor, index);



_Code quote:_
```cpp
const char* playingName = getSkl(actor)->getPlayingSklAnimName(index);
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 50 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KXrk09GMNJCqIzmE:-Nv9KXrk09GMNJCqIzmF:bgdig6u) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L50)):*
> ```cpp
>                        const char* animName5) {
>     getSkl(actor)->startSklAnim(nullptr, animName0, animName1, animName2, animName3, animName4,
>                                 animName5);
> ```

startSklAnimBlendInterpole(nullptr, animName0, ...);



_Code quote:_
```cpp
    getSkl(actor)->startSklAnim(nullptr, animName0, animName1, animName2, animName3, animName4,
                                animName5);
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 114 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9LKG91KM6bisHjhAH:-Nv9LKG91KM6bisHjhAI:b-bkv0e3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L114)):*
> ```cpp
>     getSkl(actor)->setSklAnimBlendWeight(0, weight);
>     f32 weightCalc = 1 - weight;
>     getSkl(actor)->setSklAnimBlendWeight(1, weightCalc);
> ```

getSkl(actor)->setSklAnimBlendWeight(1, 1 - weight);



_Code quote:_
```cpp
    f32 weightCalc = 1 - weight;
    getSkl(actor)->setSklAnimBlendWeight(1, weightCalc);
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 229 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9ME [...]

2024-04-10 23:59 UTC, MonsterDruide1 requested changes
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 31 of 45 files reviewed, 26 unresolved discussions (waiting on @Moddimation and @tetraxile)

___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 114 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9LKG91KM6bisHjhAH:-Nv9QlvNCOqJxpE4viTj:b5f77nf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L114)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

getSkl(actor)->setSklAnimBlendWeight(1, 1 - weight);
</blockquote></details>

Might even be an inlined call to the other `setSklAnimBlendWeightDouble`?
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 155 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9R3kqBGZuYDdch3Zx:-Nv9R3kqBGZuYDdch3Zy:bcrifrc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L155)):*
> ```cpp
>     getSkl(actor)->calcSklAnim();
> }
> void setSklAnimBlendFrameAll(LiveActor* actor, f32 frame, bool isSync) {
> ```

For this function and the one below: A lot of inlined calls
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 251 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9RA-e-N1H0Q871WHl:-Nv9RA-fAATG9PrWUt8G:b-vt7ju1) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L251)):*
> ```cpp
> }
> bool isMtpAnimPlaying(const LiveActor* actor) {
>     if (!getMtp(actor))
> ```

if(!isMtpAnimExist(actor)) return false;
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 285 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9RJi1DrqHzjQ4OYjg:-Nv9RJi1DrqHzjQ4OYjh:bghf8my) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L285)):*
> ```cpp
>         return false;
>     if (!getMcl(actor)->isAnimExist(animName))
>         return false;
> ```

if(!isMclAnimExist(actor, animName)) return false;



_Code quote:_
```cpp
    if (!isMclAnimExist(actor))
        return false;
    if (!getMcl(actor)->isAnimExist(animName))
        return false;
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 379 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9RaEu5_qlKIpu76uC:-Nv9RaEu5_qlKIpu76uD:b-91wcj9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L379)):*
> ```cpp
>     if (!isMtsAnimExist(actor))
>         return false;
>     return getMts(actor)->isAnimExist(animName);
> ```

return ... && ...



_Code quote:_
```cpp
    if (!isMtsAnimExist(actor))
        return false;
    return getMts(actor)->isAnimExist(animName);
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 499 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9Ri5c3QmPyCVEh0Lk:-Nv9Ri5c3QmPyCVEh0Ll:b-91wcj9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L499)):*
> ```cpp
>         return getMat(actor)->isAnimPlaying();
>     }
>     return false;
> ```

return ... && ...



_Code quote:_
```cpp
    if (isMatAnimExist(actor)) {
        return getMat(actor)->isAnimPlaying();
    }
    return false;
```


<!-- Sent from Reviewable.io -->

2024-04-15 17:05 UTC, Moddimation reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 31 of 45 files reviewed, 26 unresolved discussions (waiting on @MonsterDruide1 and @tetraxile)

___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 19 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9OsDX0ks7rxM2K40s:-NvAvPAF92VHsK2nlcRU:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L19)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Double parentheses
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 27 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9OuDf8y9XpUng6Toh:-NvAvPj50ogq6PN6o3kF:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Double parentheses
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 35 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9P8BR5GvZXRPASG16:-NvAvxttA-qubegm6PfY:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L35)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

```cpp
    }
    if (actor->getActorActionKeeper()) {
        actor->getActorActionKeeper()->startAction(actionName);
    }
    return true;
```
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 278 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7k0tA5Djzw-0R5-CL:-NvH_s1XEao4kQu4CpWZ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L278)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No, not quite
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 14 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9Jx7I42L3PRj1p7Pk:-NvAw_Gv4eskUqQvKOPT:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

startSklAnimBlendInterpole(nullptr, animName, nullptr, ...);
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 17 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9K2T52hWMxGIpIcfA:-NvAw_nlBlf-nOPEZhcc:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

startSklAnimBlendInterpole(...)
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 23 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9K9GBC161QpsaMQZ_:-NvHLaXp1tS4ZR_APppf:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L23)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

if(!isSklAnimExist(actor, animName)) return false;
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 29 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KIGZ4gl7WwDSsszq:-NvHLb_s78hJ8rA-BmLm:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L29)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

if(!isSklAnimExist(actor))
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 38 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KOR54Y_30IlJwNkk:-NvHLyEGDhdcYscDLdtv:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L38)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

if(isSklAnimPlaying(actor, animName, 0)) return false;
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 43 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KeVa0dkCDWmEuWnY:-NvHMASk5Fo-zRUWsbFY:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L43)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

const char* playingName = getPlayingSklAnimName(actor, index);
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 50 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KXrk09GMNJCqIzmE:-NvHMgkOD35nO0A1rb49:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L50)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

startSklAnimBlendInterpole(nullptr, animName0, ...);
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 114 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9LKG91KM6bisHjhAH:-NvHN43eDIalYeFPnaSs:b-hg0h0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L114)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Might even be an inlined call to the other `setSklAnimBlendWeightDouble`?
</blockquote></details>

if i do that, it doesnt match anymore... 
https://decomp.me/scratch/95fAI
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 155 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9R3kqBGZuYDdch3Zx:-NvH_2Ok4_WJM35xriKX:bz0uicc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L155)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

For this function and the one below: A lot of inlined calls
</blockquote></details>

tried that, but it ends up not allocating that one *sklAnim and the function doesnt match.
https://decomp.me/scratch/9wCMn
Ignore the blue box above
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 229 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9ME9FDmCJEDNiqdAj:-NvH_V2h59NwLPNIbiMQ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L229)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

return isEqualString(animName, getPlayingAnimName(actor));
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 251 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9RA-e-N1H0Q871WHl:-NvH_b-lC1DxXm7qesjO:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f7055c948e7131712dbb34e5c7fb3b598ab8fa61/lib/al/src/Library/Liv [...]

2024-04-15 19:38 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 5 files at r9, 4 of 14 files at r10, 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 36 of 46 files reviewed, 24 unresolved discussions (waiting on @Moddimation and @tetraxile)

___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 319 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHiqk06OtBjsZPYTz:-NvYFzun4NBGm95jo8bH:b-fg2w09) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L319)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

it was two, and somewhy they are in another file/another position than these. not sure if they were defined seperately in another file... i mean, this file is full of frame and name functions, so these alAnimFunctions are positioned here.......... no idea
didnt add them tho
</blockquote></details>

Hmm. Very interesting, do not add them then.
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 24 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvY5bFB9y7AzGe94Sm5:-NvY5bFB9y7AzGe94Sm6:bjvuki7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/include/Project/Anim/AnimInfo.h#L24)):*
> ```objc
>     bool tryFindAnimInfo(const char* name);
> 
>     void add(const char* name, nn::g3d::ResMaterialAnim*, f32 frameMax, bool isLoop);
> ```

The symbol says `void*` as second parameter here. Even if it might be more specific in practice, to generate matching code/symbols again we have to follow their types.
___
*[`lib/al/include/Project/Anim/AnimPlayerBase.h` line 12 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvY5qJO6qkj_rDCWGrn:-NvY5qJO6qkj_rDCWGro:b-e99m37) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/include/Project/Anim/AnimPlayerBase.h#L12)):*
> ```objc
>     AnimPlayerBase();
> 
>     virtual void updateLast() = 0;
> ```

This one is not `=0` (see `A3BD64`)
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 19 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9OsDX0ks7rxM2K40s:-NvY6jQ84rapYI8UZtjj:b-1flmac) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L19)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, I meant you should remove the double parentheses
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 27 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9OuDf8y9XpUng6Toh:-NvY6m-pBYc4C24o4KZC:b-1flmac) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L27)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, I meant you should remove the double parentheses
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 278 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7k0tA5Djzw-0R5-CL:-NvYFgOD6XnKYh15EIhL:bcgy02k) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L278)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What happened now? That's still different than what I'm suggesting though.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 14 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9Jx7I42L3PRj1p7Pk:-NvY7eTgDhSfSUhepW7X:b-bv5vgq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L14)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unchanged
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 17 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9K2T52hWMxGIpIcfA:-NvY7fK08z0ucGdvHBmx:b-bv5vgq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L17)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unchanged
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 23 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9K9GBC161QpsaMQZ_:-NvY7fmK60vRQC7gIMdl:b-bv5vgq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L23)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unchanged
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 29 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KIGZ4gl7WwDSsszq:-NvY7gWA3s3UL5rK1VqN:b-bv5vgq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L29)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unchanged
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 38 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KOR54Y_30IlJwNkk:-NvY7h68BcxdF5t54IKA:b-bv5vgq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L38)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unchanged
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 43 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KeVa0dkCDWmEuWnY:-NvY7iEc3bEMtg1tdgPq:b-bv5vgq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L43)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unchanged
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 50 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KXrk09GMNJCqIzmE:-NvY7jULClpZVaxHXXMu:b-bv5vgq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L50)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unchanged
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 114 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9LKG91KM6bisHjhAH:-NvXunkU3DsFU16KqwkP:b-l581zf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L114)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

if i do that, it doesnt match anymore... 
https://decomp.me/scratch/95fAI
</blockquote></details>

Okay, I see - neither of them match.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 155 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9R3kqBGZuYDdch3Zx:-NvYFLhM1Cp2L0-o_YVO:b-3sm2on) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L155)):*
<details><summary><i>Previ [...]

2024-04-15 20:55 UTC, Moddimation reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 36 of 46 files reviewed, 24 unresolved discussions (waiting on @MonsterDruide1 and @tetraxile)

___
*[`lib/al/include/Library/LiveActor/ActorAnimFunction.h` line 319 at r7](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NuuHiqk06OtBjsZPYTz:-NvYJz8T3M6-AACRSxv_:b-lgzs1v) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2857ff3011407b1f1ef7f629083473618f3c5114/lib/al/include/Library/LiveActor/ActorAnimFunction.h#L319)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Hmm. Very interesting, do not add them then.
</blockquote></details>

or maybe they just wanted to group them in a namespace for some reason
___
*[`lib/al/include/Project/Anim/AnimInfo.h` line 24 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvY5bFB9y7AzGe94Sm5:-NvYPCXs9vcUgvoFcxq1:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/include/Project/Anim/AnimInfo.h#L24)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

The symbol says `void*` as second parameter here. Even if it might be more specific in practice, to generate matching code/symbols again we have to follow their types.
</blockquote></details>

Done.
___
*[`lib/al/include/Project/Anim/AnimPlayerBase.h` line 12 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvY5qJO6qkj_rDCWGrn:-NvYPRK731yAz7TZAiOm:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/include/Project/Anim/AnimPlayerBase.h#L12)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This one is not `=0` (see `A3BD64`)
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 19 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9OsDX0ks7rxM2K40s:-NvYPX6FBu65xcv6LWfu:b-ftcpn5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L19)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No, I meant you should remove the double parentheses
</blockquote></details>

Done. one of the changes wiped by my WSL reset
___
*[`lib/al/src/Library/LiveActor/ActorActionFunction.cpp` line 27 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9OuDf8y9XpUng6Toh:-NvYPlOS7_Cmjrd_FxwT:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorActionFunction.cpp#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No, I meant you should remove the double parentheses
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 278 at r8](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv7k0tA5Djzw-0R5-CL:-NvYVrx85P913c3yOZIM:b-l0wtiv) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8310dda54aad628bf01b959c66e0cbde74df868f/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L278)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

What happened now? That's still different than what I'm suggesting though.
</blockquote></details>

ooooh i get it
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 14 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9Jx7I42L3PRj1p7Pk:-NvYQMTH3YHojfeV_zfb:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unchanged
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 17 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9K2T52hWMxGIpIcfA:-NvYQW8o0u1Pcpye6TAo:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unchanged
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 23 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9K9GBC161QpsaMQZ_:-NvYTf3C7hOXquxqHX65:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L23)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unchanged
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 29 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KIGZ4gl7WwDSsszq:-NvYTgtD-3lvR4O_F1Wc:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L29)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unchanged
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 38 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KOR54Y_30IlJwNkk:-NvYQmJu2BpDDZVMWToW:b-4h0s3i) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L38)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unchanged
</blockquote></details>

wym its changed
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 43 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KeVa0dkCDWmEuWnY:-NvYQzii7gdleyGJHgHV:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L43)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unchanged
</blockquote></details>

Done.
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 50 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KXrk09GMNJCqIzmE:-NvYRAy32qyhfhawTEp-:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L50)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unchanged
</blockquote></details>

done
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 229 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9ME9FDmCJEDNiqdAj:-NvYRTZiBeMwHAtN53Pw:b-7osgbq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L229)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unchanged
</blockquote></details>

it is
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 251 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9RA-e-N1H0Q871WHl:-NvYR_I-B6Li1sDXufG4:b-mw4h8t) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L251)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unchanged
</blockquote></details>

i changed it
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 285 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9RJi1DrqHzjQ4OYjg:-NvYSZLy0oU4mAsgrVBk [...]

2024-04-18 07:56 UTC, MonsterDruide1 requested changes
> Reviewed 2 of 14 files at r10, 1 of 3 files at r11, 1 of 1 files at r12, 2 of 27 files at r13, 25 of 25 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 66 of 69 files reviewed, 4 unresolved discussions (waiting on @Moddimation and @tetraxile)

___
*[`lib/al/include/Project/Anim/AnimPlayerBase.h` line 13 at r14](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvkCCRXD4AJSxPG7P_1:-NvkCCRXD4AJSxPG7P_2:b-8aq7cb) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f59e5ef2e8c6d53711f4609d573c4eeae765ef53/lib/al/include/Project/Anim/AnimPlayerBase.h#L13)):*
> ```objc
> 
>     virtual bool calcNeedUpdateAnimNext() = 0;
>     virtual void updateLast();
> ```

Wrong order: Has to be `updateLast` first to result in the correct `vtable`



_Code quote:_
```objc
    virtual bool calcNeedUpdateAnimNext() = 0;
    virtual void updateLast();
```
___
*[`lib/al/src/Library/LiveActor/ActorAnimFunction.cpp` line 38 at r10](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-Nv9KOR54Y_30IlJwNkk:-Nvk9M450GF7aT2g2zVU:b-qk7dn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d985bb1d08c25e9dc6a43437b6fbcfcd43c25168/lib/al/src/Library/LiveActor/ActorAnimFunction.cpp#L38)):*
<details><summary><i>Previously, Moddimation wrote…</i></summary><blockquote>

wym its changed
</blockquote></details>

Wasn't there before, I think - it's fine now.
___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 25 at r14](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvkB7ApAyH9JkLUCyaD:-NvkB7Aq8BvpnaGsgDZg:b-wjcxqu) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f59e5ef2e8c6d53711f4609d573c4eeae765ef53/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L25)):*
> ```cpp
> }
> void ActionFlagCtrl::start(const char* name) {
>     if (0 < mInfoCount) {
> ```

Check not neccessary, is done automatically by the compiler when `for` is used
___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 39 at r14](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvkBSTJ-fNKw6bJXIFG:-NvkBSTJ-fNKw6bJXIFH:bpxgq9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f59e5ef2e8c6d53711f4609d573c4eeae765ef53/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L39)):*
> ```cpp
>                 return;
>             }
>         }
> ```

Replace with inlined call to `findFlagInfo`?



_Code quote:_
```cpp
        for (int i = 0; i < mInfoCount; i++) {
            ActionFlagCtrlInfo* flagInfo = mInfoTable[i];

            if (isEqualStringCase(flagInfo->mName, name)) {
                mLastFlag = flagInfo;
                mBool = false;
                if (!(flagInfo))
                    return;

                startCtrlFlag();
                startCtrlSensor();
                return;
            }
        }
```
___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 45 at r14](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvkBNlo99ws_vv4u2jg:-NvkBNlo99ws_vv4u2jh:bferzcw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f59e5ef2e8c6d53711f4609d573c4eeae765ef53/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L45)):*
> ```cpp
> }
> ActionFlagCtrlInfo* ActionFlagCtrl::findFlagInfo(const char* name) const {
>     if (0 > mInfoCount)
> ```

Unneccessary check


<!-- Sent from Reviewable.io -->

2024-04-18 08:10 UTC, MonsterDruide1 reviewed
> Reviewed 1 of 27 files at r13.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 67 of 69 files reviewed, 4 unresolved discussions (waiting on @Moddimation and @tetraxile)



<!-- Sent from Reviewable.io -->

2024-04-18 14:01 UTC, Moddimation reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: 67 of 69 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1 and @tetraxile)

___
*[`lib/al/include/Project/Anim/AnimPlayerBase.h` line 13 at r14](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvkCCRXD4AJSxPG7P_1:-NvlQ--UEKsRSRLfZwN6:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f59e5ef2e8c6d53711f4609d573c4eeae765ef53/lib/al/include/Project/Anim/AnimPlayerBase.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Wrong order: Has to be `updateLast` first to result in the correct `vtable`
</blockquote></details>

Done.
___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 25 at r14](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvkB7ApAyH9JkLUCyaD:-NvlVh3T-wDdnfVs3OyA:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f59e5ef2e8c6d53711f4609d573c4eeae765ef53/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L25)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Check not neccessary, is done automatically by the compiler when `for` is used
</blockquote></details>

Done.
___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 39 at r14](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvkBSTJ-fNKw6bJXIFG:-NvlVhxYED-Iuh3FlC4s:b-r2v7zd) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f59e5ef2e8c6d53711f4609d573c4eeae765ef53/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L39)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Replace with inlined call to `findFlagInfo`?
</blockquote></details>

oml i got it to match :D
___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 45 at r14](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvkBNlo99ws_vv4u2jg:-NvlVlz5B3UFhTlEnvTO:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f59e5ef2e8c6d53711f4609d573c4eeae765ef53/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L45)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Unneccessary check
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-19 21:06 UTC, MonsterDruide1 requested changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: all files reviewed, 2 unresolved discussions (waiting on @Moddimation)

___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 32 at r15](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvsARTcAjaM5wYFkkrW:-NvsARTcAjaM5wYFkkrX:b-f94x63) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8220161ec33b9d80f1d12dfb9ed102755a74f020/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L32)):*
> ```cpp
>     startCtrlFlag();
>     startCtrlSensor();
>     return;
> ```

Useless return
___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 44 at r15](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvsAYfI9EEr6rhkzh9l:-NvsAYfI9EEr6rhkzh9m:b-e8mw5a) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8220161ec33b9d80f1d12dfb9ed102755a74f020/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L44)):*
> ```cpp
> void ActionFlagCtrl::update(float frame, float frameRate, float frameMax, bool isStop) {
>     if (mLastFlag && mBool)
>         if (mHitSensorKeeper)
> ```

Flip logic (early return), both in one line



_Code quote:_
```cpp
    if (mLastFlag && mBool)
        if (mHitSensorKeeper)
```


<!-- Sent from Reviewable.io -->

2024-04-19 21:26 UTC, Moddimation reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 32 at r15](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvsARTcAjaM5wYFkkrW:-NvsF69A-FsRFhqFtXDX:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8220161ec33b9d80f1d12dfb9ed102755a74f020/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L32)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless return
</blockquote></details>

Done.
___
*[`lib/al/src/Project/Action/ActionFlagCtrl.cpp` line 44 at r15](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-NvsAYfI9EEr6rhkzh9l:-NvsF76S0phwU2Ti2rBR:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8220161ec33b9d80f1d12dfb9ed102755a74f020/lib/al/src/Project/Action/ActionFlagCtrl.cpp#L44)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Flip logic (early return), both in one line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-19 21:49 UTC, MonsterDruide1 approved these changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Moddimation)



<!-- Sent from Reviewable.io -->

2024-04-20 08:19 UTC, Moddimation reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25#-:-Nvu_c1M6vpGFMsLE6nc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Moddimation)



<!-- Sent from Reviewable.io -->

2024-04-20 08:54 UTC, Moddimation reviewed
> Reviewed 8 of 30 files at r1, 1 of 7 files at r2, 1 of 11 files at r3, 2 of 5 files at r4, 2 of 11 files at r6, 1 of 8 files at r7, 9 of 20 files at r8, 2 of 5 files at r9, 7 of 14 files at r10, 1 of 3 files at r11, 1 of 1 files at r12, 2 of 27 files at r13, 24 of 25 files at r14, 2 of 3 files at r15, 2 of 2 files at r16, 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Moddimation)



<!-- Sent from Reviewable.io -->

2024-04-20 20:49 UTC, MonsterDruide1 approved these changes
> Reviewed 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/25)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Moddimation)



<!-- Sent from Reviewable.io -->

2024-04-20 20:51 UTC, merged