Add FireDrum2D actor and related functions
MonsterDruide1/OdysseyDecomp pull request #3
Opened 2021-12-09 01:30 UTC by Sanae6

- Adds implementation of `FireDrum2D` actor
- Rearranges some functions relating to 2D/3D objects
- Implements some functions from `ActorDimensionKeeper`

2021-12-19 18:59 UTC, MonsterDruide1 requested changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: all files reviewed, 33 unresolved discussions (waiting on @MonsterDruide1 and @Sanae6)

___
*[lib/al/actor/ActorDimensionKeeper.h, line 8 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIx5jk2qWbjBcExYQz:-MrIx5jk2qWbjBcExYR-:b-47x9rg) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L8)):*
> ```objc
> class In2DAreaMoveControl;
> 
> class ActorDimensionKeeper {
> ```

As I'm currently going through all files to split them into multiple directories instead of just `al`, this should follow the new pattern. `game/actor/ActorDimensionKeeper.h` is better here.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 9 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIwsUQBLZrPy0DkyiJ:-MrIwsUQBLZrPy0DkyiK:bkpe9gq) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L9)):*
> ```objc
> 
> class ActorDimensionKeeper {
> public:
> ```

Even if you don't want to use/implement all functions, please declare them here. `forceChange2DKeep`, `forceEndChange2DKeep` and `update` are not listed.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 10 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIy0jI4wobYOkIs3em:-MrIy0jI4wobYOkIs3en:b-fpp0x1) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L10)):*
> ```objc
> class ActorDimensionKeeper {
> public:
>     ActorDimensionKeeper(const al::LiveActor*);
> ```

Please name the parameters, if you know what they do. Just `actor` or `live_actor` should be fine here.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 13 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIw_lI0G_Hdbk0P9tv:-MrIw_lI0G_Hdbk0P9tw:b-1rj07p) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L13)):*
> ```objc
>     void validate();
>     void invalidate();
> ```

Member variables should be `private:`.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 14 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIw1t5-mWtmaRtdmmA:-MrIw1t5-mWtmaRtdmmB:b-kak3nb) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L14)):*
> ```objc
>     void invalidate();
> 
>     const al::LiveActor* mLiveActor;                      // 0x00
> ```

Please remove the `// offset` comments. They come from the old repo, I'm currently going through the files to remove such annotations, as they don't really add any information.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 21 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIwALEE_Y1_eN_LQh9:-MrIwALEE_Y1_eN_LQhA:b-uri8i1) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L21)):*
> ```objc
>     bool isCanChange2D = false;                           // 0x0C
>     bool isCanChange3D = false;                           // 0x0D
>     char padding_2[0x2];                                  // 0x0E
> ```

If nothing accesses this padding, it's not necessary here.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 23 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIxSXD-fbdPGzzr3Yb:-MrIxSXD-fbdPGzzr3Yc:b-kzwopf) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L23)):*
> ```objc
>     char padding_2[0x2];                                  // 0x0E
>     In2DAreaMoveControl* mIn2DAreaMoveControl = nullptr;  // 0x10
> };
> ```

Newline is missing.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 23 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIxgTXBsJTZZLtxnut:-MrIxgTXBsJTZZLtxnuu:b-6k5x0e) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L23)):*
> ```objc
>     char padding_2[0x2];                                  // 0x0E
>     In2DAreaMoveControl* mIn2DAreaMoveControl = nullptr;  // 0x10
> };
> ```

If you have size information on this class, please add it with `static_assert(sizeof(ActorDimensionKeeper) == 0xNNN)`!
___
*[lib/al/actor/rsDimension.h, line 9 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIyUOJ7E1OI_n9uBRe:-MrIyUOJ7E1OI_n9uBRf:bphzch3) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/rsDimension.h#L9)):*
> ```objc
> class ActorDimensionKeeper;
> 
> namespace rs {
> ```

Following the new file setup, this should go into `rs/Dimension.h`. Not sure if that will be its final name/path.
___
*[lib/al/actor/rsDimension.h, line 11 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIyH-DDsegAIrnPSVk:-MrIyH-EBfrSymaBvwQQ:bs4w2rj) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/rsDimension.h#L11)):*
> ```objc
> namespace rs {
> 
> ActorDimensionKeeper* createDimensionKeeper(const al::LiveActor* liveActor);
> ```

Parameters follow snake case, so `live_actor` would be the right one to use here.
___
*[lib/al/actor/rsDimension.h, line 12 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIyQ858O7Nbc_MgDK0:-MrIyQ858O7Nbc_MgDK1:bhzzmtf) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/rsDimension.h#L12)):*
> ```objc
> 
> ActorDimensionKeeper* createDimensionKeeper(const al::LiveActor* liveActor);
> void updateDimensionKeeper(ActorDimensionKeeper*);
> ```

Please name the parameters. Same for all functions below.
___
*[lib/al/objects/FireDrum2D/FireDrum2D.h, line 4 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIzMPb59Qd4fdUKjrf:-MrIzMPb59Qd4fdUKjrg:borscwo) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/objects/FireDrum2D/FireDrum2D.h#L4)):*
> ```objc
> 
> #include "al/LiveActor/LiveActor.h"
> #include "al/actor/ActorDimensionKeeper.h"
> ```

Stubbing this should be enough, then include it in the `cpp`.
___
*[lib/al/objects/FireDrum2D/FireDrum2D.h, line 5 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIzEb52TI1PMjv2hme:-MrIzEb52TI1PMjv2hmf:b-w3inz) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/objects/FireDrum2D/FireDrum2D.h#L5)):*
> ```objc
> #include "al/LiveActor/LiveActor.h"
> #include "al/actor/ActorDimensionKeeper.h"
> #include "al/actor/ActorInitInfo.h"
> ```

Also just a stub.
___
*[lib/al/objects/FireDrum2D/FireDrum2D.h, line 9 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIywgM3W7qDRPCLCXj:-MrIywgM3W7qDRPCLCXk:b-3a5yfr) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/objects/FireDrum2D/FireDrum2D.h#L9)):*
> ```objc
> #include "game/iuse/IUseDimension.h"
> 
> class FireDrum2D : public al::LiveActor, public IUseDimension {
> ```

Move into `game/objects/FireDrum2D/FireDrum2D.h`.
___
*[lib/al/objects/FireDrum2D/FireDrum2D.h, line 12 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIzNnN4AlAKM7a-io-:-MrIzNnN4AlAKM7a-io0:b19azf6) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/objects/FireDrum2D/FireDrum2D.h#L12)):*
> ```objc
> public:
>     FireDrum2D(const char* actorName);
>     virtual void init(const al [...]

2021-12-19 23:31 UTC, MonsterDruide1 requested changes
> Reviewed 30 of 39 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: 33 of 42 files reviewed, 36 unresolved discussions (waiting on @MonsterDruide1 and @Sanae6)

___
*[src/game/actor/CMakeLists.txt, line 3 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrK0ohM-SJ9aIpMTuS5:-MrK0ohN-ve_2sWddlDW:b4w7rnd) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/f3a8d7c045ba4cb4d6cb497976429a64830be8af/src/game/actor/CMakeLists.txt#L3)):*
> ```CMake
> target_sources(odyssey PRIVATE
>     ActorDimensionKeeper.cpp
> )
> ```

Newline missing.
___
*[src/game/objects/FireDrum2D/CMakeLists.txt, line 2 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrK0te-6h6XMgjI9ofh:-MrK0te-6h6XMgjI9ofi:bpivlux) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/f3a8d7c045ba4cb4d6cb497976429a64830be8af/src/game/objects/FireDrum2D/CMakeLists.txt#L2)):*
> ```CMake
> target_sources(odyssey PRIVATE
>         FireDrum2D.cpp
> ```

That's a bit too much indentation I think... please check other files, and adjust this one accordingly.
___
*[src/game/objects/Mofumofu/CMakeLists.txt, line 2 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrK15EJBICUTVdy9ACF:-MrK15EJBICUTVdy9ACG:byfb6vl) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/f3a8d7c045ba4cb4d6cb497976429a64830be8af/src/game/objects/Mofumofu/CMakeLists.txt#L2)):*
> ```CMake
> target_sources(odyssey PRIVATE
>         MofumofuWarpHole.cpp
> ```

Same here, might be too much indentation.


<!-- Sent from Reviewable.io -->

2021-12-19 23:49 UTC, Sanae6 reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: 30 of 42 files reviewed, 36 unresolved discussions (waiting on @MonsterDruide1 and @Sanae6)

___
*[lib/al/player/PlayerAnimator.h, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIzZjABuF2c-Ea2xV7:-MrK2IT8C36qhQAo9Xep:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/player/PlayerAnimator.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Good catch! Even removing the `sead` should be good here: `<prim/seadSafeString.h>`
</blockquote></details>

Done.
___
*[lib/al/util/OtherUtil.h, line 171 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ-O2Y7lOXqUgd_kJ5:-MrK2v713fFthP0_N5_T:bknlmwo) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/util/OtherUtil.h#L171)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

If avoidable, don't put them in this file... it was just intended for a quick store before cleaning up/sorting them into the correct files.
</blockquote></details>

Do you have any suggestions for where to put it instead?
___
*[lib/al/util/OtherUtil.h, line 171 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ-KgS-nAlbHuxtCey:-MrK30fI5TNkLqtWDq8Z:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/util/OtherUtil.h#L171)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Name the parameters if known.
</blockquote></details>

Done.
___
*[lib/al/util/OtherUtil.h, line 186 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ-XIoDHf7dKmwxeAm:-MrK3EyjDdtszClRR_Gf:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/util/OtherUtil.h#L186)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Name the parameters if known. Move to different file.
</blockquote></details>

Done.
___
*[src/game/actor/CMakeLists.txt, line 3 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrK0ohM-SJ9aIpMTuS5:-MrK43qA1VF3ipGQM-1O:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/f3a8d7c045ba4cb4d6cb497976429a64830be8af/src/game/actor/CMakeLists.txt#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Newline missing.
</blockquote></details>

Done.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 8 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIx5jk2qWbjBcExYQz:-MrK0uqc3BFz7b6I8PoS:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L8)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

As I'm currently going through all files to split them into multiple directories instead of just `al`, this should follow the new pattern. `game/actor/ActorDimensionKeeper.h` is better here.
</blockquote></details>

Done.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 9 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIwsUQBLZrPy0DkyiJ:-MrK0u9a1sfog7WMUo9a:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L9)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Even if you don't want to use/implement all functions, please declare them here. `forceChange2DKeep`, `forceEndChange2DKeep` and `update` are not listed.
</blockquote></details>

Done.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 10 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIy0jI4wobYOkIs3em:-MrK0tud5JHI7kp04QQR:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L10)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Please name the parameters, if you know what they do. Just `actor` or `live_actor` should be fine here.
</blockquote></details>

Done.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 13 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIw_lI0G_Hdbk0P9tv:-MrK0soJ2iYy6ygfmbrn:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Member variables should be `private:`.
</blockquote></details>

Done.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 14 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIw1t5-mWtmaRtdmmA:-MrK0rIp3pd01jt7kbd6:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Please remove the `// offset` comments. They come from the old repo, I'm currently going through the files to remove such annotations, as they don't really add any information.
</blockquote></details>

Done.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 21 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIwALEE_Y1_eN_LQh9:-MrK1I8E7hBLVfby8TGo:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L21)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

If nothing accesses this padding, it's not necessary here.
</blockquote></details>

Done.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 23 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIxSXD-fbdPGzzr3Yb:-MrK1IgC-vTNR_1mbEnR:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L23)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Newline is missing.
</blockquote></details>

Done.
___
*[lib/al/actor/ActorDimensionKeeper.h, line 23 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIxgTXBsJTZZLtxnut:-MrK5HZO9ICPu1Exbq6D:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/actor/ActorDimensionKeeper.h#L23)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

If you have size information on this class, please add it with `static_assert(sizeof(ActorDimensionKeeper) == 0xNNN)`!
</blockquote></details>

Done.
___
*[lib/al/sensor/rsSensor.h, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrIzu30CkXcYcs-jDtT:-MrK1PP53Nmjr_yqnxhs:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/sensor/rsSensor.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Move to `rs/Sensor.h`.
</blockquote></details>

Done.
___
*[lib/al/sensor/rsSensor.h, line 5 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ--si-iRSo_19sxpq:-MrK1PwI5G_gihvN6Q3A:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/sensor/rsSensor.h#L5)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Stub for this class is missing?
</blockquote></details>

Done.
___
*[lib/al/sensor/rsSensor.h, line 5 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ-FuCBX2yatxYp84U:-MrK1QfhBpBnAJlBozar:b-896fix) ([ [...]

2021-12-20 00:22 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 39 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: 31 of 42 files reviewed, 6 unresolved discussions (waiting on @MonsterDruide1 and @Sanae6)

___
*[lib/al/util/OtherUtil.h, line 171 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ-O2Y7lOXqUgd_kJ5:-MrK98vk-DEN7IdAObqs:b-f0pfj2) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/util/OtherUtil.h#L171)):*
<details><summary><i>Previously, Sanae6 (Sanae) wrote…</i></summary><blockquote>

Do you have any suggestions for where to put it instead?
</blockquote></details>

As there are a lot of similar functions, `sensor/SensorMsg.h` could work.
___
*[lib/game/actor/ActorDimensionKeeper.h, line 13 at r5](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrKBp723rvePnLJ47Xo:-MrKBp723rvePnLJ47Xp:bmdwfox) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/997dbdfc9aae5dda5fb3e1b28259c86093862836/lib/game/actor/ActorDimensionKeeper.h#L13)):*
> ```objc
>     void validate();
>     void invalidate();
>     ActorDimensionKeeper* forceChange2DKeep();
> ```

These three functions most likely don't return anything. This is just a false alarm by the decompiler, as the `x0`  register remains unmodified. (either from the function start, or other function calls).
___
*[lib/game/actor/ActorDimensionKeeper.h, line 17 at r5](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrKAxDgE-DCMiD-vmC-:-MrKAxDgE-DCMiD-vmC0:bipm43d) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/997dbdfc9aae5dda5fb3e1b28259c86093862836/lib/game/actor/ActorDimensionKeeper.h#L17)):*
> ```objc
>     bool update();
> 
>     bool getIs2D() { return is2D; }
> ```

These functions should be const: `bool getIs2D() const { return is2D; }`. Same for all others below.
___
*[lib/game/actor/ActorDimensionKeeper.h, line 34 at r5](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrKB83aBeI_U3E7iPNi:-MrKB83aBeI_U3E7iPNj:bz17kiu) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/997dbdfc9aae5dda5fb3e1b28259c86093862836/lib/game/actor/ActorDimensionKeeper.h#L34)):*
> ```objc
> };
> 
> static_assert(sizeof(ActorDimensionKeeper) == 0x18);
> ```

Newline missing. To match the style of the other files, you can also move that assert up one line (so it is in the next line after `};`)
___
*[src/al/objects/FireDrum2D/FireDrum2D.cpp, line 14 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ1_6t96Brvw92J4Rg:-MrKBN4L6odI3_prdzhG:b90qh07) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/src/al/objects/FireDrum2D/FireDrum2D.cpp#L14)):*
<details><summary><i>Previously, Sanae6 (Sanae) wrote…</i></summary><blockquote>

No, changed to not use inline.
</blockquote></details>

Wait, did that stop it from matching now?


<!-- Sent from Reviewable.io -->

2021-12-20 00:25 UTC, MonsterDruide1 reviewed
> Reviewed 5 of 39 files at r2.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: 36 of 42 files reviewed, 6 unresolved discussions (waiting on @MonsterDruide1 and @Sanae6)



<!-- Sent from Reviewable.io -->

2021-12-20 01:21 UTC, Sanae6 reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: 36 of 44 files reviewed, 6 unresolved discussions (waiting on @MonsterDruide1)

___
*[lib/game/actor/ActorDimensionKeeper.h, line 13 at r5](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrKBp723rvePnLJ47Xo:-MrKM3JFAb1jXNiUR3ZQ:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/997dbdfc9aae5dda5fb3e1b28259c86093862836/lib/game/actor/ActorDimensionKeeper.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

These three functions most likely don't return anything. This is just a false alarm by the decompiler, as the `x0`  register remains unmodified. (either from the function start, or other function calls).
</blockquote></details>

Done.
___
*[lib/game/actor/ActorDimensionKeeper.h, line 17 at r5](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrKAxDgE-DCMiD-vmC-:-MrKOlKe3j-uQbpS3HQs:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/997dbdfc9aae5dda5fb3e1b28259c86093862836/lib/game/actor/ActorDimensionKeeper.h#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

These functions should be const: `bool getIs2D() const { return is2D; }`. Same for all others below.
</blockquote></details>

Done.
___
*[lib/game/actor/ActorDimensionKeeper.h, line 34 at r5](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrKB83aBeI_U3E7iPNi:-MrKFZN40nDuN527fryN:bytu7aj) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/997dbdfc9aae5dda5fb3e1b28259c86093862836/lib/game/actor/ActorDimensionKeeper.h#L34)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Newline missing. To match the style of the other files, you can also move that assert up one line (so it is in the next line after `};`)
</blockquote></details>

Moving `static_assert` into the class requires me to create an incomplete declaration at the top, and making that change doesn't really make sense in my opinion.
___
*[lib/al/util/OtherUtil.h, line 171 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ-O2Y7lOXqUgd_kJ5:-MrKG-vf8w1QSQFNrH5m:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/lib/al/util/OtherUtil.h#L171)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

As there are a lot of similar functions, `sensor/SensorMsg.h` could work.
</blockquote></details>

Done.
___
*[src/al/objects/FireDrum2D/FireDrum2D.cpp, line 9 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ1Haz9K0keyoGLUT9:-MrKPB_FC9ky1UdB1WEv:b-dy2489) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/src/al/objects/FireDrum2D/FireDrum2D.cpp#L9)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Hmm, I'll take a look at it...
</blockquote></details>

That TODO line was copied from MofumofuWarpHole's constructor.
```cpp
MofumofuWarpHole::MofumofuWarpHole(const char* name)
    : al::LiveActor(name) {}  // TODO minor mismatch about storing `gap`
```
___
*[src/al/objects/FireDrum2D/FireDrum2D.cpp, line 14 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ1_6t96Brvw92J4Rg:-MrKE2Gz1l2BSHIF6Wv0:bfh1p7p) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/src/al/objects/FireDrum2D/FireDrum2D.cpp#L14)):*
> Why would you do it in-line like this? Does it mismatch otherwise?
Nah, I just wrote it like that, which way it was written is not important in this case.


<!-- Sent from Reviewable.io -->

2021-12-20 09:42 UTC, MonsterDruide1 requested changes
> Reviewed 3 of 3 files at r3, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: 43 of 44 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1 and @Sanae6)

___
*[lib/game/Player.h, line 3 at r6](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrMCnlWDVMs5yGHC8ne:-MrMCnlWDVMs5yGHC8nf:brlmxgb) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b2d7836b05fd6d0416fd361699df4c7b61e56a61/lib/game/Player.h#L3)):*
> ```objc
> #pragma once
> 
> class IUseDimension;
> ```

This stub is (currently) not required in this class.
___
*[lib/game/Player.h, line 11 at r6](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrMCrTh1qlMwIeBPspz:-MrMCrTiCW7hqhB4Qg7E:b-dcznvu) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b2d7836b05fd6d0416fd361699df4c7b61e56a61/lib/game/Player.h#L11)):*
> ```objc
> namespace rs {
> 
> bool isGuardNosePainCap(const al::LiveActor*);
> ```

Argument name?
___
*[lib/game/actor/ActorDimensionKeeper.h, line 34 at r5](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrKB83aBeI_U3E7iPNi:-MrMBx7x5R9F5OGYRcE-:b-2xkk1b) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/997dbdfc9aae5dda5fb3e1b28259c86093862836/lib/game/actor/ActorDimensionKeeper.h#L34)):*
<details><summary><i>Previously, Sanae6 (Sanae) wrote…</i></summary><blockquote>

Moving `static_assert` into the class requires me to create an incomplete declaration at the top, and making that change doesn't really make sense in my opinion.
</blockquote></details>

No, not *into* the class, but just one line up, so it is directly after the closing bracket of the class, without an empty line in-between.


<!-- Sent from Reviewable.io -->

2021-12-20 17:23 UTC, Sanae6 reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: 40 of 44 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[lib/game/Player.h, line 3 at r6](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrMCnlWDVMs5yGHC8ne:-MrNr5d-50LUSXYkbhER:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b2d7836b05fd6d0416fd361699df4c7b61e56a61/lib/game/Player.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This stub is (currently) not required in this class.
</blockquote></details>

Done.
___
*[lib/game/Player.h, line 11 at r6](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrMCrTh1qlMwIeBPspz:-MrNr6Y3274Dyv7Ob2bF:bfhf8o3) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b2d7836b05fd6d0416fd361699df4c7b61e56a61/lib/game/Player.h#L11)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Argument name?
</blockquote></details>

Done. I actually just moved this file from al/player/rsPlayer.h but I may as well give it a simple name anyways :+1: 
___
*[lib/game/actor/ActorDimensionKeeper.h, line 34 at r5](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrKB83aBeI_U3E7iPNi:-MrNpDPc85Qrf-rxEqtd:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/997dbdfc9aae5dda5fb3e1b28259c86093862836/lib/game/actor/ActorDimensionKeeper.h#L34)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No, not *into* the class, but just one line up, so it is directly after the closing bracket of the class, without an empty line in-between.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-20 19:58 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: all files reviewed, 3 unresolved discussions (waiting on @Sanae6)

___
*[lib/game/objects/FireDrum2D/FireDrum2D.h, line 15 at r7](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrOPme-1HJ4pzO4-rF2:-MrOPme-1HJ4pzO4-rF3:bw6vqu8) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/5e182c443336ac9a315ba3579a72096d91dfcecb/lib/game/objects/FireDrum2D/FireDrum2D.h#L15)):*
> ```objc
> public:
>     FireDrum2D(const char* name);
>     virtual void init(const al::ActorInitInfo& info) override;
> ```

As this function is already specified as `override`, `virtual` is not necessary.
___
*[lib/game/objects/FireDrum2D/FireDrum2D.h, line 23 at r7](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrOPrtWA9MsnRYcaoCA:-MrOPrtWA9MsnRYcaoCB:b-y5et83) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/5e182c443336ac9a315ba3579a72096d91dfcecb/lib/game/objects/FireDrum2D/FireDrum2D.h#L23)):*
> ```objc
>     void exeBurn();
> 
>     virtual ActorDimensionKeeper* getActorDimensionKeeper() const override;
> ```

Same here: no `virtual`.
___
*[src/al/objects/FireDrum2D/FireDrum2D.cpp, line 9 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ1Haz9K0keyoGLUT9:-MrOPWsf2cyYjVXLba8p:bfm94l1) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/src/al/objects/FireDrum2D/FireDrum2D.cpp#L9)):*
<details><summary><i>Previously, Sanae6 (Sanae) wrote…</i></summary><blockquote>

That TODO line was copied from MofumofuWarpHole's constructor.
```cpp
MofumofuWarpHole::MofumofuWarpHole(const char* name)
    : al::LiveActor(name) {}  // TODO minor mismatch about storing `gap`
```
</blockquote></details>

Changing the header to `ActorDimensionKeeper* mActorDimensionKeeper = nullptr;` fixes this diff.


<!-- Sent from Reviewable.io -->

2021-12-20 20:03 UTC, Sanae6 reviewed
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: 41 of 44 files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[lib/game/objects/FireDrum2D/FireDrum2D.h, line 15 at r7](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrOPme-1HJ4pzO4-rF2:-MrOQTKwBIZu6vWHbpwo:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/5e182c443336ac9a315ba3579a72096d91dfcecb/lib/game/objects/FireDrum2D/FireDrum2D.h#L15)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

As this function is already specified as `override`, `virtual` is not necessary.
</blockquote></details>

Done.
___
*[lib/game/objects/FireDrum2D/FireDrum2D.h, line 23 at r7](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrOPrtWA9MsnRYcaoCA:-MrOQTgG-TUTKjN68t7_:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/5e182c443336ac9a315ba3579a72096d91dfcecb/lib/game/objects/FireDrum2D/FireDrum2D.h#L23)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Same here: no `virtual`.
</blockquote></details>

Done.
___
*[src/al/objects/FireDrum2D/FireDrum2D.cpp, line 9 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3#-MrJ1Haz9K0keyoGLUT9:-MrOQplv8oVpgKKjm9HT:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/b57de32e149cad9c5c45cd1df3e2a1faf624fa0e/src/al/objects/FireDrum2D/FireDrum2D.cpp#L9)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Changing the header to `ActorDimensionKeeper* mActorDimensionKeeper = nullptr;` fixes this diff.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-20 20:09 UTC, MonsterDruide1 approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sanae6)



<!-- Sent from Reviewable.io -->

2021-12-20 20:23 UTC, MonsterDruide1 approved these changes
> Reviewed 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sanae6)



<!-- Sent from Reviewable.io -->

2021-12-20 20:24 UTC, merged