Host functions
MonsterDruide1/OdysseyDecomp pull request #44
Opened 2024-05-24 13:12 UTC by Fuzzy2319

This PR adds `Host` header and an implementation for almost every functions except `expandEnvironmentString`, `makeTmpExpandEnvironmentString` and a function that has no debug symbols.

2024-05-24 15:31 UTC, MonsterDruide1 requested changes
If you're interested in it, you can also implement the other two functions without doing the unnamed function first - just make sure that the symbol is "good enough", and it should be fine.

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-:-NyfCtTnCYqNuDJGWODH:b-24x710)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/Debug/Host.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfBU_mD_rk1wtHs8gQ:-NyfBU_mD_rk1wtHs8gR:bsykhu8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L4)):*
> ```objc
> 
> #include <prim/seadSafeString.h>
> #include "Library/Base/String.h"
> ```

The linter wants you to place an empty line above this (between the two includes)
___
*[`lib/al/include/Library/Debug/Host.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfAEho688jcdSqOiCB:-NyfAEho688jcdSqOiCC:b-m5dddu) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L7)):*
> ```objc
> 
> namespace al {
> bool tryGetComputerName(sead::BufferedSafeStringBase<char>* computerName);
> ```

Should be `sead::BufferedSafeString*`, same below
___
*[`lib/al/include/Library/Debug/Host.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfAJZi-z7knEyPx4vO:-NyfAJZi-z7knEyPx4vP:b-acukog) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L13)):*
> ```objc
> void expandEnvironmentString(
>     sead::BufferedSafeStringBase<char>* out,
>     const sead::SafeStringBase<char>& envStr);       // TODO: Needs FUN_710086f65c
> ```

`const sead::SafeString&`, same below
___
*[`lib/al/include/Library/Debug/Host.h` line 14 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfC8VJ8ATA5sMX8RSq:-NyfC8VJ8ATA5sMX8RSr:b9wwxfm) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L14)):*
> ```objc
>     sead::BufferedSafeStringBase<char>* out,
>     const sead::SafeStringBase<char>& envStr);       // TODO: Needs FUN_710086f65c
> void* FUN_710086f65c(long* param_1, long* param_2);  // TODO: Find what is this function
> ```

I'm thinking it should be `void FUN...(sead::BufferedSafeString*, const sead::SafeString&);`
___
*[`lib/al/include/Library/Debug/Host.h` line 18 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfAWcb15P66eFKRbwf:-NyfAWcb15P66eFKRbwg:b-l05969) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L18)):*
> ```objc
>     const sead::SafeStringBase<char>& envStr);  // TODO: Needs FUN_710086f65c
> StringTmp<128> makeTmpFileFullPath(const char* fileName);
> char* getALCommon();
> ```

Should probably return `const char*` instead?
___
*[`lib/al/src/Library/Debug/Host.cpp` line 16 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfDEnHEXZIzLD78Zge:-NyfDEnI5cQoE3P_rTN3:b-qwahz5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/src/Library/Debug/Host.cpp#L16)):*
> ```cpp
> bool tryGetComputerName(sead::BufferedSafeStringBase<char>* computerName) {
>     return getComputerName(computerName) > 0;
> }
> ```

Usually, it's the other way around:
```
void getComputerName( ... ) {
  tryGetComputerName(...);
}
bool tryGetComputerName(...) {
  // actual implementation
}
```

I don't think that the normal, non-`try` method should return anything.



_Code quote:_
```cpp
s32 getComputerName(sead::BufferedSafeStringBase<char>* computerName) {
    computerName->format("");
    computerName->format("");

    return sead::EnvUtil::getEnvironmentVariable(computerName, "COMPUTERNAME");
}

bool tryGetComputerName(sead::BufferedSafeStringBase<char>* computerName) {
    return getComputerName(computerName) > 0;
}
```


<!-- Sent from Reviewable.io -->

2024-05-24 17:59 UTC, Fuzzy2319 commented
> If you're interested in it, you can also implement the other two functions without doing the unnamed function first - just make sure that the symbol is "good enough", and it should be fine.

Oh OK I will try to decompile them then.

> ```objc
>     sead::BufferedSafeStringBase<char>* out,
>     const sead::SafeStringBase<char>& envStr);       // TODO: Needs FUN_710086f65c
> void* FUN_710086f65c(long* param_1, long* param_2);  // TODO: Find what is this function
> ```
> 
> I'm thinking it should be `void FUN...(sead::BufferedSafeString*, const sead::SafeString&);`

![image](https://github.com/MonsterDruide1/OdysseyDecomp/assets/61144247/1e3ca0e1-0865-4612-9c27-de67ec5fa997)
According to Ghidra's pseudocode the function should return something so I think `void*` is a better return type for now.

> _[`lib/al/src/Library/Debug/Host.cpp` line 16 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfDEnHEXZIzLD78Zge:-NyfDEnI5cQoE3P_rTN3:b-qwahz5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/src/Library/Debug/Host.cpp#L16)):_
> 
> ```c++
> bool tryGetComputerName(sead::BufferedSafeStringBase<char>* computerName) {
>     return getComputerName(computerName) > 0;
> }
> ```
> 
> Usually, it's the other way around:
> 
> ```
> void getComputerName( ... ) {
>   tryGetComputerName(...);
> }
> bool tryGetComputerName(...) {
>   // actual implementation
> }
> ```
> 
> I don't think that the normal, non-`try` method should return anything.
> 
> _Code quote:_
> 
> ```c++
> s32 getComputerName(sead::BufferedSafeStringBase<char>* computerName) {
>     computerName->format("");
>     computerName->format("");
> 
>     return sead::EnvUtil::getEnvironmentVariable(computerName, "COMPUTERNAME");
> }
> 
> bool tryGetComputerName(sead::BufferedSafeStringBase<char>* computerName) {
>     return getComputerName(computerName) > 0;
> }
> ```

It feels strange to have the logic inside `tryGetComputerName` and a function `getUserName` with the logic inside.
![image](https://github.com/MonsterDruide1/OdysseyDecomp/assets/61144247/72f91bfe-9c84-4a24-98ef-09131aa8b05d)

2024-05-24 21:08 UTC, MonsterDruide1 requested changes
Ghidra/IDA only guess with the return types, and try to be conservative, assuming that *something* is returned. I don't believe that this is the case here:
1. The call you showed is a recursive call, so it doesn't help in identifying whether there is a return value.
2. Return values are stored in the `X0` register (except if returning floats, which is definitely not the case here). If you look at the last few assembly instructions, there is nothing writing to `X0` which would usually be the case during the last block, but there, we only have X20-X29. This is not a definitive criterion though, only gives a hint that this might not return anything.
3. If this code doesn't store `X0`, maybe the code *before* it does. While the code immediately before is the recursive call and might already set up `X0` correctly, there are other references to the last block, for example `0x710086F9B0`. Here, `X0` is the result of the previous `memcpy` call, which on paper returns the `dest` part of the call - using that as return value is pretty useless though, as you would usually return the parameter directly instead of the return value of the `memcpy` call.
4. If that's still not definitive enough, we can follow another control flow backwards to `0x710086FBA8` being the last call to a function or storing `X0`. This `BLR` instruction results in a call to some `sead::SafeString::assureTermination` variant, which is a `void` function - it definitely doesn't return anything, and as nothing else writes to `X0` afterwards, the entire function must be `void`.

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-:-NygOPUe2LJGnMHvYZOx:bq4dt2p)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/src/Library/Debug/Host.cpp` line 16 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfDEnHEXZIzLD78Zge:-NygQLB88_Ir9lf5SwzG:bdtcc3m) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/src/Library/Debug/Host.cpp#L16)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

It feels strange to have the logic inside `tryGetComputerName` and a function `getUserName` with the logic inside.
![image](https://github.com/MonsterDruide1/OdysseyDecomp/assets/61144247/72f91bfe-9c84-4a24-98ef-09131aa8b05d)

</blockquote></details>

I would think that there also exists some `tryGetUserName`, which got then optimized out... but we can't really know that, and I don't know if functions are actually being optimized completely away in the compiler setup Nintendo used for SMO. Having `getComputerName` return an `int` definitely seems "more incorrect" though.


<!-- Sent from Reviewable.io -->

2024-05-25 11:45 UTC, Fuzzy2319 commented
@MonsterDruide1 I pushed the changes.

2024-05-25 12:38 UTC, MonsterDruide1 requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/src/Library/Debug/Host.cpp` line 45 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyjkIDrCHQ86T58Vd7I:-NyjkIDrCHQ86T58Vd7J:b7rzpyf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/767d03e361f101e9df5e6972c2799dd7b84ccc14/lib/al/src/Library/Debug/Host.cpp#L45)):*
> ```cpp
>     tmp.clear();
> 
>     FUN_710086f65c(&tmp, envStr);
> ```

Ohh, maybe this is an inlined call to `expandEnvironmentString`? That would explain the `clear()` call on a String that was just created.



_Code quote:_
```cpp
    tmp.clear();

    FUN_710086f65c(&tmp, envStr);
```


<!-- Sent from Reviewable.io -->

2024-05-25 13:00 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Debug/Host.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfBU_mD_rk1wtHs8gQ:-NyjcyiVCd3kroaKSwfG:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L4)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

The linter wants you to place an empty line above this (between the two includes)
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Debug/Host.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfAEho688jcdSqOiCB:-NyjczP95EzwWicwUJXd:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should be `sead::BufferedSafeString*`, same below
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Debug/Host.h` line 13 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfAJZi-z7knEyPx4vO:-Nyjczsu0h96Y9C21tPW:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`const sead::SafeString&`, same below
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Debug/Host.h` line 14 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfC8VJ8ATA5sMX8RSq:-Nyjd-Td9ufD0GeWCfvP:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I'm thinking it should be `void FUN...(sead::BufferedSafeString*, const sead::SafeString&);`
</blockquote></details>

Done.
___
*[`lib/al/include/Library/Debug/Host.h` line 18 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfAWcb15P66eFKRbwf:-Nyjd02N00P1kEomwjxy:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/include/Library/Debug/Host.h#L18)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should probably return `const char*` instead?
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Debug/Host.cpp` line 16 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyfDEnHEXZIzLD78Zge:-Nyjd1Ju4t4NB36AQtel:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/58b130600cc6968b6ce09db0ac0ecf2e3446b5c6/lib/al/src/Library/Debug/Host.cpp#L16)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I would think that there also exists some `tryGetUserName`, which got then optimized out... but we can't really know that, and I don't know if functions are actually being optimized completely away in the compiler setup Nintendo used for SMO. Having `getComputerName` return an `int` definitely seems "more incorrect" though.
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Debug/Host.cpp` line 45 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44#-NyjkIDrCHQ86T58Vd7I:-Nyjp_ApANXn1zzJ1DS4:b6sti8h) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/767d03e361f101e9df5e6972c2799dd7b84ccc14/lib/al/src/Library/Debug/Host.cpp#L45)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Ohh, maybe this is an inlined call to `expandEnvironmentString`? That would explain the `clear()` call on a String that was just created.
</blockquote></details>

That makes sense.
Done.


<!-- Sent from Reviewable.io -->

2024-05-25 13:02 UTC, MonsterDruide1 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/44)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)



<!-- Sent from Reviewable.io -->

2024-05-31 10:00 UTC, merged