Enemy: Implement `KuromadoMagicBall`
MonsterDruide1/OdysseyDecomp pull request #69
Opened 2024-06-05 22:27 UTC by GRAnimated

This is a small unused actor that would have been used by a nonexistent `Kuromado` actor, also known as the Magikoopa.

2024-06-06 09:25 UTC, MonsterDruide1 requested changes
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/69)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @GRAnimated)

___
*[`lib/al/include/Library/LiveActor/ActorInitFunction.h` line 26 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/69#-NzgrG1X1ci4NyaLnmLE:-NzgrG1X1ci4NyaLnmLF:b-6vssjv) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4b4748ec550631e92214afd5fb5cb55c79a2fe30/lib/al/include/Library/LiveActor/ActorInitFunction.h#L26)):*
> ```objc
> class SceneCameraInfo;
> 
> void initActorSceneInfo(LiveActor*, const ActorInitInfo&);
> ```

How did you sort these, and what's the rule to split them between `ActorInitFunction` and `ActorInitInfo`? If the latter one is an actual file, there should be more functions listed here in that one.


<!-- Sent from Reviewable.io -->

2024-06-06 23:38 UTC, MonsterDruide1 commented
Also, this will probably conflict with the other, huge PR, so we'll probably get this one sorted out first, then rebase the other - but let's see.

2024-10-28 17:28 UTC, LynxDev2 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/69)* status: 2 of 17 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/LiveActor/ActorInitFunction.h` line 26 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/69#-NzgrG1X1ci4NyaLnmLE:-OAJ8qo2CAXWem3bROLy:b-hoo1a8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4b4748ec550631e92214afd5fb5cb55c79a2fe30/lib/al/include/Library/LiveActor/ActorInitFunction.h#L26)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

How did you sort these, and what's the rule to split them between `ActorInitFunction` and `ActorInitInfo`? If the latter one is an actual file, there should be more functions listed here in that one.
</blockquote></details>

In my opinion `ActorInitInfo` should only have the class and the `al` functions should be in `ActorInitFunction`. I moved all of them there. There are some actors and objects that only include `ActorInitInfo` for the functions causing this change to break compiling. I don't want to add too much additional file changes to this PR which is why I made `ActorInitInfo`include `ActorInitFunction` as a temporary solution. If you want me to change all the actor classes instead, let me know


<!-- Sent from Reviewable.io -->

2024-10-28 20:06 UTC, MonsterDruide1 requested changes
> Reviewed 10 of 15 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/69)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @GRAnimated and @LynxDev2)

___
*[`lib/agl` line 1 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/69#-OAJhRhS4fm2HHoOLNso:-OAJhRhS4fm2HHoOLNsp:b-r2k7pj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7f029377dbe180bbfe90962901ae48bd0bef215d/lib/agl#L1)):*
> ```
> Subproject commit 20374c4ca7a41552f1767756730497374eef368d
> ```

Should this be changed? Why is it necessary?
___
*[`lib/al/include/Library/LiveActor/ActorInitFunction.h` line 26 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/69#-NzgrG1X1ci4NyaLnmLE:-OAJirx-43MkB0cPuuQW:b22c7nz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4b4748ec550631e92214afd5fb5cb55c79a2fe30/lib/al/include/Library/LiveActor/ActorInitFunction.h#L26)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

In my opinion `ActorInitInfo` should only have the class and the `al` functions should be in `ActorInitFunction`. I moved all of them there. There are some actors and objects that only include `ActorInitInfo` for the functions causing this change to break compiling. I don't want to add too much additional file changes to this PR which is why I made `ActorInitInfo`include `ActorInitFunction` as a temporary solution. If you want me to change all the actor classes instead, let me know
</blockquote></details>

If you check the function map, the `ActorInitInfo::` functions are somewhere in the middle of those that you just merged/moved into `ActorInitFunction`. This layout only seems to be re-creatable when using a single file, not splitting them, or am I missing something here?


<!-- Sent from Reviewable.io -->

2025-02-06 10:02 UTC, LynxDev2 commented
I completely forgot about this PR but a while ago we agreed on discord that the layout should be ActorInit[Util, Info, Function]. (Util and Function might be the other way around)

2025-02-09 10:34 UTC, MonsterDruide1 approved these changes
I don't think it matters for this PR - with the current changes, the major file layout is not touched, so if we decide that it's wrong, we can adjust it later.

> Reviewed 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/69#-:-OIeGNUV2MpHenklVZW-:bbnosvd)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)



<!-- Sent from Reviewable.io -->

2025-02-10 21:51 UTC, merged