HeapUtil functions
MonsterDruide1/OdysseyDecomp pull request #73
Opened 2024-06-07 19:09 UTC by Fuzzy2319

This PR adds `HeapUtil` functions and a header for `MemorySystem`

2024-06-07 19:36 UTC, MonsterDruide1 requested changes
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)* status: 3 of 7 files reviewed, 16 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/Memory/HeapUtil.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoAJoT8evZ8h_98OQq:-NzoAJoT8evZ8h_98OQr:b-wq09st) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/include/Library/Memory/HeapUtil.h#L3)):*
> ```objc
> #pragma once
> 
> #include <heap/seadExpHeap.h>
> ```

Useless include
___
*[`lib/al/include/Library/System/SystemKit.h` line 5 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoANI3-hBQ6KuTC2op:-NzoANI3-hBQ6KuTC2oq:bsl8t08) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/include/Library/System/SystemKit.h#L5)):*
> ```objc
> #include <heap/seadHeap.h>
> 
> #include "Project/Memory/MemorySystem.h"
> ```

Useless include/forward-declare instead
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 59 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoAnNwADdeLw0IlSPw:-NzoAnNx9y5JcYVEA5zz:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L59)):*
> ```cpp
> 
>     addResourceCategory("シーケンス", 0x18,
>                         alProjectInterface::getSystemKit()->getMemorySystem()->getSequenceHeap());
> ```





_Suggestion:_
```cpp
    addResourceCategory("シーケンス", 0x18, getSequenceHeap());
```
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 69 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoAsiK1UvzT13AXEQd:-NzoAsiK1UvzT13AXEQe:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L69)):*
> ```cpp
> 
>     addResourceCategory("シーケンス", 0x18,
>                         alProjectInterface::getSystemKit()->getMemorySystem()->getSequenceHeap());
> ```





_Suggestion:_
```cpp
    addResourceCategory("シーケンス", 0x18, getSequenceHeap());
```
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 81 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB9Gz3Xhdydf8g0_3:-NzoB9Gz3Xhdydf8g0_4:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L81)):*
> ```cpp
>     MemorySystem* memorySystem = alProjectInterface::getSystemKit()->getMemorySystem();
>     sead::ScopedCurrentHeapSetter heapSetter =
>         sead::ScopedCurrentHeapSetter(memorySystem->getSequenceHeap());
> ```





_Suggestion:_
```cpp
    sead::ScopedCurrentHeapSetter heapSetter = sead::ScopedCurrentHeapSetter(getSequenceHeap());
```
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 88 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB0hT969FFXA72o8H:-NzoB0hT969FFXA72o8I:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L88)):*
> ```cpp
>         addResourceCategory(
>             "シーン", 0x200,
>             alProjectInterface::getSystemKit()->getMemorySystem()->getSceneResourceHeap());
> ```





_Suggestion:_
```cpp
        addResourceCategory(
            "シーン", 0x200, getSceneResourceHeap());
```
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 91 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB2yQ4JzpIMAxBqkj:-NzoB2yQ4JzpIMAxBqkk:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L91)):*
> ```cpp
>         addResourceCategory(
>             "シーン", 0x200,
>             alProjectInterface::getSystemKit()->getMemorySystem()->getSceneResourceHeap());
> ```





_Suggestion:_
```cpp
        addResourceCategory(
            "シーン", 0x200, getSceneResourceHeap());
```
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 100 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBL7ABnU_9R-rEVWt:-NzoBL7ABnU_9R-rEVWu:bnj7hl0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L100)):*
> ```cpp
>     MemorySystem* memorySystem = alProjectInterface::getSystemKit()->getMemorySystem();
>     sead::ScopedCurrentHeapSetter heapSetter =
>         sead::ScopedCurrentHeapSetter(memorySystem->getSequenceHeap());
> ```

same as above



_Code quote:_
```cpp
    MemorySystem* memorySystem = alProjectInterface::getSystemKit()->getMemorySystem();
    sead::ScopedCurrentHeapSetter heapSetter =
        sead::ScopedCurrentHeapSetter(memorySystem->getSequenceHeap());
```
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 107 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBNxwDQFJATSh-JVg:-NzoBNxwDQFJATSh-JVh:bnj7hl0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L107)):*
> ```cpp
>     addResourceCategory(
>         "シーン", 0x200,
>         alProjectInterface::getSystemKit()->getMemorySystem()->getSceneResourceHeap());
> ```

same as above
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 110 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBPEj60eAlhwUNv_H:-NzoBPEj60eAlhwUNv_I:bnj7hl0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L110)):*
> ```cpp
>     addResourceCategory(
>         "シーン", 0x200,
>         alProjectInterface::getSystemKit()->getMemorySystem()->getSceneResourceHeap());
> ```

same as above
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 135 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBWpU4HhMV164ehbo:-NzoBWpU4HhMV164ehbp:bnj7hl0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L135)):*
> ```cpp
>     MemorySystem* memorySystem = alProjectInterface::getSystemKit()->getMemorySystem();
>     sead::ScopedCurrentHeapSetter heapSetter =
>         sead::ScopedCurrentHeapSetter(memorySystem->getSequenceHeap());
> ```

same as above



_Code quote:_
```cpp
    MemorySystem* memorySystem = alProjectInterface::getSystemKit()->getMemorySystem();
    sead::ScopedCurrentHeapSetter heapSetter =
        sead::ScopedCurrentHeapSetter(memorySystem->getSequenceHeap());
```
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 141 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBZp2D5OQnUuLWec-:-NzoBZp2D5OQnUuLWec0:bnj7hl0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L141)):*
> ```cpp
>     addResourceCategory(
>         "コースセレクト", 0x40,
>         alProjectInterface::getSystemKit()->getMemorySystem()->getCourseSelectResourceHeap());
> ```

same as above
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 154 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBb9Y34BkhwbJm96Q:-NzoBb9Z13ewNWlSDmMh:bnj7hl0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L154)):*
> ```cpp
>     MemorySystem* memorySystem = alProjectInterface::getSystemKit()->getMemorySystem();
>     sead::ScopedCurrentHeapSetter heapSetter =
>         sead::ScopedCurrentHeapSetter(memorySystem->getSequenceHeap());
> ```

same as above



_Code quote:_
```cpp
    MemorySystem* memorySystem = alProjectInterface::getSystemKit()->getMemorySystem();
    sead::ScopedCurrentHeapSetter h [...]

2024-06-07 20:05 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)* status: 3 of 7 files reviewed, 16 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/Memory/HeapUtil.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoAJoT8evZ8h_98OQq:-NzoEiALE2znAzaFoc-5:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/include/Library/Memory/HeapUtil.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include
</blockquote></details>

Done.
___
*[`lib/al/include/Library/System/SystemKit.h` line 5 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoANI3-hBQ6KuTC2op:-NzoEOOA6kd5HdWooBbV:b-zg9gke) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/include/Library/System/SystemKit.h#L5)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include/forward-declare instead
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/FUoZ8F0mKDj3KNYa7ZiIcRX-/image.png)
It doesn't compile if I forward-declare.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 59 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoAnNwADdeLw0IlSPw:-NzoGq_E8nDZhl8O0jqw:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L59)):*
> ```cpp
> 
>     addResourceCategory("シーケンス", 0x18,
>                         alProjectInterface::getSystemKit()->getMemorySystem()->getSequenceHeap());
> ```

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 69 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoAsiK1UvzT13AXEQd:-NzoGpc65MLJIAXHhSAV:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L69)):*
> ```cpp
> 
>     addResourceCategory("シーケンス", 0x18,
>                         alProjectInterface::getSystemKit()->getMemorySystem()->getSequenceHeap());
> ```

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 81 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB9Gz3Xhdydf8g0_3:-NzoHGV06HeODrONSkae:b62b0ei) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L81)):*
> ```cpp
>     MemorySystem* memorySystem = alProjectInterface::getSystemKit()->getMemorySystem();
>     sead::ScopedCurrentHeapSetter heapSetter =
>         sead::ScopedCurrentHeapSetter(memorySystem->getSequenceHeap());
> ```

![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/gtiS10ab18jgp9ZW203NKgL2/image.png)
It doesn't match with this code.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 88 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB0hT969FFXA72o8H:-NzoGnLR6-B4CDeA8JaE:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L88)):*
> ```cpp
>         addResourceCategory(
>             "シーン", 0x200,
>             alProjectInterface::getSystemKit()->getMemorySystem()->getSceneResourceHeap());
> ```

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 91 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB2yQ4JzpIMAxBqkj:-NzoGmdQ8lqJzoq5SF8W:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L91)):*
> ```cpp
>         addResourceCategory(
>             "シーン", 0x200,
>             alProjectInterface::getSystemKit()->getMemorySystem()->getSceneResourceHeap());
> ```

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 100 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBL7ABnU_9R-rEVWt:-NzoHgudDgP6pkjOaxgg:b-sjpsof) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L100)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

It doesn't match with this code.
![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/D-dbbxT03NfFygEhoYvtyM4V/image.png)
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 107 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBNxwDQFJATSh-JVg:-NzoGl4vEqdVO9Lz0V_F:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L107)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 110 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBPEj60eAlhwUNv_H:-NzoGkUs9WywWxUlEXNc:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L110)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 135 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBWpU4HhMV164ehbo:-NzoIBqb8L2GKL2Lezl0:b-hzznqy) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L135)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Same as the other.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 141 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBZp2D5OQnUuLWec-:-NzoGjQV7Ckav6GOkV_7:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L141)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 154 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBb9Y34BkhwbJm96Q:-NzoIJrg7iIFKsyeeUg0:bvhx73c) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L154)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Same as the other
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 161 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBc3S0KfkRC-OzD3L:-NzoG5eI64JrwzsEHmuI:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L161)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 179 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBdaE3HUCLBA-9ch5:-NzoGCP82J0Nsb2Q5-_X:bt1111o) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L179)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

`getPlayerResourceHeap()` doesn't exist according to the function map
___
*[`src/System/ProjectInterface.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBg2C3h3lwK9sIwrI:-Nzo [...]

2024-06-07 20:10 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/System/SystemKit.h` line 5 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoANI3-hBQ6KuTC2op:-NzoIwPs6a5cpgDSnq73:bp6uo6f) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/include/Library/System/SystemKit.h#L5)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/FUoZ8F0mKDj3KNYa7ZiIcRX-/image.png)
It doesn't compile if I forward-declare.
</blockquote></details>

Yeah, remove the include from here and add it to the `cpp` instead.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 81 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB9Gz3Xhdydf8g0_3:-NzoJQW181WH2kaueij8:bhpk7wu) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L81)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/gtiS10ab18jgp9ZW203NKgL2/image.png)
It doesn't match with this code.
</blockquote></details>

Can you create a `decomp.me` for one of them?
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 179 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBdaE3HUCLBA-9ch5:-NzoJZBkEibBpHyCVxJx:bfv0w6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L179)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

`getPlayerResourceHeap()` doesn't exist according to the function map
</blockquote></details>

Ah, alright. Ignore then.
___
*[`src/System/ProjectInterface.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBg2C3h3lwK9sIwrI:-NzoJak46ijcHfMG1GTr:b-772675) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/src/System/ProjectInterface.h#L3)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/fLh_QsSH4WFFFPoRmUvkPi3i/image.png)
It doesn't compile if I forward-declare.
</blockquote></details>

See the other, include in `cpp` instead


<!-- Sent from Reviewable.io -->

2024-06-07 20:25 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Library/System/SystemKit.h` line 5 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoANI3-hBQ6KuTC2op:-NzoKQux0nklS3AwSnQh:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/include/Library/System/SystemKit.h#L5)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Yeah, remove the include from here and add it to the `cpp` instead.
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 81 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB9Gz3Xhdydf8g0_3:-NzoKj1gDgTXoYwS_Tso:bmskzwx) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L81)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Can you create a `decomp.me` for one of them?
</blockquote></details>

https://decomp.me/scratch/qAv8M
___
*[`src/System/ProjectInterface.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBg2C3h3lwK9sIwrI:-NzoKYB780t5GlN0qmf9:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/src/System/ProjectInterface.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

See the other, include in `cpp` instead
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-07 20:28 UTC, MonsterDruide1 requested changes
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 81 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB9Gz3Xhdydf8g0_3:-NzoNqeQAY4YzZa4c4t_:bh9agek) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L81)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

https://decomp.me/scratch/qAv8M
</blockquote></details>

https://decomp.me/scratch/kAdF8

Still matches with it.


<!-- Sent from Reviewable.io -->

2024-06-07 20:36 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 81 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoB9Gz3Xhdydf8g0_3:-NzoOeLU7lDDlAVgv1DX:b-ub1pby) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L81)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

https://decomp.me/scratch/kAdF8

Still matches with it.
</blockquote></details>

I forgot to comment the line above when I tested it and the compiler didn't optimised it. 
Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 100 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBL7ABnU_9R-rEVWt:-NzoP0oV16sisX2DA5G_:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L100)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

It doesn't match with this code.
![image.png](https://files.reviewableusercontent.io/images/reviewable/61144247/D-dbbxT03NfFygEhoYvtyM4V/image.png)
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 135 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBWpU4HhMV164ehbo:-NzoP3_872JFYIEP82sw:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L135)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

Same as the other.
</blockquote></details>

Done.
___
*[`lib/al/src/Library/Memory/HeapUtil.cpp` line 154 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoBb9Y34BkhwbJm96Q:-NzoP5Lb4b_DUYf85IlU:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d82d824799b23ba2baf9e98bde9b3a030e5511c0/lib/al/src/Library/Memory/HeapUtil.cpp#L154)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

Same as the other
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-07 20:50 UTC, MonsterDruide1 requested changes
> Reviewed 1 of 7 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/include/Project/Memory/MemorySystem.h` line 14 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoRU-Q-TdALe3YDwQs:-NzoRU-Q-TdALe3YDwQt:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4bfe53225f1fad812c5837ac8a83018fd4764062/lib/al/include/Project/Memory/MemorySystem.h#L14)):*
> ```objc
>     MemorySystem(sead::Heap* heap);
> 
>     void allocFailedCallbackFunc(sead::HeapMgr::AllocFailedCallbackArg const*);
> ```





_Suggestion:_
```objc
    void allocFailedCallbackFunc(const sead::HeapMgr::AllocFailedCallbackArg*);
```
___
*[`lib/al/include/Project/Memory/MemorySystem.h` line 57 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoRiua4ziDkzxhGh3l:-NzoRiua4ziDkzxhGh3m:b-d4mvcl) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4bfe53225f1fad812c5837ac8a83018fd4764062/lib/al/include/Project/Memory/MemorySystem.h#L57)):*
> ```objc
>     AudioResourceDirector* mAudioResourceDirector;
>     bool mIsExistFileResource;
>     sead::Delegate1<MemorySystem, sead::HeapMgr::AllocFailedCallbackArg const*>* _70;
> ```

Also, I would think that this is actually a non-pointer, which would explain the following 3 arguments as well - having a self-reference in a class is weird, but being part of a `sead::Delegate` makes more sense.

With that, only this member is lacking a proper name - I think you can make something up here.



_Suggestion:_
```objc
    sead::Delegate1<MemorySystem, const sead::HeapMgr::AllocFailedCallbackArg*>* _70;
```


<!-- Sent from Reviewable.io -->

2024-06-08 09:04 UTC, Fuzzy2319 reviewed
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/include/Project/Memory/MemorySystem.h` line 14 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoRU-Q-TdALe3YDwQs:-Nzr2fOmApa2FbmzJBMs:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4bfe53225f1fad812c5837ac8a83018fd4764062/lib/al/include/Project/Memory/MemorySystem.h#L14)):*
> ```objc
>     MemorySystem(sead::Heap* heap);
> 
>     void allocFailedCallbackFunc(sead::HeapMgr::AllocFailedCallbackArg const*);
> ```

Done.
___
*[`lib/al/include/Project/Memory/MemorySystem.h` line 57 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73#-NzoRiua4ziDkzxhGh3l:-Nzr2gr65gCyG9TO5j3y:brn9naw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/4bfe53225f1fad812c5837ac8a83018fd4764062/lib/al/include/Project/Memory/MemorySystem.h#L57)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Also, I would think that this is actually a non-pointer, which would explain the following 3 arguments as well - having a self-reference in a class is weird, but being part of a `sead::Delegate` makes more sense.

With that, only this member is lacking a proper name - I think you can make something up here.
</blockquote></details>

I wasn't sure for the members after `mIsExistFileResource` but it makes more sense with a non-pointer `sead::Delegate`
Done.


<!-- Sent from Reviewable.io -->

2024-06-08 20:30 UTC, MonsterDruide1 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/73)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)



<!-- Sent from Reviewable.io -->

2024-06-08 21:12 UTC, merged